### ISSUE TITLE
As a user I want to be able to create an accordion by choosing the title, and inner contents, with the ability to have it load open.

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#1]
Proposed Solution:
Similar to how tabs are currently created.

**Comment by btopro** [comment]
If this was envisioned the way the grid-plate works (as far as HAX wiring and plate options) where things are in slots and those slots relate to which tab it is shown on. Either that or each individual thing is a title + content as a tab... will have to think through structurally but definitely needs an option.

**Comment by onelittlebecca** [comment]
Is there a way to add a setting to make the option for the accordion to appear open or at least the first item?

**Comment by btopro** [comment]
in the current accordian (which the HAX verison would completely repurpose) yes.

**Comment by btopro** [comment]
@nikkimk and I recently discussed the notion of abstracting what we currently call a "grid plate" and that a tab list, collapse fieldset, columns in a grid, are all effectively the same data model / structure but visualized differently. Pinging her so she's aware of this request and that it ties in directly in many discussions we've been having.

**Comment by btopro** [comment]
Accordian added to the demo and the HAX data updated. This is now making sure the appstore reference has the a11y-collapse included. This is now working
