### ISSUE TITLE
As a user I want to have all my options in one place.

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#10]
The menus in the editor all over the place -- one is on top, one is on top of paragraph. We need to unify this.

Take a look at the editing and action sidebars of these two sites.
https://grapesjs.com/demo.html
https://webflow.com/

**Comment by btopro** [comment]
Menus consolidated. Everything happens off the side now in one place. Far less pop ups and @nikkimk and I have discussed how to remove even more. This is something you'll just have to play with to grasp but I'm going to push the working version out to CDNs soon because it's dramatically improved.

**Comment by btopro** [comment]
### options all shown in a single panel

![image](https://user-images.githubusercontent.com/329735/75394460-2c63f400-58be-11ea-94a0-cb0bf2687dd6.png)

### options auto opened when element selected
![image](https://user-images.githubusercontent.com/329735/75394535-54535780-58be-11ea-8fa3-0b2261f2a2cb.png)

### grid
![image](https://user-images.githubusercontent.com/329735/75394567-646b3700-58be-11ea-9973-b4f6c5be04d0.png)
