### ISSUE TITLE
Allow project management "units" to be customized

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#101]
> I know some classes use
these container modules for
multi-step projects, but I
use them for course units.
Maybe we could change the
name to something more generic like “module?”

[studio-notes.pdf](https://github.com/elmsln/issues/files/4256666/studio-notes.pdf)

**Comment by btopro** [comment]
This is a training issue. That's not hard coded anywhere and they have the ability to modify that value by hitting edit
