### ISSUE TITLE
[course-intro] add support for slots for footer

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1014]
Right now the `course-intro-footer` tag will use 4 unofficial props from the theme variables system. While these could be moved to a different metadata area, it's probably better to do this via slots and skip the problem entirely (right now saving the site.json file will wipe unapproved metadata theme settings for API integrity).

- add support for slotting of tags into left and right footer
- implement the top level `course-intro` to have the `a` and `img` tags in it
- then cascade the slotted content down into the `course-intro-footer`

This will solve the long term issue of those going away from the site.json and is generally a more sustainable solution as it's a 1 time setting on initial content creation and then not touched after the fact.

**Comment by btopro** [comment]
@cgldevel i could be wrong but didn't we get this merged in recently?

**Comment by cgldevel** [comment]
Yea, we merged...You should have everything...Closing now.
