### ISSUE TITLE
[editable-table] Table disappears when filtered 

### ISSUE THREAD

**Issue by Masha-L** [elmsln/issues#105]
Hi! 
I was working with editable-table and noticed an odd behavior playing with both this example and an editable table I have:

http://www.personal.psu.edu/lnm105/editable-table/

So, in this example, if you turn on editing, turn on filtering, delete the value of a cell, toggle to display mode, click "filter" in the said empty cell - and watch the table disappear.

**Comment by btopro** [comment]
next version now has this
