### ISSUE TITLE
[video-player] full-screen / sticky corner bugs

### ISSUE THREAD

**Issue by cgldevel** [elmsln/issues#1063]
Faculty Email: A student of mine said that they were having a hard time seeing videos from HAX on a phone. Do you know if there is a better browser to use for phone or if it just does not work as well on mobile devices?

Our team tested across Android and Apple mobile devices on Chrome / Safari browsers and we can understand where the student might have experienced difficulties. Specifically: 

- Full Screen Enter / Exit Issues - Icon/option for full screen on menu not showing up on mobile in expected areas. If you rotate your phone horizontally to the side, the icon does display.

- Sticky-corner won’t disable - When you hit play button on sticky-corner player, it sends student back to the original video location.  If you press play on the original video location, it sends student back to sticky-corner mode and thus, the 'sticky-corner-conundrum'. 

See attached video for better explanation (recorded on my phone- Moto G6 - Android / Chrome).

https://user-images.githubusercontent.com/11019355/195442922-18d305ff-6286-423e-a8f7-c8922d825e71.mp4

**Comment by btopro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bill's Made-Up card](https://trello.com/c/bqS9MQp6/8-bills-made-up-card)

**Comment by btopro** [comment]
The previous message is an association to a trello card we are testing

**Comment by btopro** [comment]
dfssdf

**Comment by btopro** [comment]
@WilliamMRose can you make a card associated w/ the actual submission @cgldevel made so we can go through the real process now instead of our previous fake postings to prove it worked :)

**Comment by btopro** [comment]
Sticky corner is now disabled by default. No one will miss it lol.

Working on buttons placement for mobile today

**Comment by btopro** [comment]
between landmine fixes, button on mobile, and sticky being disabled by default, this is hopefully resolved. @cgldevel once it's in prod (today) please review and let me know if it is in fact resolved.
