### ISSUE TITLE
[inline-audio] inline audio clip w/ text that's a clickable audio player #3

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1102]
Not sure we have direct need for this, but it's following off of #732 which surfaced http://soundcite.knightlab.com/

- [ ] inline element (much like a span tag) so demo should have a few positioned within a few paragraphs of content
- [ ] audio source (mp3) that is local (don't worry about supporting things like spotify for example)
- [ ] light dom for text that is clickable
- [ ] "state" for playing
- [ ] if no text / slotted material (`this.innerText == ""`) then needs to render still but as a small play button w/ minimum width so that you can still see the progression throughout
- [ ] icon for play vs pause (pegged to state)
- [ ] CSS fills the meter based on reading the length of the audio file (`<audio>` tag can be used to obtain the data associated with it)
- [ ] `click` event to toggle playing state
- [ ] accessibility consideration for tabbing / focus state like any other link / normal audio player (the current player is NOT accessible in this way so this is enhancement beyond)
- [ ] You are NOT to use the code from their player as it is jQuery / globally scoped, it is the idea of how it works that we'll be drawing from and visually matching a similar style (with color support)
- [ ] CSS variables / parts should exist to customize things like borders, padding, font, etc
- [ ] `SimpleColors` should be used to allow for colorization and helps practice inheritance

## ::before ::after psuedo selectors
Not saying you MUST use this but these style selectors can let you do some interesting things. Here's a code pen showing how I composite things on a HR using fake before and after selectors
- https://codepen.io/btopro/pen/zYmrwXV

## SimpleColors / class inheritance
- Example install / what it does and how to use it a bit https://haxapi.vercel.app/?path=/story/system-simple-colors--simple-colors-story
- Here's an example implementation in simple icons https://github.com/elmsln/lrnwebcomponents/blob/master/elements/simple-icon/src/simple-icon.js#L6-L24

Image showing what it should look like / do
![image](https://user-images.githubusercontent.com/329735/229552282-23f395a6-2d97-40b4-b2f3-a81166ff8a9f.png)

**Comment by ethanxo** [comment]
Team 16 claims ❗

**Comment by Pandaalifter** [comment]
Looks cool, claimed.

**Comment by nboyless** [comment]
claim

**Comment by SilkyTable2** [comment]
### Claimed

**Comment by SangjinLeee** [comment]
Claimed

**Comment by asbee03** [comment]
Claimed

**Comment by asbee03** [comment]
I shall take

**Comment by MaryConnolly5** [comment]
i can do this

**Comment by DynamicPunch** [comment]
I'm down for this one.

**Comment by SilkyTable2** [comment]
https://github.com/SilkyTable2/inline-audio (base template of code, emptied out)

**Comment by btopro** [comment]
included. thank you!
