### ISSUE TITLE
[suggested-plan] tag for breaking up a week #2

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1111]
While @cgldevel is working on this, I think it would be a good project to have students chew on as a possible final project.

This is interpretive visually though a screenshot is given and the requirements are shown below.

## Requirements
- [ ] Should only make this request on visibility using an Intersection Observer. Here's a SuperClass you can use to make this happen in Lit more easily https://dev.to/btopro/intersectionobserver-based-import-5adh
- [ ] Week / label in question (String)
- [ ] Time to complete (number)
- [ ] Title as seen on right side (string)
- [ ] brief description / driving question (string)
- [ ] Array of what to expect with icons for "Reading", "Watch video", "Activity", "Quiz" which is shown as a single summary value initially (so make a basic object to represent each thing)
- [ ] expanded boolean pegged to state of the "see all" collapsed area
- [ ] "See all" should be a collapse that shows the 7 videos, 3 readings, 1 quiz in the order they appeared with the icon, title  of the thing, type, and link to it directly. Clicking on the entire summary should show all the items
- [ ] Some minor visual border to imply the items under "see all" are associated w/ that summary
- [ ] Only render the items under "See all" when expanded
- [ ] Support for multiple weeks (show at least 3) to be rendered via endpoint data (1 end point)
- [ ] able to load from an endpoint (json file via `fetch` is fine)
- [ ] Basic mobile responsiveness that reduces the design to a simplified form that looks good on a phone

![image](https://user-images.githubusercontent.com/329735/217650835-9ea89e49-cffe-4848-a6be-ba237a52d8a8.png)

**Comment by lloyd64** [comment]
I will work on this one

**Comment by e10chen** [comment]
I got this

**Comment by M18ab** [comment]
I got this 🔥

**Comment by JoeVan21** [comment]
I will take on this issue

**Comment by Jps709** [comment]
I will work on this one

**Comment by pjstrauss12** [comment]
I got this one

**Comment by platinumfishes** [comment]
Liz and I CRUSH this, claimed

**Comment by jackvanzandt** [comment]
Ill work on this one.

**Comment by gleyze** [comment]
I want to work on this one

**Comment by btopro** [comment]
@jackvanzandt @gleyze please pick something else as there are 10 above

**Comment by gleyze** [comment]
> @jackvanzandt @gleyze please pick something else as there are 10 above

sorry i did not count! I just commented on inline audio clip w/ text that's a clickable audio player #1102

**Comment by bfl5322** [comment]
> > @jackvanzandt @gleyze please pick something else as there are 10 above
> 
> sorry i did not count! I just commented on inline audio clip w/ text that's a clickable audio player #1102

I'll take it

**Comment by M18ab** [comment]
https://www.coursera.org/learn/the-science-of-well-being-for-teens#syllabus

**Comment by platinumfishes** [comment]
https://chrome.google.com/webstore/detail/snipcss/hbdnoadcmapfbngbodpppofgagiclicf?hl=en

**Comment by pjstrauss12** [comment]
A way to think about See all:
- Have a "see-all" element that can be mapped into the rest of the week badge (or whatever we call each individual week)
- Potentially have a JSON file that can render each type of activity in a week
- Move down to rendering activities
- Render each element (if type = reading, render all readings, etc.) (maybe reuse filter functions from previous project)
- Figure out how to make the dropdown look like "see all" and change it to "see less" if open
