### ISSUE TITLE
Update ELMSLN to support PHP 8.1

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#1112]
PHP 7.4 is no longer receiving security updates so presents a vulnerability. PHP 8.1 is the latest actively supported version that Drupal 7 core also supports

**Comment by btopro** [comment]
Are there things we know don't work in 8.1 currently or does core need updated or a more general notice?

**Comment by btopro** [comment]
We run U20 on our boxes which have LTS support for PHP 7 through 2030 I believe. LTS operating system will support security beyond traditional project date for the included libraries
