### ISSUE TITLE
Image gallery input seems to be broken

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1132]
There doesn't seem to be a place to input images, and if a description or title is added to the gallery, the edit function only allows the user to go and edit the heading, not the gallery.

**Comment by btopro** [comment]
absolutely nonfunctional; thank you for the report. If you could go through and do this for ALL the types that'd really help an audit that Bill and I are about to kick off starting next week and will continue over the next several weeks.

**Comment by btopro** [comment]
disabling as an option for now until we do a full gap analysis. thank you for reporting, very broken!
