### ISSUE TITLE
styled image block spacing issues

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1137]
There are problems with the styled image block, especially with spacing. Inserting a paragraph block below the image block places the paragraph block beneath the image, but not beneath the text.

Additionally, when there are two styled image blocks, you can no longer add blocks beneath the second block, it only adds to below the first one.

**Comment by btopro** [comment]
Good to note. Try this on x.vmhost.psu.edu using the "fire" build. I believe this was fixed based on reporting that @cgldevel made but we haven't rolled the fix out in production yet. If it's still an issue on fire then please update to let me know

**Comment by Peter12G** [comment]
In the fire build, the add blocks beneath adds blocks correctly beneath when it is not right or left offset. When the image is offset left or right, it adds them next to the image. If two images are offset left or right, the text goes to the top of the page.

**Comment by btopro** [comment]
offset left or right as set via the `layout` option or a different setting internal to the block?

**Comment by Peter12G** [comment]
The setting internal to the block.

**Comment by btopro** [comment]
fixed on fire
