### ISSUE TITLE
`wcf start` windows compatability

### ISSUE THREAD

**Issue by jedgar1mx** [elmsln/issues#13]
I was trying to create a new element in my windows machine after pulling down my factory from git. I keep getting this error:
`TypeError: Cannot read property 'value' of undefined                                 at Object.when (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_module s/@wcfactory/cli/src/questions/element.js:25:40)                                     at promptUser (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_modules /@wcfactory/cli/src/utils/commands.js:34:40)                                         at Element.run (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_module s/@wcfactory/cli/src/commands/element.js:12:19)                                      at Element._run (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_modul es/@oclif/command/lib/command.js:35:31)`

**Comment by btopro** [comment]
closing; reopen if still an issue but we've had people develop on windows w/ this before
