### ISSUE TITLE
try to deploy webrtc + vercel demos

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1319]
https://github.com/LouieMartin/webrtc-demo
https://github.com/sbehrends/ptwo-house
https://github.com/feross/simple-peer

Between the two, if we made it so that if accessing the same route in HAXcms you could start a conversation with other ppl on that page it would be pretty incredible. We have a user name so that'd be the unique name already populated. PeerJS / WebRTC spins up to broker the connection 1x and then it's p2p.

Goal would be to convert to a web component from r_act

**Comment by priyankgandhi0** [comment]
### **local stream microphone not working while share screen + system audio shared in HTML JS**


![Screenshot 2023-07-19 182435](https://github.com/muaz-khan/RTCMultiConnection/assets/13184098/d09f1b14-2ad8-4181-8162-5f9e0817f9de)

Here is code HTML + JS ✅
```
 function startScreenShare() {
        if (screenSharing) {
            stopScreenSharing()
        }
        navigator.mediaDevices.getDisplayMedia(
            { video: { mediaSource: "screen" }, audio: true }
        ).then((stream) => {
            setScreenSharingStream(stream);
    
            screenStream = stream;
            let videoTrack = screenStream.getAudioTracks()[0];
            videoTrack.onended = () => {
                stopScreenSharing()
            }
            if (peer) {
                let sender = currentPeer.peerConnection.getSenders().find(function (s) {
                    return s.track.kind == videoTrack.kind;
                })
                sender.replaceTrack(videoTrack)
                screenSharing = true
            }
            console.log(screenStream)
        })
    }
```




We have tried to share screen audio. When sharing the screen, microphone and screen-sharing audio do not work together. Mic does not work when system audio is on. System audio does not working if end mic is on. please explain me what is the about issue.

**Comment by btopro** [comment]
appear to not be working unfortunately
