### ISSUE TITLE
9xPETJ [tagging-question] Question that students use tags to provide qualitative analysis

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1334]
This is an instructional activity that can be used in content to test knowledge. This is common in learning management systems / assessment engines.

## Hint
Here's a demo of some basic drag and drop functionality -- https://codepen.io/btopro/details/YMMYOB

## Description
- `tagging-question` is the name of the primary tag. it should be a question but also have individual, styled "tags" or chips, much like what you find here on github
- This is like a multiple choice question except there is a question and then a sea of available tags to pick from
- The user looks at the question, considers the possible tags that match the response, and then drag and drops them in an answer area
- There is an optional area with the question for an image
- Clicking check answer button it outlines the tags that were correct answers and the ones that were incorrect
- A statement for consideration is presented per incorrect response
- The user can reset the interaction and try again until they get it right
- on correct; confetti
- A statement of why this is the correct answer is shown

## Example data
![HAX psu World changer-circle](https://github.com/elmsln/issues/assets/329735/b1e940c9-b838-4e0f-acfb-2d354926bc8d)
"Which of the following big ideas would YOU associate with this artistic work?"

Tag data (tag value, correct status, feedback to give per response)
- good form - correct - The shape of the vase clearly demonstrates craftsmanship
- poor taste - incorrect - Taste is in the eye of the designer as well as the viewer.
- contrasting themes - incorrect - There is uniformity in the shape, but there is no depth to this media to imply that it is contrasting with other figures.
- AI - correct - While a modification of prior work, this is still AI generative work.
- shading - incorrect - while there is a light source and a shadow cast, shading is a term used for pencil based sketching
- original work - correct - this character is not based on any person, place, or existing trope
- accessible - incorrect - the color scheme while high contrast in some areas, loses form in others and has written text unrelated to the character

There are 7 tags that should be shown from the above data, but your element must allow for any number of tags. After creating the example one above, envision your own that has your own image, question, and then 10 possible solutions with 1/2 of them being correct and each giving feedback.

## Requirements
- There should be two implementations of this element. one that is the example data above, and another that is your own planning and creation. Both need to be shown in your demo / index.html file
- This should be a block element that in your demo sits between some text that rambles about the topic in question so it appears more real to the context (this will be used in classes)
- you should be able to supply an image and text of the question using a slot OR be property
- Tag based data needs to come from a json file. An array of objects with keys `tag` (string), `correct` (bool), `feedback` (string)
- These tags should appear in a random order as not to give away the answer
- When correct options are selected, these options should appear with a green outline. Incorrect Red. But options that were not selected (meaning still left in the pile) should NOT be presented with any visual change
- Only show correct / incorrect answer status when they click the button to check answer
- There should be buttons to check answers as well as Reset / Try again
- Reset should always be there so that you can quickly remove all tags from the board

### Accessibility considerations
- Check answers is disabled when we click it
- You should be able to tab to the tags in question and if you hit "Enter" while a tag has focus, it should switch from the answer bank to the Solution area.
- If you tab over to the tags in solution area and hit tab, it should move them back over to the available options area
- This must be built using DDD and all sizing, font and color values need to come from the design system to ensure contrast ratios

**Comment by tjk5903** [comment]
Our pod is doing tagging (front left)

**Comment by williamguthier** [comment]
My pod is doing tagging.

**Comment by infodigger33** [comment]
We are doing tagging

**Comment by devonclaudino** [comment]
Devon Claudino, EarlJon Pilarca, Luke Trexler and Marissa Tolomeo

**Comment by jsr5743** [comment]
Joseph Raudabaugh, Cassius French - Tagging

**Comment by ssambender** [comment]
Unable to make a demo using the included image as it is hosted as a private image through github

**Comment by btopro** [comment]
@ssambender download the image and include it in your repo. Recall the ` new URL ` based way we did this with past submissions

**Comment by btopro** [comment]
https://github.com/infodigger33/tagging-project
