### ISSUE TITLE
storybook not rendering components with correct properties.

### ISSUE THREAD

**Issue by jedgar1mx** [elmsln/issues#14]
When i run `yarn start` at the factory level. Storybook opens but the components don't render with the correct styles.

## storybook
![not-working](https://user-images.githubusercontent.com/21081923/56837049-0eb1a280-6847-11e9-88e3-044c5b94d530.PNG)
## polymer
![working](https://user-images.githubusercontent.com/21081923/56837062-15401a00-6847-11e9-8c47-180ece2aa1a0.PNG)

**Comment by btopro** [comment]
storybook completely refactored as far as how it's integrated now. closing out but example here http://webcomponents.psu.edu/
