### ISSUE TITLE
[video-player] add a "watch on youtube" / open in new window button

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#145]
Can be an easier way to leverage the video player, especially for those multi-tasking. Already have access to the button, icon and link itself so this shouldn't be too bad

**Comment by Griffin-Sullivan** [comment]
I'll take this one

**Comment by btopro** [comment]
PR accepted and then I fixed the icon issue. The issue was that it needed to load the iconset library's definition so that it knew where it was located. I also snagged a valid youtube icon so now it works.

**Comment by Griffin-Sullivan** [comment]
Nice!!
