### ISSUE TITLE
Image Maps

### ISSUE THREAD

**Issue by Deb-G** [elmsln/issues#1492]
Faculty in Art History would find image maps useful in their courses.  It would be a simple roll you cursor over an area of an image and a short description of that area would appear.

**Comment by btopro** [comment]
I don't debate the merrts of this, but they are very difficult to pull off both accessibly as well as from an editing perspective as it's image + content + hot spots.

For now, I'd recommend the "image hotspots" type from H5p until we replace it -- https://accessibility.psu.edu/multimedia/h5p/ claims it is among the accessible items

**Comment by Deb-G** [comment]
[like]  Gulick, Deborah reacted to your message:
________________________________
