### ISSUE TITLE
[bug] User report from HAX daemon

### ISSUE THREAD

**Issue by beb5040** [elmsln/issues#1531]
Location: https://iam.hax.psu.edu/beb5040/sites/aa100-su23/welcome
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 2560x1440
Window size: 1829x1159
Battery: 87%
Connection: 4g
Bug you experienced: Course welcome graphic clips into table of contents seated below.

**Comment by btopro** [comment]
really intended to be stand alone, setting theme to blank makes this show up correctly bc it has enough space to do so
