### ISSUE TITLE
[bug] Putting a & in a page title breaks editing

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1534]
Location: https://iam.hax.psu.edu/ptr5004/sites/aa100/new-item-5/lesson-12/page-1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 2133x1067
Battery: 100%
Connection: 4g
Bug you experienced:

If you edit a page with a "&" in the title, it does not edit the page and instead creates a new page.

https://psu.mediaspace.kaltura.com/media/The+%26+Page+Title+Issue/1_q9mtn84m

**Comment by btopro** [comment]
combination of things. our parser would brick on bad charcters. Because of how our parser is built (walking HTML submitted) < > & " could all break things and we were only stripping for `"`

new release shortly.
