### ISSUE TITLE
[bug] User report from HAX daemon

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1562]
Location: https://iam.hax.psu.edu/ptr5004/sites/aa100/new-page-5
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 2133x1067
Battery: 100%
Connection: 4g
Bug you experienced:

When changing placeholder images, there are two things called "image" that they can be changed to. One is the old image layout, the other is the current one (the one merged with what used to be called styled image).

https://psu.mediaspace.kaltura.com/media/Kaltura+Capture+recording+-+June+28th+2023%2C+4A06A05+pm/1_eeqateec

**Comment by btopro** [comment]
was told to be hidden and so is everywhere... except change type which it had handlers for. :facepalm: fixed now
