### ISSUE TITLE
Adding image labels/attributions

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/issues#157]
Figure/image labels or captions for the attributions on images - probably could be fields in the image display configuration 

the citation and license tool needs CC0 - Public Domain added, and when public domain is set, there is no author to cite. 

decrease the padding in between 50/50 columns 
<img width="1465" alt="Screen Shot 2020-04-03 at 7 10 15 PM" src="https://user-images.githubusercontent.com/15616523/78411772-cc5c1e00-75de-11ea-95b9-98f65160821b.png">

sometimes the drag option doesn't show up? Usually it appears in the upper right of whatveer I'm editing. I'm not sure why it went away. Saving and re-editing seems to fix it until it disappears randomly again. Couldn't get a screen shot because all the options disappear when you hit keys
![IMG_4609](https://user-images.githubusercontent.com/15616523/78411721-a3d42400-75de-11ea-91f7-6e14c4f98699.JPG)

Can I have the same type of spacing in lines on a single page? The column text is single spaced and looks great, but the non-column text at the bottom is 1.5 and I can't change it to match the above...
<img width="1119" alt="Screen Shot 2020-04-03 at 7 13 29 PM" src="https://user-images.githubusercontent.com/15616523/78411895-5906dc00-75df-11ea-8def-3ff78ff79e4a.png">

**Comment by btopro** [comment]
Did you do citation or license? Check both; wanting to discover your expectations for what each does or examples of how we could combine these. @nikkimk let's think of the notion of how we could relate elements in the page without us going into every "image" element type and basically replicating all this functionality per thing. #2 is similar / def related in need

**Comment by kat-wehr** [comment]
added more things to my original here

**Comment by btopro** [comment]
https://creativecommons.org/share-your-work/public-domain/cc0

**Comment by btopro** [comment]
@nikkimk added stuff to do this I believe
