### ISSUE TITLE
[bug] User report from HAX daemon

### ISSUE THREAD

**Issue by umnayaXXdevushka** [elmsln/issues#1604]
Location: https://iam.hax.psu.edu/ajm32/sites/rus101/page
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1512x982
Window size: 1297x770
Battery: 12%
Connection: 4g
Bug you experienced: Russian text is distorted after saving.

**Comment by umnayaXXdevushka** [comment]
<img width="1296" alt="Screenshot 2023-07-18 at 1 39 12 PM" src="https://github.com/elmsln/issues/assets/139910633/9c132b88-f994-4d2c-a097-292e991da80b">

**Comment by btopro** [comment]
backend issue as opposed to frontend, and only on page title. The plot thickens..

**Comment by btopro** [comment]
https://stackoverflow.com/questions/3872423/php-problem-with-russian-language

lol

**Comment by btopro** [comment]
Thank you for this report @umnayaXXdevushka . You'll see here that this literally was an issue with PHP (our backend code) and russian characters. This 1 line resolves the issue so the next release will have this fix https://github.com/elmsln/HAXcms/commit/3198833ababe372b4df79166149d39a2ef045efa
