### ISSUE TITLE
Option to disable splash screen for public websites created with hax

### ISSUE THREAD

**Issue by TaylorJadin** [elmsln/issues#1606]
It would be great if there was an option to disable the splash screen on sites created with hax.

By splash screen, I mean this loading screen:
![Capture 2023-07-18 14 00 00](https://github.com/elmsln/issues/assets/4328899/3a1eaab2-0b18-40a3-a1ea-d7a0d58d4264)

**Comment by btopro** [comment]
reducing complexity. no option to disable but it'll just be a loading bar that fades as assets load. Loading screen needed on just about all SPAs given that JS is loading to avoid assets moving everywhere visually.

**Comment by btopro** [comment]
rebuilds of managed files / new sites will behave this way by default now
