### ISSUE TITLE
[simple-fields] support for html blocks / buttons /etc

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#168]
HAXcms had some buttons and field groups which allowed for the form to have additionally interactive material like click the publish button to publish the site. I can move this stuff if needed but right now it's not possible w/ simple-fields and was previously.

**Comment by btopro** [comment]
#629 is the specific implementation not working, this issue is more generalized

**Comment by nikkimk** [comment]
This commit to master should resolve this. see index demo of simple fields for the html-block field: https://github.com/elmsln/lrnwebcomponents/commit/7af4f58c82ee02ea883f6065b653e35e00f11c72
