### ISSUE TITLE
HAX Import Modules Marked as Hidden When They Aren't

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1680]
We imported from ELMS a course and when it imported we had some strangeness with an icon that I didn't recognize.

In any case, if the modules are supposed to be hidden, I shouldn't be able to see them as I am not an author or they shouldn't have the hidden symbol next to them. I can read them.

![MicrosoftTeams-image](https://github.com/elmsln/issues/assets/123656933/e9849cf3-1df7-495e-b211-a8289cc313ed)

**Comment by btopro** [comment]
You have to set this under site settings. Site settings -> I believe last tab there's something about hiding unpublished pages. Check that and they'll go away unless logged in / author

**Comment by btopro** [comment]
![Screenshot_20230818-161429](https://github.com/elmsln/issues/assets/329735/988ff809-34a6-4161-882c-15e88c3aee51)
