### ISSUE TITLE
heading style from comps

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1695]
ODL has this
![image](https://github.com/elmsln/issues/assets/329735/274a2387-355b-4f5f-9a59-c49bd4cdc864)

sites.psu.edu has this
![image](https://github.com/elmsln/issues/assets/329735/f8ccf720-2062-40d1-8d9b-2b28c2482466)

both would be good variants as far as accent-color + border either left or offset bottom (`::after psuedo`) in the case of sites.

**Comment by btopro** [comment]
@kchar601 do we have these? I feel like I've seen them but don't want to close it until we are sure.

**Comment by kchar601** [comment]
> @kchar601 do we have these? I feel like I've seen them but don't want to close it until we are sure.

Both are able to be created using polaris colors and 'hr-vert' class on heading for first or primitive hr tag for the second

**Comment by btopro** [comment]
Can we get a listing of how to do this in the styleguide then please

**Comment by btopro** [comment]
exists in guide now
