### ISSUE TITLE
scalable video size while keeping aspect ration

### ISSUE THREAD

**Issue by tomsshow** [elmsln/issues#172]
Allowing the user to scale the video to whatever size they chose while keeping the original video aspect ratio and having some sort of reset button in case someone makes their video too large. Similar to *Reddit Enhancement Suite Youtube Video Preview + Video Scaler*

**Comment by btopro** [comment]
@tomsshow when you get a chance can you point to links / shoot a video / gif as to how this works for a user? could be a cool stand alone video player that just provides this.

**Comment by btopro** [comment]
inactive thread, closing

**Comment by tomsshow** [comment]
I dont know why I didnt see the notification for this. I am repoening and going to screen cap the scaling video player in the reddit enhancement suite.

**Comment by btopro** [comment]
unless you're implementing please close. we've not had this as a feature request so unless someone contribute it it's weight in our queue drowning our small team.
