### ISSUE TITLE
Field processing issue

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/issues#1736]
Location: https://iam.hax.psu.edu/bmr1/sites/haxcellence/tutorials/brand-new-user
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1920x1080
Window size: 1820x888
Battery: 100%
Connection: 4g
Bug you experienced:

As shown in the first time user tutorial, when a URL is pasted into the field for a video, the page does not update until you click somewhere else. That click allows the field to process. This issue threw Peter and me off until we figured out what was going on.

**Comment by btopro** [comment]
On paste event and on save

**Comment by btopro** [comment]
delayDebounceFn = setTimeout(() => {
      console.log(searchTerm)
      // Send Axios request here
    }, 3000)

    return () => clearTimeout(delayDebounceFn)
  }, [searchTerm])

Something like this. We denounce key press events on simple fields prior to insert. It's either that we don't get these events off of url based input until after blur or something else intentionally blocking it. Have to dig
