### ISSUE TITLE
[feature request] Revamp the haxtheweb.org site

### ISSUE THREAD

**Issue by heyMP** [elmsln/issues#1737]
## Room for improvement

My proposal would be to revamp the haxtheweb.org site to be a focused landing page for developers who are looking for a next generation HTML layout builder.  We want to quickly explain what HAX is, what makes it different from everything else out there and how they can quickly get started using the editor.

## What HAX is

We want to state that we consider HAX to be a next generation HTML editor and layout builder.  Framework agnostic, HTML first, drop-in replacement for existing WYSIWYG.

## What makes HAX different

- Framework / Platform agnostic: most layout builders lock you in to frameworks like React, (builder.io). We want to make HAX ultra-portable and HTML first.
- Extensible: Extend the HAX API and add your own features using web standard Custom Elements.
- Layout builder: Most WYSIWYG editors don't have drag and drop layout building, we do!
- Drop-in Replacement: Migrating from an existing editors such as CKEditor is easy
- Open Source: of course

## Usage

As a developer I want to see how this thing works.  What's the bare minimum example of how to use HAX.  This gives me a sense of what this thing actually does.  We want to show how to wrap content with the HAX editor component.  What that gives you in terms of the editor, and then how to get HTML back out of HAX.  This will prove that it can really be HTML first and a drop-in replacement for existing editors.

```html
<body>
  <h-a-x>
  <h1>Page title</h1>
  <p>content...</p>
  <iframe src="youtube.com">
  </h-a-x>
</body>
```

| Code Sample | ➡️ | Editor interface | ➡️ | Example HTML Output |
|--------------|--|-----------------|---|------------------------|

## Getting Started

The next thing I want to see as a developer is how to quickly get started.  I want to see how I can add it to an existing project and a quick code sample to prove it works.

Example:

Install this
```bash
npm install hax
```

Import the library
```js
import 'hax';
```

Then wrap any content you want to make editable with HAX
```html
  <h-a-x>
    [ your existing HTML here ]
  </h-a-x>
```

Now you can use the HAX API to save that content
```js
document.addEventListener('hax-save-event', newContent => {
  // save html content to your database
  db.updateNode('body_field_content', newContent);
})
```

## Demo

I would also like to see a super basic example of the HAX editing experience in the browser.  I want to be able to click 'see demo' and be take to a blank page that just has the HAX editor enabled.  I don't want to see anything else that is outside of the HAX editor experience because I don't want to get confused between HAX and other platform specific features such as HAXcms.

## Advanced Features

As a developer I also want to see how the extensibility of HAX works.  I want to have a separate section, away from the homepage, of how to create a new component that uses that HAX schema.  I want to see how to add that new component gets registered to be included in the HAX editor.

Beyond that introduction, I would expect to see the full schema api in a separate docs section.

**Comment by btopro** [comment]
https://oer.hax.psu.edu/bto108/sites/haxcellence/documentation/hax-frontend-devs
