### ISSUE TITLE
[bug] Text formatting issue with extraneous spaces with punctuation when text is bolded or italicized

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1743]
Location: https://iam.hax.psu.edu/ptr5004/sites/aa100/new-item-1/page-2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47
OS: Windows - 8GB RAM - 12 cores
Screen: 1280x720
Window size: 1272x598
Battery: 100%
Connection: 4g
Bug you experienced:
<img width="646" alt="Comma Error Screenshot 1" src="https://github.com/elmsln/issues/assets/123656933/e6f41cfe-8116-44ac-9c5c-423d19522d5c">
<img width="676" alt="Comma Error Screenshot 2" src="https://github.com/elmsln/issues/assets/123656933/102dcda3-cbbb-4f34-a910-879b688396bc">

When the italics or bold feature is used to edit text, if the punctuation is also not bolded or italicized with it, there is an extraneous space that occurs that can't be removed.

This is fixed by the comma being bolded or italicized.

**Comment by btopro** [comment]
![image](https://github.com/elmsln/issues/assets/329735/6a7becf0-e6c6-4350-aa99-7ce3189b6c21)

I'm not entirely sure there's even a solution for this. When inserting these tags it appears that chrome or FF or whatever browser, is adding a `&nbsp;` which is a hard coded space. This is an issue that has come up before w/ web editing in general so I can look some time but not positive there's a solution

**Comment by btopro** [comment]
```js
    // inline tags naturally format in HTML with a new line based on our previous tag formatter
    // unfortunately in text this screws stuff up by adding random spaces before and after the html tag
    content = content.replace(/(\n.\W)?<i(.*?)>/gim, "<i>");
    content = content.replace(/<\/i>\n/gim, "</i>");
    content = content.replace(/(\n.\W)?<em(.*?)>/gim, "<em>");
    content = content.replace(/<\/em>\n/gim, "</em>");
    content = content.replace(/(\n.\W)?<b(.*?)>/gim, "<b>");
    content = content.replace(/<\/b>\n/gim, "</b>");
    content = content.replace(/(\n.\W)?<strong(.*?)>/gim, "<strong>");
    content = content.replace(/<\/strong>\n/gim, "</strong>");
```

**Comment by btopro** [comment]
this should be fixed w/ the next release (no date set) and took approximately 10 hours to track down for context of how incredibly nothing issues can be impossible and impossible sounding things are super easy :p
