### ISSUE TITLE
Support Solid platform.

### ISSUE THREAD

**Issue by damooo** [elmsln/issues#1770]
[Solid](https://solidproject.org/) is a web native protocol to enable interoperable, read-write, collaborative, and decentralized web, truer to web's original vision.

> Solid adds to existing Web standards to realise a space where individuals can maintain their autonomy, control their data and privacy, and choose applications and services to fulfil their needs.

It would be great to have HAX integration with Solid. Solid protocol is w3c CG standard, and soon a WG's. It gives user autonomy to chose their own storage and idp.

Also please check [SolidOs](https://github.com/SolidOS/solidos/) project, which i believe has close resemblence to HAX goals.

**Comment by btopro** [comment]
It's a bit abstract but at a high level it appears these would be in alignment? I'm not positive what an integration would look like but HAX / HAXcms DID have integration with Beaker Browser where you could take any HAX site, take a copy of it and then based on key matching internal to that system just write the CMS pages directly without a backend (your computer becomes the backend). https://hax.cloud/ also attempts to demonstrate capabilities like this (experiment)

If HAX was the editing experience for SolidOS then you could take content and easily add advanced web components to material using an appstore.json definition coming from a CDN (which we do for demos all the time). I'm interested... but would need a lot more scope / understanding of what that integration might look like and how the two could benefit each other. I do believe our goals are in alignment from an initial reading though and appreciate you making the suggestion.
