### ISSUE TITLE
Merlin, looking for "quote" only shows up picture with quote, should show up blockquote as well.

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1807]
Location: https://iam.hax.psu.edu/ptr5004/sites/divinsky-art-010/module-two-nests/copy-of-explore-three-artists
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1153x892
Battery: 100%
Connection: 4g
![Quote](https://github.com/elmsln/issues/assets/123656933/5cd88bb3-abbe-4223-9016-0f0c5a5bcda3)

Bug you experienced:

I think that all that needs to happen here is that quote gets added to the blockquote tags.

**Comment by btopro** [comment]
`block-quote` exists maybe in that site from past usage or something. bug is with hax.psu itself not supplying the definition, I'll add it shortly.

**Comment by btopro** [comment]
works on X now
