### ISSUE TITLE
Feature Request: Ability to email the page you are on to save progress.

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1814]
Location: https://iam.hax.psu.edu/ptr5004/sites/customerdiscovery101/home

There is a requirement in the project I am working on:

"User can stop and continue – prompt to pick up where user left off. As this is self-paced, the user needs to be able to pause and continue without losing their place."

The two options that were used before this started being imported over to HAX was people not clearing their cookies or cache, or people were emailed a link. The users in this program will not log in, and it needs to be accessible to people who are using a shared computer, like a public library, so the not clearing cache solution likely won't work. 

I was wondering if it was possible to have a button, like the ones that are for the PDF, Print, QR Code, or RSS Feed section of the page that you could click, enter an email, and it would send you a link to the page that you are on. Maybe it could be called save or email?

Or, this could be a block that would be put manually on the page. I find this option to not be as good as having a button around all the time.

I have a meeting with this group on Friday to see what they have used before, but having this feature in HAX might be useful.

**Comment by btopro** [comment]
todo: Make an email this page icon mixin like QR and PDF. Add into clean themes

**Comment by btopro** [comment]
clean one and clean two both getting this
