### ISSUE TITLE
Balance aesthetic versus instructional needs with color and icon usage

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/issues#1815]
I think we have two legitimate needs that currently compete--

1) We want to enforce consistency of name, color, and icon on learning components, so that when someone uses "Learning Objectives", theirs looks like all others (in a course, a course portfolio, or even by college)

2) We need some subset of icon/color/title options that do **not** need to be consistent everywhere; I see these as aesthetic/layout driven, not instructionally driven. Freedom to do slick, color-coordinated page treatments. We are nearly there now, but we have our hands tied.

We should discuss at some point. Things I feel like I am missing are the ability to get to a true color wheel (or at least web-safe colors in their entirety), freedom to mix/match icons and colors (or have no icon at all), and a subset of components where all text (like title) is under my control.

Essentially, we want to free & empower the ID role while constraining the faculty role.

**Comment by btopro** [comment]
#1850

**Comment by btopro** [comment]
1 split out, another now has ability to override values so both met
