### ISSUE TITLE
Allow for clickable images that can hyperlink out for navigation

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/issues#1819]
I'd like to be able to click an image and have it navigate to wherever I point the link (internal page, in my case). So, maybe a new flavor in the Images category becomes "Clickable Image".

Bryan's comments in Teams: 

i mean it's probably something that gets hooked into certain block types but then those blocks have to implement this feature
so like right now the collection item supports a URL... so it'll obviously be linkable
core "link anything" is way more complicated than just "let's add support to link these specific media types"

**Comment by btopro** [comment]
#1925  will implement what's requested here
