### ISSUE TITLE
Unable to Remove Page Type Icons

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1827]
Location: https://iam.hax.psu.edu/ptr5004/sites/customerdiscovery101/home
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1912x924
Battery: 100%
Connection: 4g
Bug you experienced:

In the page settings, there is the dropdown for type. After I added the type, I can no longer remove them. Changing it to "none" causes the icon for what it was to remain on the page.

https://psu.mediaspace.kaltura.com/media/Unable+to+remove+page+type+tags/1_qc92kwk8

**Comment by btopro** [comment]
looks like a you / caching thing. if you had refreshed the page I beet it wouldn't be there. Can't replicate
