### ISSUE TITLE
Selected text not being replaced

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/issues#1832]
Bug you experienced:

In a paragraph, when selecting "Deep thoughts" starter text and replacing it with a paste, the text is not replaced but instead is appended to the end

**Comment by btopro** [comment]
`      // if we got here then we have HTML structures to pull together`
is block that's causing this since we clean up pastes we have to fake what the operation was. Most likely related to something with asking for selection in the active node being lost as it seems to blink just before insert.

**Comment by btopro** [comment]
https://stackoverflow.com/questions/3997659/replace-selected-text-in-contenteditable-div

Maybe we need a utility that we import and leverage that once we know what the text that we've cleaned up is. May need to refactor bc of shadows but worth comparing
