### ISSUE TITLE
Background color options on headings (and elsewhere)

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/issues#1833]
Currently we have 19 background color options available for headings. Our pages are becoming much more attractive, and headings are playing a major role in that. But the available color spectrum isn't nearly broad enough. If I have four or five content chunks on a page that I want to color differentiate, the best way to do is to select those values from a "color family", so that they work together but can still be differentiated. The current palate is too limited.

**Comment by btopro** [comment]
Having a tone range though much like how tags can automatically generate color differences wouldn't be a terrible idea tho

**Comment by btopro** [comment]
needs agreed upon as a whole set and each reviewed, but this is now possible and discussed many colors that exist now w/  the team.
