### ISSUE TITLE
[bug] Content Not Saving (sites/mjs100/sites/digital-toolkit

### ISSUE THREAD

**Issue by cgldevel** [elmsln/issues#1837]
Location: https://iam.hax.psu.edu/cgl109/
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1680x1050
Window size: 1519x747
Battery: 100%
Connection: 4g
Bug you experienced:

From Melissa: I add content and it doesn't save. If I am a faculty member trying to add content and this happened randomly on every other page, I'd stop using it. Please fix this. Here is the video: https://psu.mediaspace.kaltura.com/media/Kaltura+Capture+recording+-+HAX+not+saving/1_b2vmo0z1

I'm troubleshooting this further I just wanted to move the issue here instead of where she originally filed it. I suspect something is coming across with her copy/paste that is preventing the desired formatting on 'save'.  I checked the server and write permissions for the site are appropriately set to 'data-access' across the board...The name of the site in site.json is also correct. She's created other pages / content and saved fine, so this seems isolated.

**Comment by btopro** [comment]
Looks more like needs to log out of azure and back in or refresh the browser from a long running dead token. Guessing here

**Comment by btopro** [comment]
https://github.com/elmsln/issues/issues/1306
