### ISSUE TITLE
When importing from .docx, the old image block is used.

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1847]
Location: https://iam.hax.psu.edu/ptr5004/sites/midatlanticstates/mid-atlanticstates-2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1738x840
Battery: 100%
Connection: 4g
Bug you experienced:

I imported a .docx file with an image in it for a page and the image block that is used is the uneditable image that was in old hax as opposed to having all the new image editing features in the new block.

**Comment by btopro** [comment]
known issue, shouldn't import images as part of doc files. Not sure how best to account for this other than scrubbing them perhaps..

**Comment by btopro** [comment]
https://oer.hax.psu.edu/bto108/sites/haxcellence/tutorials/migrate-data-to-hax#header-23701954-bf19-e68d-0550-27bb194bf603

documentation notice left behind about this
