### ISSUE TITLE
Images in columns not staying in columns and becoming very large.

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1866]
Location: https://iam.hax.psu.edu/ptr5004/sites/aa100/new-item/lesson-1/case-study-2-chavin-de-huantar-and-andean-verticality-copy
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1912x924
Battery: 100%
Connection: 4g
Bug you experienced:

Images that were placed in columns do not stay in columns and become very large. 

![Large Image](https://github.com/elmsln/issues/assets/123656933/e2672ed8-bbe5-4917-be2b-4e47891afc93)

When one hits edit, they are where they are supposed to be.

![Edit Column Image](https://github.com/elmsln/issues/assets/123656933/56211a27-a9ec-404f-85d6-d8b7c6896d19)

This happens on pages that were already created as well as pages and images that are newly created.

This happened with the newest update and persists through theme changes (Clean Course Theme and Clean Course Two)

**Comment by btopro** [comment]
already fixed.
