### ISSUE TITLE
Polaris Navigation Disappearing

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1872]
Location: https://iam.hax.psu.edu/ptr5004/sites/customerdiscovery101-1-1/
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
OS: Windows - 8GB RAM - 16 cores
Screen: 1920x1080
Window size: 2133x1058
Battery: 100%
Connection: 4g
Bug you experienced:

https://github.com/elmsln/issues/assets/123656933/02bf3e71-5974-4032-8299-dc12cb6a01b5

The large pages are still there, but some of the children disappear and can't be navigated to.

**Comment by btopro** [comment]
contents

**Comment by btopro** [comment]
no it's there, your just not building the site the right way. If you built it like my extremely rigid mental model has in mind it'll show up! [sic]

Testing commit to fix. It's a simple fix as originally the block was apparently setup under the idea of sub-sub pages as opposed to sub pages loading :shrug: . No idea why I wrote it that way :pager:

**Comment by btopro** [comment]
![image](https://github.com/elmsln/issues/assets/329735/b05b6392-23cc-44b2-a3dc-dd93230bae3f)
