### ISSUE TITLE
Doing something with headers caused the site settings to break

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1874]
Location: https://iam.hax.psu.edu/ptr5004/sites/customerdiscovery101-3/
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
OS: Windows - 8GB RAM - 16 cores
Screen: 1920x1080
Window size: 2133x1058
Battery: 100%
Connection: 4g
Bug you experienced:

I tried to recreate this, but when I added multiple pages or images into headers, the site settings ended up breaking. I can no longer edit anything and I have only two tabs as opposed to the normal four.
![Site Settings Break Headers](https://github.com/elmsln/issues/assets/123656933/229b529e-acbf-415c-aa1e-ae7d77a5e7fe)

I put the site into a cleaner browser and still had the issue.

**Comment by btopro** [comment]
Guessing this is an array vs single instance issue. Not sure how you generated nonarray data for this output other than being a level 9000 paladin
