### ISSUE TITLE
Learning Component Block Advanced Edits Not Working

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1878]
Location: https://iam.hax.psu.edu/ptr5004/sites/customerdiscovery101-2/step2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1912x924
Battery: 100%
Connection: 3g
Bug you experienced:

When trying to edit the learning component block, the advanced features do not work. It changes in the editing phase and does not save when changed in the page. I've tried this in a few cleaner browsers.

https://psu.mediaspace.kaltura.com/media/Learning+Component+Advanced+Edits+Not+Working/1_xtqsdcr9

**Comment by btopro** [comment]
testing locally, fix should be released shortly
