### ISSUE TITLE
[bug] Bugs and feature request for audio player

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/issues#1881]
Location: https://iam.hax.psu.edu/bmr1/sites/haxcellence/peter-aeschbacher-exhibit
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1280x800
Window size: 1280x800
Battery: 100%
Connection: 4g
**Bug you experienced:** I supplied a text title but it does not appear anywhere. Not sure whether text alignment works because I can't see that.  Background color does not work (but accent does).
**Feature request:** If no thumbnail image is supplied, the height of the player remains the same. I'd prefer a minimal height player that doesn't eat as much screen real estate to no purpose. So, if you supply a thumbnail image, it is exactly as it is now. If you don't, the size is reduced to just the player itself.

**Comment by btopro** [comment]
> Bill "I want things designed the way I want them to in my head" questions the design (lack of) decisions made.

This is probably more of a "we need to design this intentionally as part of the DDD effort" as opposed to a bug / feature request.
