### ISSUE TITLE
Figuring out how to edit a page in the Collections Theme is difficult.

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1904]
Location: https://iam.hax.psu.edu/ptr5004/sites/dundundund/
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1912x924
Battery: 100%
Connection: 4g

In most themes, when editing a page, the page details line is at the top. In collections, because of the large banner image is placed before the "page details" makes it unintuitive on how to edit the large banner image. I wanted to click on the image to edit it, and that's not how it works.

Could, in that theme, the page options be embedded in the area where that image will be? Is that even possible?

**Comment by btopro** [comment]
not sure I follow? page details is where it always is

![image](https://github.com/elmsln/issues/assets/329735/2859cd1f-7092-4f7d-9c12-136d9db34652)

**Comment by btopro** [comment]
not at the moment no and I can't really think of how that would work. Until we actually ahve someone use the theme for a real purpose I'm not sure it's worth looking into to be honest. It's driven by the theme settings and then the page itself if that is supplied under Advanced. Probably more a documentation issue
