### ISSUE TITLE
Advanced options for icons in the Multiple Choice block don't do anything

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1905]
Location: https://iam.hax.psu.edu/ptr5004/sites/reallysuperfakecourse/page-2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1912x924
Battery: 100%
Connection: 4g
Bug you experienced:

I don't know if these are relics of an older system, but they don't do anything.
![Advanced MC Questions](https://github.com/elmsln/issues/assets/123656933/d3745c9f-ae17-4886-a3a1-0f7cbfd237d0)

**Comment by btopro** [comment]
dropping bc we dont want ppl customizing these anyway

**Comment by btopro** [comment]
![image](https://github.com/elmsln/issues/assets/329735/16293372-738a-45b8-a91a-2a0452b16129)
