### ISSUE TITLE
All text is bold on Windows when shared by certain users.

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1922]
![All Text Bold](https://github.com/elmsln/issues/assets/123656933/c462fb02-4bf9-4dc7-b33d-1b3137db52dc)

Deb has sent me two different pages, AA113N (https://oer.hax.psu.edu/dlg131/sites/aa113n/page-1/page-2) and Arts Admin 301 (https://oer.hax.psu.edu/dlg131/sites/artsa301/page-3) and all of the text is bold, including text that can't be edited, such as the citation under images. This is occurring in both Clean Course One and Clean Course Two.

I have checked this in Edge, Firefox, and a very clean Chrome browser and they all have the same problem, which makes me think it is a caching issue. Bill sent me pages that were in the Invent theme and the problem did not occur.

I spoke with Deb and one of the professors she is working with on a course is having the same issue.

This has led me to believe it is a Windows issue. I will check on my other Windows machines later this afternoon to see if it still there, but I have no reason to believe it wouldn't be.

**Comment by Peter12G** [comment]
After some further investigation, this seems to happen on pages that I can't edit in clean course one, clean course two, learn theme, and Polaris theme.

This does not happen in the invent theme.

It does not happen on my phone (android).

I sent this to another Windows user (using Chrome) who hadn't logged into Hax in a long time and the same issue happened.
![Unbolded IAM](https://github.com/elmsln/issues/assets/123656933/bc6fad8f-efc6-4ed0-aec4-622d6d98ad0e)

![Bolded Oer](https://github.com/elmsln/issues/assets/123656933/11508040-4e27-4c7a-ab4c-bcd11907fc34)

**Comment by btopro** [comment]
Should be fixed in newer DDD releases
