### ISSUE TITLE
CVS Uploads not saving with tables

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1944]
Location: https://iam.hax.psu.edu/ptr5004/sites/odlsyllabi/thea/thea112#header-ab8bcea2-f97e-53e7-49e6-2be1f7233f0d
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 2124x1064
Battery: 100%
Connection: 4g
Bug you experienced:

https://psu.mediaspace.kaltura.com/media/CSV+Table+Uploads+Not+Saving/1_iz2rl788

If you use the CVS upload, it appears and then the table doesn't save.

**Comment by btopro** [comment]
Is this fixed now in the latest?
