### ISSUE TITLE
CSV File Problems

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1945]
Location: https://iam.hax.psu.edu/ptr5004/sites/odlsyllabi/thea/thea111
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 2124x1064
Battery: 100%
Connection: 4g
Bug you experienced:

Two issues:

1. Download CSV does not download as a CSV, it downloads as a .txt file.

2. Uploading CSV files do not save after being uploaded into a table.

**Comment by Peter12G** [comment]
Workaround to number 2.

In advanced, upload the csv file, then delete the text in the CSV data section. Hit save and the table will work.

**Comment by btopro** [comment]
.csv is now extension on download
