### ISSUE TITLE
Request small spacing between headers and text. 

### ISSUE THREAD

**Issue by Deb-G** [elmsln/issues#1957]
Location: https://iam.hax.psu.edu/dlg131/sites/aa113n/introductiontothepsychologyofart
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1920x1080
Window size: 1389x783
Battery: 100%
Connection: 4g
Bug you experienced: I would like to see smaller spacing between headers and the text that follows so that the association between the two is more obvious.
![Screen Shot 2024-03-28 at 3 54 28 PM](https://github.com/elmsln/issues/assets/12716869/47060052-49a0-4933-a0d9-1c49ac200cab)

**Comment by btopro** [comment]
![image](https://github.com/elmsln/issues/assets/329735/98c40b8f-0f2d-479f-8bf2-677f1e009849)
it's pulled in slightly tighter but needs room to breathe

**Comment by Deb-G** [comment]
That's better!  Thank you! :-)
