### ISSUE TITLE
Lists (both bulleted and numbered) do not save text in column formats.

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1962]
Location: https://iam.hax.psu.edu/ptr5004/sites/dundundund/page-1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 2390x1197
Battery: 100%
Connection: 4g
Bug you experienced:

https://psu.mediaspace.kaltura.com/media/Bulleted+Lists+in+Column+Formats+do+Not+Save/1_5czpyki1

When you try to create a bulleted or numbered list in a column format, the text does not save and just disappears. Above is a video of this happening.

**Comment by btopro** [comment]
#982 will solve this
