### ISSUE TITLE
[feature request] Could the default for hyperlinks be opening in a new tab?

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1963]
## Room for improvement

Currently, when you add a hyperlink into text, the default is that it opens up in the same page that you are on. When I open links, I like them to open in a new tab. For instance, if I am reading an article and there is a link to further reading, I don't want to lose my place in what I'm currently reading and I will open the article to look at later. That exists in the advanced options, but is there any reason why that can't be the default?

**Comment by btopro** [comment]
makes sense; internal links it's a problem tho potentially but your right most of the time you are linking out not in

**Comment by btopro** [comment]
fixed. Words cannot express how needlessly complicated this was to solve.
