### ISSUE TITLE
[feature request] Allow Image Modal Options for Playlist Block

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1964]
https://iam.hax.psu.edu/ptr5004/sites/dundundund/page-2

Would it be possible for the images that are placed in the Playlist to have the same set of options that images do?

I was creating a slideshow of paintings to compare different paintings by the same artist and I would like to be able to click on the images and zoom in. This would be especially nice when a slideshow of different-sized images are used as you need to scroll to see the whole thing, which doesn't work as well for paintings.

Having the ability to caption and title in the Playlist would also be very nice.

**Comment by btopro** [comment]
yes.... the option to do what is built in. I am not sure how you accomplished the feat of... checks notes.... disabling the carefully prepared solution that allows for the default and instead opted for the... more difficult option.
![image](https://github.com/elmsln/issues/assets/329735/7b97ccd4-aea1-4963-9baa-710e8ccba3e9)

**Comment by btopro** [comment]
Put media image elements in it and it should work.

**Comment by btopro** [comment]
https://github.com/elmsln/issues/issues/1968
