### ISSUE TITLE
[bug] Image Compare Block Not Working

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1965]
Location: https://iam.hax.psu.edu/ptr5004/sites/dundundund/page-2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 2390x1197
Battery: 100%
Connection: 4g
Bug you experienced:

The compare image block is not pulling in images. It isn't pulling in the placeholder images either.

**Comment by btopro** [comment]
service that was supplying the fake images must have gone away. it does work when you supply media, just takes some time bc of the other media failing. switched to other cats
