### ISSUE TITLE
Template for Poems

### ISSUE THREAD

**Issue by Deb-G** [elmsln/issues#1973]
Location: https://iam.hax.psu.edu/dlg131/sites/arth101/page-11/page
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1920x1080
Window size: 1728x963
Battery: 100%
Connection: 4g
Your idea: This doesn't happen often, but every once in a while I get a request for a poem.  I tried using the citation feature for this, but the instructor didn't like it for some reason.  The layout on the page: https://iam.hax.psu.edu/dlg131/sites/arth101/page-11/page, shows a poem with spacing between lines and verses, and most poems do not look like this.   I have included screenshots with the way the poem looks on this page(https://iam.hax.psu.edu/dlg131/sites/arth101/page-11/page) and how many poems are written - single spacing between lines, double between verses.  

![Limited spacing options](https://github.com/elmsln/issues/assets/12716869/9c7382c4-8fd2-40bf-8865-29e64b9d7a59)
![Should look like this](https://github.com/elmsln/issues/assets/12716869/22b8e6e0-ddb8-471c-95ec-29ba95ab3ef3)

**Comment by btopro** [comment]
see Teams chat w/ video posted recently as far as options coming. Not going to support poems specifically but you'll be able to do modifications to hopefully lay things out and offset them a bit better like this

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=ZwHKAO38PHQ
