### ISSUE TITLE
Order of options in Earth paragraph Configure options feedback

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1974]
Location: https://try.earth.x.vmhost.psu.edu/ptr5004/sites/dundundund/page-3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1912x958
Battery: 100%
Connection: 4g

The first option is Primary color, but it doesn't change any color until you put in an accent color to make it a box or a design treatment to make the letter big. I found that to be confusing as when it says "primary color" I thought it was going to change the font, which it wasn't designed to do, but it affects options that you see after it.

**Comment by btopro** [comment]
also moved "Design treatment" ahead of both as they are where you'd really see the thing you are changing anyway
