### ISSUE TITLE
As a user I want to be able to add a caption to any image.

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#2]
Proposed Solution:
The caption field should be available to any image.

Currently the caption field is not a default field when adding an image. This needs to be corrected.

**Comment by btopro** [comment]
@McGarvelcuddy this would be a good one to step into fixing an issue that's not direct element building but instead improving upon existing ones. Everything we have called image should have something that at least represents a 'caption' or small descriptive text that's visible and just below the image. Check out haxtheweb.org and try creating different images to come up with a checklist of what ones DO NOT have a caption (recording the element name here as a list).

From there we can work through how to actually add them to the hax schema for that element or when we need to extend an existing API.

**Comment by onelittlebecca** [comment]
Where you add an image from the paragraph area is where we ran into this *i think*

**Comment by btopro** [comment]
makes sense as that's a `img` tag we'll have to do some other fun-stuff to make it work for that use-case OR we make like `simple-image` be the default image we create which only adds in a little caption area. Do you have an example you are targetting for this?

**Comment by btopro** [comment]
@cgldevel next Wed when @McGarvelcuddy  is there can you work with him to show him how to modify the HAX schemas in the images we have as well as how that all works. I think a big part of this is just ensuring that the image display types we have name fields appropriately. The main "image" referenced in this will be a slightly larger discussion but one we can definitely handle (just might need to make a new basic element)

**Comment by btopro** [comment]
#221 related

**Comment by btopro** [comment]
@nikkimk cleaned up the existing ones and added one called a11y-figure for adding long form descriptions to media in an accessible way.
