### ISSUE TITLE
Move Rollup configs into package until utils project in "elements"

### ISSUE THREAD

**Issue by heyMP** [elmsln/issues#20]
![screen shot 2018-09-20 at 10 26 57 am](https://user-images.githubusercontent.com/3428964/45825256-d26e0080-bcbf-11e8-886c-5a203a12f949.png)

What I would suggest is that any relative links to configuration files, or "global files" would be better managed by an npm package.  The benefits of this would be that the configs would be versioned so **potentially** your element would be pegged to a specific config version.  It would also mean that you could change the location or move it out of this repo and into another and it would break the build.

Being that we are going all-in on Lerna, I would feel comfortable with making a lot of npm packages.

**Comment by btopro** [comment]
We abuse the connotation of "elements" a bit since it just streamlines publishing of any npm package. If we stuff this in the elements folder under utils since it's a hodge podge of stuff, I won't complain.

**Comment by btopro** [comment]
http://npmjs.com/package/@wcfactory/rollup-umd-build
