### ISSUE TITLE
[marketing] Information architecture / restructuring of all project sites

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#201]
https://www.polymer-project.org/ is a good template to follow as far as this overall structure that matches our own

## What we have
- High level organizing thing (elmsln.org / elmsln)
- smaller, individual projects, all having their own scope (hax, haxcms, elmsln system, wcfactory, unbundled-builds, lrnwebcomponents, oerschema)
- smaller projects having their own sites (wcfactory, haxtheweb, elmsln, oerschema all currently have sites)
- blogs (elmsln has an inactive one, haxtheweb should have one)
- events (haxcamp, hax uncode)
- media (youtube channel)
- contributors (psu, ASU, NARA, waxam, etc)
- documentation (haxtheweb / wcfactory in the site itself, elmsln on gitbook)

## How to get there
- [ ] needs assessment / additional detail gathering beyond whats here
- [ ] XD / prototypes of what this looks like
  - [ ] one for the organization / elmsln.org level
  - [ ] one for the project site level with dedicated docs section off of it or doc site for ALL projects
- [ ] web components starting to be made for these
- [ ] hax11ty static site for top level, haxcms or hax11ty for doc sites that sorta thing

**Comment by onelittlebecca** [comment]
Gah! Wanted to assign this to Miran LOL if he doesn't or can't pick it up and no one else wants it, I am happy to take a stab.

**Comment by onelittlebecca** [comment]
Screw it -- assigning to myself -- Miran and I are going to work on it together.

**Comment by btopro** [comment]
You are assigned; Miran added to repo pending invite. I also have some student workers who can help out in this are and will be on boarding them later in May.

**Comment by onelittlebecca** [comment]
When you say "wcfactory, haxtheweb, elmsln, oerschema all currently have sites" -- I know haxtheweb, and I assume for elmsln you are referring to https://www.elmsln.org/

Is this the one for wcfactory: https://wcfactory.js.org/  ?
and is this the one for oerschema: http://oerschema.org/  ?

Assuming I am correct, I will begin doing a breakdown and analysis. Will pass it along once I have completed it and drawn some conclusions.

**Comment by btopro** [comment]
those are the addresses. Would be nice if we made them subdomain related in some way

**Comment by onelittlebecca** [comment]
yes, gathered that -- kk will sort my life out and put together a plan of sorts. Will pull in Miran when he decides to exist.

**Comment by onelittlebecca** [comment]
Can we do a survey of sorts in the HAX slack that would help gather data about how to organize or structure all of the various HAX offerings? Since we dont have analytics, at least we could gather some qualitative data.

**Comment by btopro** [comment]
dup of #1032 which is pushing that work forward
