### ISSUE TITLE
empty draft saved

### ISSUE THREAD

**Issue by joyously** [elmsln/issues#22]
I created a new post and messed around trying to get Hax to let me do something. It seemed like nothing worked correctly. 
I got some text into the edit box finally though.
Clicking on the WP Preview button, the post is empty.
Clicking on All Posts in the menu (to get out and try again), it let me get out without asking me to save my changes. That usually indicates that nothing was created so there is nothing to save. But there in the list was my draft post, which shouldn't be there if there was nothing to save. 
When I edited it again, the text that I had typed was not there.

**Comment by btopro** [comment]
WP integration way better now
