### ISSUE TITLE
[feedback] some thoughts about managing LOTS of small content pieces

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/issues#220]
After my mis-adventures with the Outline today (and I should have known it was not going to work; a gazillion clicks is never a good sign, ha ha), I thought I would share a couple of ideas re: managing LOTS of small content pieces, which is the kind of project I am looking at, and is perhaps relevant to other academic and non-academic projects. 

I am publishing public domain stories with HAX; I'll be published probably a couple thousand of these public domain stories each year, or even more if we can figure out what's really possible. Basically, I can expand to fill infinite story space. :-)

When I think about how to manage that, I really think about photo albums and music playlists. Flickr is a great example; if I could organize my HAX story pages the way I organize images at Flickr, that would be fabulous.
**albums**: you put items into albums; you can also order the items in an album; the same item can go in multiple albums
**collections**: you can put albums into collections; this is useful when you have a ton of albums and need to organize them
**tags**: in addition to albums/collections, you can use tags that enable searching across albums and collections
I have 8000 images at Flickr right now, mostly illustrations for stories in the public domain, and they feel totally organized to me: almost all my images are in albums, and almost all my albums are in collections, and despite the large number of items, it is all very manageable.

The Outline approach right now in the HAX theme I am using (I don't know if that Outline approach is what I would find in other themes?) is not up to the task of managing hundreds, much less thousands of items. It's too hard to arrange a ton of content in outline form, and, more importantly, the outline form prevents me from using the same item in multiple albums (playlists, books, whatever you would call the content collection).

So, those are some quick thoughts.

I know that my LOTS-of-small-content-pieces approach may not be the most common type of project you expect to see, but I hope it is one that will fit into the HAX universe of projects. :-)

**Comment by btopro** [comment]
#334 some overlapping workflows here / UI things potentially as well as w/ the studio work currently being done

**Comment by btopro** [comment]
#1058
#1054 
#1059 
#1041

**Comment by btopro** [comment]
#1030

It's been years... but we now have a lot of the capabilities required to dig into smaller bigs of content and make meaning. Now, as we review this functionality for the next release, our team internally will keep working on polishing things and adding to the "Insights" dashboard.
