### ISSUE TITLE
[a11y-image-description] Make an image type w/ long description

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#221]
Based on discussion in episode 9:
https://cookiecrook.com/longdesc/details/
- source (property)
- slot forms the description
- simpleColors based
- "for" some kind of association like a tooltip
- positioning (internal, right after, collapse (default))

example usage:
```html
<img src="stuff.jpg" id="thing" />
<a11y-image-description for="thing">
  <table> ... </table>
</a11y-image-description>
```
```html
  <media-image source="whatever.jpg" />
  <image-description>
    <p>This is a paragraph of what you will be describing</p>
  </image-description>
```

**Comment by nikkimk** [comment]
Finalized in https://github.com/elmsln/lrnwebcomponents/pull/414
