### ISSUE TITLE
Print Button Error

### ISSUE THREAD

**Issue by cgldevel** [elmsln/issues#225]
Question: Does the print button work on your ELMS courses?  Ours is not.  So I was wondering if it’s something that needs fixed OR if it’s just that our instance of ELMS, needs updated. When I click any of the print options for our courses, I receive this error.

Worth noting, I've tried multiple courses in both Chrome / Firefox and received same error when printing.

![Screen Shot 2020-05-18 at 10 24 11 AM](https://user-images.githubusercontent.com/11019355/82225915-cf437180-98f3-11ea-8010-aacb56aa8388.png)

**Comment by btopro** [comment]
https://courses.aanda.psu.edu/music109/book/export/html/1303 works; can you turn on error reporting so we can see what it's complaining about? This is def a php side thing

**Comment by btopro** [comment]
closing unless can be reproduced / need more info
