### ISSUE TITLE
[elmsln] Drupal core security update to 7.70

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#227]

**Comment by btopro** [comment]
@rickhumphries I'll push these up to master and test them shortly. These appear to be very minor changes and we're on 7.69 in 1.x.x currently

**Comment by btopro** [comment]
threw it up on staging, looks fine. Really just adds 1 JS file and a very minor tweak to how link redirects are handled in its regex

**Comment by rickhumphries** [comment]
Nice one @btopro thanks
