### ISSUE TITLE
[testing] Implement cypress in our monorepo workflows

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#231]
https://www.cypress.io/ check this out and see which way we should go here

**Comment by RCS-167** [comment]
Initial exploration shows a promising testing tool. Installing and running is no problem at all, and comes with sample test code to run. Upon running the code, a browser is opened (options are Firefox and Electron which can run headless) and shows a split window. On the left side is each of the automated tests and on the right is the website/webcomponent being tested. Key things that set Cypress apart from Selenium is test running and debugging. In Selenium, if there is an error in your test script, the code will stop executing and instantly close the browser. This means that one has to find which line is failing and use a hard stop such as a break point in Visual Studio. Cypress however will continue to execute code lines and remain open at the end for test results review. I will continue to explore Cypress and attempt to create my own test scripts.

**Comment by btopro** [comment]
Thanks for the update. After some more exploration do a short video showing it in context of a web component driven test so the team can get ideas (or bring it to uncode Friday's).

**Comment by btopro** [comment]
related next step if Cypress is as good as it seems #230

**Comment by RCS-167** [comment]
This took me a while to figure out, but I'm finding ways to use Cypress to interact with custom elements. I have a simple webcomponent running locally using Open WC that has a button that increments the number on screen. My current script is able to find the button in the webcomponent and click it using some scripts that lets it search in the shadow dom. Currently trying to figure out how to write the assertion for the component. There are supposedly shadow dom plugins for Cypress that give you commands like cy.shadowFind, but I haven't tried those yet.

**Comment by btopro** [comment]
went with playwrite which is now working
