### ISSUE TITLE
creating local lrnwebcomponents repo

### ISSUE THREAD

**Issue by dtn9197** [elmsln/issues#240]
I followed the installation instructions for Windows. I did not use the cygwin command line. I ran all the command line instructions in Visual Studio. I am still getting error when i do yarn start. Any assistance would be appreciated. Thanks
![error](https://user-images.githubusercontent.com/55216005/83072601-0d037100-a03d-11ea-9458-2b50f1708348.png)

**Comment by dtn9197** [comment]
this is the error when i run yarn start on any particular web component
![error2](https://user-images.githubusercontent.com/55216005/83072817-6d92ae00-a03d-11ea-8f75-06700aa38677.png)

**Comment by btopro** [comment]
Did you do yarn install at the project root and then start in an individual element? Start at the top screws up the tooling. Also try doing it not in vscode. Power she'll I think can work but not possitive. @McGarvelcuddy might have ideas

**Comment by dtn9197** [comment]
i do **yarn install** at **/lrnwebcomponents.** 
 Then i would  **cd elements/ELEMENTNAME** and do **yarn start** to test individual elements. Let me know if this is right.

**Comment by btopro** [comment]
yeah that's the workflow. based on the error in the 1st one I think you need to run cygwin or try running cygwin to see if that helps. Windows hates a very minor aspect to our tooling which is beyond weird as it's just like making a folder and referencing it. Anyway, try cygwin and see if that helps

**Comment by dtn9197** [comment]
So i reinstalled the repository using PowerShells which i think kinda solved the first problem, which was the node_modules packages not being installed correctly. Now i'm encountering some kind of import issue with the modules whenever i do **yarn start** in the individual components.

![importerror](https://user-images.githubusercontent.com/55216005/83160485-44bdf780-a0d5-11ea-9fb0-8b88960f5401.png)

Do you think this is still a cygwin related problem.  Ideally i'd love to solve it without installing a new command line which will take more time to learn and set up. Some of the bandage solutions in the error message at the bottom such as renaming files or removing "type" = "module" in package.json aren't helpful either since they'll just cause further integration problems.

My node version is: v12.16.1. if that helps.

**Comment by btopro** [comment]
I'm on v10.18.1 currently on my ubuntu 19 machine. Mac is a bit easier to deal w/ this stuff too.

Try doing yarn install, then yarn run postinstall and see if that helps. It has to do with paths and finding their way back to the correct node_modules directory. @McGarvelcuddy fought this a lot and it's in better shape then it was (if you can believe). Cygwin operates more like a unix terminal so not a ton to learn there; biggest thing I believe is that it correctly navigates symlinks.

Give that last install / postinstall a try and then if that doesn't work Cygwin it is

**Comment by dtn9197** [comment]
@btopro that worked. Doing **yarn install** again inside any element's folder (**element/ELEMENTNAME**) after the first **yarn install** at **/lrnwebcomponents** solved the issue. At the same time i also switched to the cygwig terminal for the entire installation process. So i guess i can't say for sure if it worked because of the second **yarn install** or the cygwig terminal. My guess is the **yarn install** because it created a lot of stuff that was missing in the node modules.
