### ISSUE TITLE
simple-colors: choose a version

### ISSUE THREAD

**Issue by saracunn** [elmsln/issues#243]
When doing yarn install to add simple-colors it says: Please choose a version of "@rhelements/rh-sass" from this list

Requires me to choose a version twice

![Screen Shot 2020-05-28 at 12 11 27 PM](https://user-images.githubusercontent.com/59973201/83166130-71294200-a0dc-11ea-9003-6cd0c404c314.png)

**Comment by btopro** [comment]
last commit fixed this too
