### ISSUE TITLE
[merit-badge] badge as sticker in a book #5

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#246]
Remember sticker books where you find the stickers on 1 page and then find the outline in the book and apply it? this isn't terribly different from the idea of accomplishing a task in a course and then being "credited" for it. Right now those credit systems are invisible, things like Canvas tracking every page and how long your there :eyes: (yes...). What we'd like to do is create a system where students can see achievements in a course like so:
- When you read Unit 1 and complete the quizzes with a 70% or higher, you'll unlock the "Art of the Middle Ages" badge
- This badge says the skills / topics that were covered and boils it down to a visible merit badge

## code idea
```js
    ${this.heading.split('').map((letter, index) => html`<span class="char${index+1}">${letter}</span>`)}
```

If we have a visual system for this, we have a better chance of building user-buy-in across topics / courses. You get a sash / backpack to store your accomplishments in, could publish them to LinkedIn (some platforms do this sorta thing like Linda).

Requirements:
- [ ] A visual badge that is made to look like a merit badge in scouting
- [ ] CSS to make it a circle, raised, looks like a stitched border
- [ ] Use `SimpleColors` as base class for easier accent color inheritance
- [ ] CSS variables / parts for color of the stitching and sizing
- [ ] icon that's from the icon library OR an image (so support for 1 or the other based on which is there)
- [ ] Title for the label to apply to the badge
- [ ] date for the date that this badge was unlocked
- [ ] "eventName" an event to listen for from the system that will unlock the badge
- [ ] CSS that makes the text warp to the badge / scaled appropriately
- [ ] Link with icon that when clicked opens in a new window
- [ ] `skills` as an Array (shown as a bulleted list) 
- [ ] verification link - clicking button takes user to a URL that is who gave this badge / verifies this information
- [ ] absolute-position-behavior used to show details and skills as a pop over so that when you click on a button for detail or skills that it shows those in a pop over
- [ ] CSS / property for "locked" as in the badge has not yet been completed by the user
- [ ] Badges should be set side by side
- [ ] In your demo, make 5 badges that are locked. Add a button that when clicked, unlocks the badge by issuing the custom event it's looking for against it. When it's unlocked, the date should be set as the current date
- [ ] This is most likely a badge-sticker (visual of the badge stand alone), merit-badge which has the badge + click events for displaying more details in the absolute position behavior, as well as the lock / unlock on event logistics

## some helpers
While not seeming related, moar-sarcasm (https://dev.to/btopro/moar-sarcasm-plz-a-totaly-necessary-web-components-tutorial-3c51) needs to process text in a similar way for the fan out approach. It accepts every letter of a value and then wraps each in a span. A similar method could be used to produce what's laid out here (conceptually) https://css-tricks.com/set-text-on-a-circle/
Code that converts string into a series of spans next to each other: https://github.com/elmsln/lrnwebcomponents/blob/master/elements/moar-sarcasm/src/moar-sarcasm.js#L98-L112

## Absolute positioning / icon work

This one is a bit more in the weeds as far as element reuse so here's some helpers
```
npm install --save @lrnwebcomponents/absolute-position-behavior
npm install --save @lrnwebcomponents/simple-icon

import "@lrnwebcomponents/absolute-position-behavior/absolute-position-behavior.js";

firstUpdated(changedProperties) {
  if (super.firstUpdated) {
    super.firstUpdated(changedProperties);
  }
  this.activeNode = this.shadowRoot.querySelector("#badge");
}

skillClick(e) {
  this.skillsOpened = !this.skillsOpened;
}

<badge-sticker id="badge">

  <simple-icon-button
      icon="cancel"
      @click="${this.skillClick}"
    ></simple-icon-button>
</badge-sticker>

<absolute-position-behavior
            justify
            position="bottom"
            allow-overlap
            sticky
            auto
            .target="${this.activeNode}"
            ?hidden="${!this.skillsOpened}"
          >
    ${this.skills.map(item => html`<li>.....
</absolute-position-behavior>
```

![image](https://user-images.githubusercontent.com/329735/229592631-67950545-bd63-42c3-a304-058c9afdc3ea.png)

**Comment by btopro** [comment]
@cgldevel this made me think of your experience tiles that you worked on for that resume layout. Could be a good one to get added in longer term as we think of how to do this for educational purposes. Might also be a cool one to do as part of the fall class and have you kinda be like the PM / person to ask questions of while 2 different teams work on this from two different angles; 1 visually, 1 data layer transmission wise.

**Comment by btopro** [comment]
Image concept
![image](https://user-images.githubusercontent.com/329735/210815830-35cdee54-3d57-4261-aabd-f9abc3039bc2.png)

**Comment by btopro** [comment]
Image concept

![image](https://user-images.githubusercontent.com/329735/229592631-67950545-bd63-42c3-a304-058c9afdc3ea.png)

**Comment by JeffTaylor108** [comment]
I'll work on this issue

**Comment by zach-carson** [comment]
I'll take this one

**Comment by masonyurko** [comment]
I want this one

**Comment by msanyal7** [comment]
I would like this one

**Comment by epicman2-boop** [comment]
I would like to do this one.

**Comment by robborys** [comment]
I'd like to work on this one

**Comment by rakib-anam** [comment]
Claim

**Comment by danialamo** [comment]
I'll will do this one.

**Comment by ERos1012** [comment]
I will work on this one

**Comment by ishanitewari** [comment]
This looks interesting, I'll take it if it's open :)

**Comment by robborys** [comment]
width: 200px;
   height: 200px;
   background: red;
   border-radius: 50%
   padding: 20px;
   margin: 10px;
   background: #ff0030;
   color: #fff;
   font-size: 21px;
   font-weight: bold;
   line-height: 1.3em;
   border: 2px dashed #fff;
   border-radius: 50%;
   box-shadow: 0 0 0 4px #ff0030, 2px 1px 6px 4px rgba(10, 10, 0, 0.5);
   text-shadow: -1px -1px #aa3030;
   font-weight: normal;
   text-align: center;
   vertical-align: text-middle;


If someone wants the "stitched look" for their circle here's some CSS to help

**Comment by ERos1012** [comment]
Help for wrapping the text around the circle: https://codepen.io/ERos1012/pen/YzJpPVZ

**Make sure to ask chatGPT to make it work in Lit Elements**
