### ISSUE TITLE
[audio-player] Make an audio specific player

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#247]
`video-player` has a mode for accounting for mp3's. maybe we need to make a wrapper specific to audio as we've been running into confusion around video / audio mix ups in production as the video player can play mp3s. Example from in a course where there's no image and it makes things full screen in rendering:
![image](https://user-images.githubusercontent.com/329735/83266490-e5bdb880-a190-11ea-93a2-93dc3ed8b682.png)
example internally: https://courses.aanda.psu.edu/music109/node/1384

**Comment by nikkimk** [comment]
Works in HAX, not in ELMS:LN. See issue #263
