### ISSUE TITLE
Multiple Choice - Answer Options Not Saving

### ISSUE THREAD

**Issue by Deb-G** [elmsln/issues#250]
In a chrome browser, Version 83.0.4103.61 (Official Build) (64-bit).  

Editing this page: https://courses.aanda.psu.edu/id100/node/14

Attempted to add answer options to the last question on the page by doing the following:

1. Edit "HAX"
2. Clicked on the question I wanted to add answer options to, in this case, the last question out of four.
3. Clicked on "Configure" in the left hand navigation window
4. Note: Randomize is already selected - I leave that.
5. Clicked on "Add Item"
6. Checked on "Correct"
7. Clicked "+" to expand
8. Typed answer (in this particular question, the word color is in every answer, this time I left that out. 
9. Clicked "Add Item"
10. Repeated all of above, ending with a total of four answer options
11. Clicked on "Green Save Button" in the upper right hand navigation. 

The attached image is the result.
![Screen Shot 2020-06-01 at 4 40 35 PM](https://user-images.githubusercontent.com/12716869/83452488-c9d34480-a426-11ea-97f8-9e19eb808572.png)

**Comment by nikkimk** [comment]
My changes show up in the JSON and HTML hax's view source mode. What happens to the HTML and JSON when ELMS:LN saves?

**View  Source Results**
```<multiple-choice accent-color="grey" typeof="oer:Assessment" 
resource="#6dbca3ee-9d04-3aaf-d10d-e478486750a1" 
prefix="oer:http://oerschema.org/ schema:http://schema.org/ dc:http://purl.org/dc/terms/ foaf:http://xmlns.com/foaf/0.1/ cc:http://creativecommons.org/ns# bib:http://bib.schema.org " 
check-label="Check answer" reset-label="Reset" correct-text="Great job!" incorrect-
text="Better luck next time!" correct-icon="icons:thumb-up" 
incorrect-icon="icons:thumb-down" quiz-name="default" title="Testing Multiple  Choice" 
question="What do yellow and blue make?" 
randomize schema-resource-id="#6dbca3ee-9d04-3aaf-d10d-e478486750a1" 
answers="[{&quot;label&quot;:&quot;Purple&quot;},{&quot;userGuess&quot;:false,&quot;correct&quot;:true,&quot;label&quot;:&quot;Green&quot;}]">
</multiple-choice>```

```
[
  {
    "tag": "multiple-choice",
    "properties": {
      "accentColor": "grey",
      "dark": false,
      "colors": {
        "grey": [
          "#ffffff",
          "#eeeeee",
          "#dddddd",
          "#cccccc",
          "#bbbbbb",
          "#999999",
          "#666666",
          "#444444",
          "#333333",
          "#222222",
          "#111111",
          "#000000"
        ],
        "red": [
          "#ffdddd",
          "#ffaeae",
          "#ff8f8f",
          "#ff7474",
          "#fd5151",
          "#ff2222",
          "#ee0000",
          "#ac0000",
          "#850000",
          "#670000",
          "#520000",
          "#3f0000"
        ],
        "pink": [
          "#ffe6f1",
          "#ffa5cf",
          "#ff87c0",
          "#ff73b5",
          "#fd60aa",
          "#ff3996",
          "#da004e",
          "#b80042",
          "#980036",
          "#78002b",
          "#5a0020",
          "#440019"
        ],
        "purple": [
          "#fce6ff",
          "#f4affd",
          "#f394ff",
          "#f07cff",
          "#ed61ff",
          "#e200ff",
          "#a500ba",
          "#8a009b",
          "#6c0079",
          "#490052",
          "#33003a",
          "#200025"
        ],
        "deep-purple": [
          "#f3e4ff",
          "#ddacff",
          "#c97eff",
          "#bb63f9",
          "#b44aff",
          "#a931ff",
          "#7e00d8",
          "#5d009f",
          "#4c0081",
          "#3a0063",
          "#2a0049",
          "#1d0033"
        ],
        "indigo": [
          "#e5ddff",
          "#c3b2ff",
          "#af97ff",
          "#9e82ff",
          "#9373ff",
          "#835fff",
          "#3a00ff",
          "#2801b0",
          "#20008c",
          "#160063",
          "#100049",
          "#0a0030"
        ],
        "blue": [
          "#e2ecff",
          "#acc9ff",
          "#95baff",
          "#74a5ff",
          "#5892fd",
          "#4083ff",
          "#0059ff",
          "#0041bb",
          "#003494",
          "#002569",
          "#001947",
          "#001333"
        ],
        "light-blue": [
          "#ddefff",
          "#a1d1ff",
          "#92c9ff",
          "#65b3ff",
          "#58adff",
          "#41a1ff",
          "#007ffc",
          "#0066ca",
          "#0055a8",
          "#003f7d",
          "#002850",
          "#001b36"
        ],
        "cyan": [
          "#ddf8ff",
          "#9beaff",
          "#77e2ff",
          "#33d4ff",
          "#1ccfff",
          "#00c9ff",
          "#009dc7",
          "#007999",
          "#005970",
          "#003f50",
          "#002c38",
          "#001a20"
        ],
        "teal": [
          "#d9fff0",
          "#98ffd7",
          "#79ffcb",
          "#56ffbd",
          "#29ffac",
          "#00ff9c",
          "#009d75",
          "#007658",
          "#004e3a",
          "#003829",
          "#002a20",
          "#001b14"
        ],
        "green": [
          "#e1ffeb",
          "#acffc9",
          "#79ffa7",
          "#49ff88",
          "#24ff70",
          "#00f961",
          "#008c37",
          "#00762e",
          "#005a23",
          "#003d18",
          "#002a11",
          "#001d0c"
        ],
        "light-green": [
          "#ebffdb",
          "#c7ff9b",
          "#b1ff75",
          "#a1fd5a",
          "#8efd38",
          "#6fff00",
          "#429d00",
          "#357f00",
          "#296100",
          "#1b3f00",
          "#143000",
          "#0d2000"
        ],
        "lime": [
          "#f1ffd2",
          "#dfff9b",
          "#d4ff77",
          "#caff58",
          "#bdff2d",
          "#aeff00",
          "#649900",
          "#4d7600",
          "#3b5a00",
          "#293f00",
          "#223400",
          "#182400"
        ],
        "yellow": [
          "#ffffd5",
          "#ffffac",
          "#ffff90",
          "#ffff7c",
          "#ffff3a",
          "#f6f600",
          "#929100",
          "#787700",
          "#585700",
          "#454400",
          "#303000",
          "#242400"
        ],
        "amber": [
          "#fff2d4",
          "#ffdf92",
          "#ffd677",
          "#ffcf5e",
          "#ffc235",
          "#ffc500",
          "#b28900",
          "#876800",
          "#614b00",
          "#413200",
          "#302500",
          "#221a00"
        ],
        "orange": [
          "#ffebd7",
          "#ffca92",
          "#ffbd75",
          "#ffb05c",
          "#ff9e36",
          "#ff9625",
          "#e56a00",
          "#ae5100",
          "#833d00",
          "#612d00",
          "#3d1c00",
          "#2c1400"
        ],
        "deep-orange": [
          "#ffe7e0",
          "#ffb299",
          "#ffa588",
          "#ff8a64",
          "#ff7649",
          "#ff6c3c",
          "#f53100",
          "#b92500",
          "#8a1c00",
          "#561100",
          "#3a0c00",
          "#240700"
        ],
        "brown": [
          "#f0e2de",
          "#e5b8aa",
          "#c59485",
          "#b68373",
          "#ac7868",
          "#a47060",
          "#85574a",
          "#724539",
          "#5b3328",
          "#3b1e15",
          "#2c140e",
          "#200e09"
        ],
        "blue-grey": [
          "#e7eff1",
          "#b1c5ce",
          "#9badb6",
          "#8d9fa7",
          "#7a8f98",
          "#718892",
          "#56707c",
          "#40535b",
          "#2f3e45",
          "#1e282c",
          "#182023",
          "#0f1518"
        ]
      },
      "schemaResourceID": "#6dbca3ee-9d04-3aaf-d10d-e478486750a1",
      "schemaMap": {
        "prefix": {
          "oer": "http://oerschema.org/",
          "schema": "http://schema.org/",
          "dc": "http://purl.org/dc/terms/",
          "foaf": "http://xmlns.com/foaf/0.1/",
          "cc": "http://creativecommons.org/ns#",
          "bib": "http://bib.schema.org"
        }
      },
      "title": "Testing Multiple  Choice",
      "disabled": false,
      "singleOption": false,
      "checkLabel": "Check answer",
      "resetLabel": "Reset",
      "hideTitle": false,
      "question": "What do yellow and blue make?",
      "answers": [
        {
          "label": "Purple"
        },
        {
          "userGuess": false,
          "correct": true,
          "label": "Green"
        }
      ],
      "correctText": "Great job!",
      "incorrectText": "Better luck next time!",
      "correctIcon": "icons:thumb-up",
      "incorrectIcon": "icons:thumb-down",
      "quizName": "default",
      "randomize": true,
      "hideButtons": false,
      "typeof": "oer:Assessment",
      "resource": "#6dbca3ee-9d04-3aaf-d10d-e478486750a1",
      "prefix": "oer:http://oerschema.org/ schema:http://schema.org/ dc:http://purl.org/dc/terms/ foaf:http://xmlns.com/foaf/0.1/ cc:http://creativecommons.org/ns# bib:http://bib.schema.org ",
      "schemaResourceId": "#6dbca3ee-9d04-3aaf-d10d-e478486750a1"
    },
    "content": ""
  }
]
```

**Comment by nikkimk** [comment]
This is definitely an ELMS issue and not an issue with the multple-choice, simple-fields, or hax state management.  

HAX is posting the correct data `answers=\"[{&quot;userGuess&quot;:false,&quot;correct&quot;:true,&quot;label&quot;:&quot;Green&quot;}]\"` to ELMS but when ELMS sends data.json back, multiple choice has `answers="\`\`"`.

If I bypass HAX entirely and edit with the old editor, the same issue happens when the page reloads.
