### ISSUE TITLE
Git cloning haxcms

### ISSUE THREAD

**Issue by saracunn** [elmsln/issues#252]
when git cloning haxcms it did not run properly and nothing appeared. i tried exiting and creating a new terminal and still nothing. to fix the issue I had to restart my computer and then it worked.

**Comment by btopro** [comment]
You'll have to be more clear then this or try providing a PR for the directions that is more clear. Even things around DDEV saying `(requires reboot after install)` can be helpful to new contributors. Spell out the commands more directly and use trpple ` to indicate a block.

For example:
```bash
$ yarn install
$ cd elements/simple-colors
$ yarn start
# in a new terminal window
$ code .
```
