### ISSUE TITLE
[desktop] Start a new boilerplate electronJS app w/ 9.0 release

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#262]
https://www.electronjs.org/blog/electron-9-0 E 9.0 just came out; we are way out of date w/ version of this and so let's look for a new boilerplate; start a fresh branch and just blow everything we used to do away. This is very dated but let's keep in the same repo in the event we have conventions we want to move forward (minimal I'm sure) https://github.com/elmsln/hax-desktop-app so let's leave it alone.

All new work should take place in https://github.com/elmsln/HAXdesktop to match our naming convention for projects

#261 will help w/ collaborating on the tooling itself and the end points for things across projects desiring this
#215 will be achievable once we know what the structure for integration even looks like
@heyMP has built some interesting "hax11ty" commands which could probably have the 11ty parts abstracted a bit so that we have just like a `haxserve` command or some such thing

# Actions
- [x] make a boilerplate in https://github.com/elmsln/HAXdesktop
- [x] to start, try and get it to just correctly load a hello-world page
- [x] test a build flow w/ github for distribution as outlined here
  - https://www.electronforge.io/config/publishers
  - https://www.electronforge.io/config/publishers/github
- [x] test out https://github.com/ArekSredzki/electron-release-server which has a docker instance so testing should be quick. See if this is potentially a viable way of distributing / managing updates over the life cycle

**Comment by btopro** [comment]
@dtn9197 I accepted the PR. Nice to see electron boilerplate is cleaner than it was previously. Next up working through the build / packaging routine. We want to make this work nicely with Linux, Windows, and OSX based routines and come up with a workflow for easily building new ones. @RCS-167 might be aware of a way that we could leverage automation like Tavis or Github hooks in order to run a routine that automatically generates new compiles of the app for different platforms (but I'm not positive).

**Comment by dtn9197** [comment]
@btopro do you think webpack tool is important for this project. Electron-builder, which is a popular tool for packaging and building distribution, actually recommends the webpack boiler plate setup in the documentation. Ideally i'd like to install only things that i understand. If it's important i'll do quick research on it so i can integrate the necessary toolings.

**Comment by btopro** [comment]
our team is 100% against webpack in all scenarios except where we are forced to engage with it. Please do not use this. See if there's a way to do the building without that bc it'll only cause issues.
