### ISSUE TITLE
UX - (HAX) - Block placement w/o cursor designation

### ISSUE THREAD

**Issue by AndrewGearhart** [elmsln/issues#269]
If you immediately place a block on the page after creating a page for the first time (without clicking on the content area), the item is placed in a "nowhere" space that isn't displayed when the page is rendered. However, it is displayed on every new page during the edit mode.

**Comment by btopro** [comment]
would have to see a video or something visual in order to diagnose this. Steps to replicate that are more detailed may help as well; not seen what you are referencing.

**Comment by btopro** [comment]
Fixed this, difficult to describe what it is but work on #186 lead to untangling this as well.
