### ISSUE TITLE
[haxcms] URL upload button label and positioning 

### ISSUE THREAD

**Issue by dtn9197** [elmsln/issues#270]
![image](https://user-images.githubusercontent.com/55216005/84046312-ecf67a80-a977-11ea-80b8-fd1c06e03dd0.png)

The current menu for uploading a video is posting a URL then hitting the "Configure" Button. The "Configure" button is not related to the "Upload files" portion functionality. I think it would be more helpful if the button is moved up right under the URL link. This is a more logical grouping of things. Also maybe change the label from "Configure" to something like "post" or "upload" so the semantic is more related to the task.

**Comment by btopro** [comment]
resuming in #334
