### ISSUE TITLE
[haxcms] text placement in Video Player Settings

### ISSUE THREAD

**Issue by dtn9197** [elmsln/issues#271]
![image](https://user-images.githubusercontent.com/55216005/84046790-8aea4500-a978-11ea-87e6-5c16d27cc8eb.png)
In the Video player Settings tab, the text at the bottom of each section("Source" and "Closed Caption") mentions putting the url into the textbox even if the user chooses the option to upload assets locally. This could be misleading for new users because there would be no textbox if they choose the upload option. the "URL here label" should only be displayed when the upload url option is selected just like in the "Closed Caption" section in the picture.

**Comment by btopro** [comment]
resuming in #334
