### ISSUE TITLE
Make sure the following components are available in ELMS:LN and hax.psu.edu

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#281]
- a11y-figure
- lrn-vocab
- lrndesign-gallery
- lrndesign-timeline
- lrndesign-chart
- image compare-slider
- accent-card

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/87056703-00de0800-c1d4-11ea-8a4a-fb0c2f268fae.png)


elmsln has this in place too but won't be reflected in production until we update prod for the latest version
