### ISSUE TITLE
[hax11ty] add in default unbundled repo

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#288]
Adding this in we'll be able to manage the boilerplate more sustainably.

Make sure this includes the default dependencies to work with HAXcms / the learn two theme as that's what we're stamping out by default

**Comment by AndrewGearhart** [comment]
be sure to add the unbundled-webcomponents to the .eleventyignore

**Comment by AndrewGearhart** [comment]
Also include .surgeignore in the _site directory with the following:
```
!build/*
!build/es5-amd/node_modules
!build/es5-amd/node_modules/**
!build/es6-amd/node_modules
!build/es6-amd/node_modules/**
!build/es6/node_modules
!build/es6/node_modules/**
build/es6/node_modules/@polymer/.DS_Store
```

**Comment by btopro** [comment]
@heyMP this might be a good time to see if we can get the unbundled-webcomponents tooling / build flow piece to be part of wcfactory and then merge some of the current hax11ty tools into that. This way we could have a cleaner integration than is what I threw together in the deskop app (https://github.com/elmsln/HAXdesktop/tree/master/app/unbundled-webcomponents) and will throw in here when I get a chance based on what @AndrewGearhart rigged up this evening through some manual steps.

I also agree with you that we should be able to merge the build routine itself into the hax11ty serve command so that the watch is also doing a rebuild of assets. Maybe we could do this based on some kind of modifying like siteAssets.js or something where you can then add in custom assets and it'll compile them *correctly* unlike our fudged importmap concept from before :)

**Comment by btopro** [comment]
This is in place; @heyMP 's work will need to be integrated from here so this is a baby step toward WCFactory having several of these things included inside it. I think 2 templates for HAX11ty could be included directly in WCFactory as well to stamp out and get us going w/ new static sites :)
