### ISSUE TITLE
Issue adding code blocks

### ISSUE THREAD

**Issue by aliceworksmedia** [elmsln/issues#298]
Hello, I attempted to add a code block to a HAX site at
 https://iam.hax.psu.edu/ars301/sites/hax-ux-ui-teardown/webcomponents

There's a screenshot there of the text I used - it continues to render as an actual web component instead of code example.

**Comment by btopro** [comment]
code viewer tag should be able to do this from internal testing. Please reopen or provide a more detailed example if this is not working still.
