### ISSUE TITLE
As a user I want to be able to float content, images and any other content items Left and Right

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#3]
can't float items -- any alignment is in a div -- wheeeeee

Proposed Solution:
The ability to float content >_>

**Comment by btopro** [comment]
@onelittlebecca could you have Miran look for a specific example of something that they are trying to do so we can see what functionality isn't available to accomplish this. We had left/right float previously and dropped it bc of valid points about grids that @nikkimk had made from a design perspective, though I completely understand the desire to do so. I am assuming this is probably more of a "I want an image to the right of this text" sorta thing which we do need to make a way of supporting, its more a matter of how we approach that architecturally.

**Comment by onelittlebecca** [comment]
will do. you should see something from him shortly.

**Comment by junkant** [comment]
That is spot on.
"I want an image to the right of this text"
This was exactly what the users tried to do. It could also be a case that they are not used to using grids to aligns things and want to do it the way they are used to.

**Comment by btopro** [comment]
ok cool. Ya we'll have to think up a way of accomplishing that WITHOUT floating right OR, only allowing floating right in certain situations. For example, if a grid plate exists and there's a paragraph in the column, now the float right becomes available for things (something like that).

What we're desperately trying to avoid is the ability for people to make things that look like total garbage as a result of overly floating things and allowing it everywhere. If there are conditions by which certain things can opt into floating or self define their ability to float right (which is another possibility, default to all things positioning without it and then things that want floatRight saying it in their HAXSchema).

**Comment by btopro** [comment]
float right added back in for the time being; if we run into issues we can correct from there
