### ISSUE TITLE
Expand YouTube appstore to download caption files when a video is selected.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#300]
When using YouTube's appstore search content to select a video, the author should be able to get the captions as well as the video.

This will require using the YT API (https://developers.google.com/youtube/v3/docs/captions/list) to download the captions and then uploading them to HAX as a VTT. 

There is no way to get them as the video plays. (The have to be downloaded first, and we don't want to make download request every a user plays a video.)

**Comment by btopro** [comment]
Not possible, closing
