### ISSUE TITLE
[haxcms]Color issue with accent-color setting

### ISSUE THREAD

**Issue by dtn9197** [elmsln/issues#316]
After clicking "Edit Page", the accent-color theme will overshadow the entire viewport, making it difficult to edit content. Video here:
https://share.getcloudapp.com/d5uWDeKe

**Comment by btopro** [comment]
weird, appears related to some recent state management work associated w/ button disabling. Have fixed locally.

**Comment by btopro** [comment]
fix pushed out w/ new themes; thanks for the report!
