### ISSUE TITLE
Adding Youtube videos

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/issues#331]
Attempting to insert a youtube video and I get a mini version of the page instead? 

<img width="1647" alt="Screen Shot 2020-07-17 at 11 47 24 AM" src="https://user-images.githubusercontent.com/15616523/87805547-76c11f80-c823-11ea-807c-21fefdafc360.png">

**Comment by btopro** [comment]
Ya YouTube changed their API #327 was just identified yesterday. High priority to fix I'll be on this soon

**Comment by btopro** [comment]
fixed, which also fixes Vimeo too so that was a nice surprise :).

Probably will notice it Monday, if not may need to clear some caches
