### ISSUE TITLE
[haxcms] site settings panel doesn't load on subsequent loads

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#332]
After selecting my site, I can click the Edit Site settings button the first time and get the haxcms-site-dashboard and change my theme, but if I do it again, haxcms-site-dashboard doesn't load there. my sight  If I go back to my sites, and then click on my site, I can access it again, but the second time it has the issue again.

**Comment by btopro** [comment]
Given the complexity of what's changed in this panel I might just force the page to reload. If for example you change the theme from clean one to learn 2 theme there's a possibility that the css variable (becasue of some lingering `@apply` usage) will not be set appropriately, which then isn't reflected until the next page load.

Reloading the site on a successful save fixes this issue and the state management issue w/ css var's while being a simple solution :)
