### ISSUE TITLE
[hax] highlight and process selection across multiple elements

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/issues#333]
Adding new lines (like you would when you want to turn something into a bulleted list) creates a new paragraph for every line, and I can't highlight all the paragraphs to turn them into a bulleted list. So I ended up formatting my list and pasting the code into the source view. Visuals: 
Before - separate paragraphs for each line, can't highlight to make bulleted list 
<img width="1542" alt="Screen Shot 2020-07-17 at 12 02 04 PM" src="https://user-images.githubusercontent.com/15616523/87807212-fd76fc00-c825-11ea-98d5-a6ebf79b9e4c.png">
After I added my own html 
<img width="1502" alt="Screen Shot 2020-07-17 at 12 04 40 PM" src="https://user-images.githubusercontent.com/15616523/87807241-0536a080-c826-11ea-9bca-73e393259b63.png">

**Comment by btopro** [comment]
going to need some browser details and a link to see where this happens.Not run into this one.

**Comment by kat-wehr** [comment]
Chrome... it happens every time. Is there a way to add a break that doesn't start a new paragraph so I can highlight the whole thing and then make it a list?

**Comment by btopro** [comment]
I believe this is `shift` + `enter` but not positive. If you make 4 lines, then move the cursor to a line and hit delete, it'll suck the content back into the previous element. Doing this you can make line 1 a bullet list, then hit delete at the 1st character position in left two and it should turn it into 1 list.

**Comment by btopro** [comment]
@kat-wehr I'll need a video or gif or something demonstrating this as I haven't been able to replicate. Going to push up some new stuff though for testing in staging though so maybe it'll get fixed in that (doubt it but never know).

**Comment by kat-wehr** [comment]
shift+enter fixed it, was just awkward to not be able to highlight multiple lines and make them into bullets (a la MS Word style)

**Comment by btopro** [comment]
ahhh ok that makes more sense then. I updated the title to be more actionable. There is a semi-intentional selection methodology currently employed to NOT allow what you are describing. This is so that you don't select the whole document and accidentally delete everything. Once we get our history manager in place (undo / redo) then this becomes possible.

**Comment by btopro** [comment]
https://github.com/elmsln/issues/issues/384 related operations / issues

**Comment by btopro** [comment]
So going to close this because of enhancements coming in the next release which brings undo / redo w/ high accuracy. There's a lot of clean up in copy/paste as well which should also help so let's see w/ what comes out.
