### ISSUE TITLE
[haxcms] New "Upload Media" feature prototypes

### ISSUE THREAD

**Issue by dtn9197** [elmsln/issues#334]
#270 #271 .These are the current prototypes for the re-imagined uploading media process.
https://xd.adobe.com/view/27423cc7-adc5-4845-af37-02f2e6430508-7211/
https://xd.adobe.com/view/72310ed7-3d94-4ad3-bfd1-2687cd0b703c-2762/

**Comment by btopro** [comment]
@nikkimk saw your doodles today; some past work in this area too
