### ISSUE TITLE
[image-gallery] ux with HAX is confusing

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#342]
It's difficult to see on the screen because of how deep the options go. This could be solved by making the left panel size of the hax panel either something that the user can drag and expand / change sizes of OR by better spacing within the form itself

**Comment by nikkimk** [comment]
We need to look at treating slots like grid-plates. We should talk through this.

**Comment by btopro** [comment]
Sounds good, will accept contributions 🤪

**Comment by btopro** [comment]
Now w/ the supplying a grid-plate pattern, we can effectively supply any complex editing interface we want in context. This happens by wrapping the content, modyfing, and then removing the editor when done. See hax-store's definitions for editable-table for how to implement elsewhere :) :) :)

**Comment by btopro** [comment]
updated array capabilities should help this
