### ISSUE TITLE
[a11y] Try out axe /  axe-core/chai

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#356]
https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

**Comment by btopro** [comment]
https://open-wc.org/testing/testing-chai-a11y-axe.html with some examples

**Comment by btopro** [comment]
@nikkimk have you seen this before? looks like it could help w/ some baseline quality control on a11y

**Comment by cousquer** [comment]
I highly recommend Axe. 
I use it for the development of my[ webcomponent card](https://github.com/uPortal-contrib/CardWebComponents). 
It is one of the tools recommended by the W3C WAI. A thousand times more interesting than lighthouse.

**Comment by btopro** [comment]
@collinkleest check this out for a tooling improvement

**Comment by btopro** [comment]
in next release of wcf!
