### ISSUE TITLE
lightspeed + haxcms

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#357]
This thing flies. Some areas that could be automated further in setup for a docker image:
- [ ] Allow Override needs set to allow local overrides
- [ ] .htaccess needs to respect index.php, index.html "Index" discovery
- [ ] http needs redirected to https

**Comment by btopro** [comment]
@bradallenfisher mind taking a look at this some time? Might be nice to have an automatic lightspeed + haxcms installer / docker image. I believe all that's needed are the 3 things above but I'm not sure if you have more experience scripting these settings vs I know they have a UI for a lot of stuff

**Comment by bradallenfisher** [comment]
i can take a look at it.

**Comment by bradallenfisher** [comment]
do you have a docker build file you are working from?
is there a specific registry you are using?
is this simply set up on digital ocean and you want me to dockerify it?

**Comment by bradallenfisher** [comment]
looks like we can tac on a build file and ultimately just customize this:
https://hub.docker.com/r/litespeedtech/openlitespeed

**Comment by btopro** [comment]
I believe this is the one https://hub.docker.com/r/elmsln/haxcms
