### ISSUE TITLE
Image sizes lost after saving

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/issues#366]
https://courses.aanda.psu.edu/gd115/node/25

When editing I'm setting image sizes to how I want them to look but after I save it and look at the page, they show up in their original sizes anyway. (For now I ended up putting them in columns to keep them small)

Published View
![screencapture-courses-aanda-psu-edu-gd115-node-25-2020-08-07-14_06_56](https://user-images.githubusercontent.com/15616523/89675135-6c8cc100-d8b7-11ea-8dea-b6c133b03489.png)

Editing View
![screencapture-courses-aanda-psu-edu-gd115-node-25-hax-2020-08-07-14_07_37](https://user-images.githubusercontent.com/15616523/89675143-71517500-d8b7-11ea-8cb2-d7e73e70f4ce.png)

**Comment by btopro** [comment]
I see a 2 col grid now which appears to hold the size; was this the intention to resolve this? Still worth us fixing just clarifying.

**Comment by kat-wehr** [comment]
Yeah - I put the columns there so they would stay smaller.

**Comment by btopro** [comment]
Another thing to review when doing stuff like this is adding haxcms/ to the path between name of the course and the node part. It's possible hax is putting th image width in correctly yet the elmsln default theme is messing it up. Is this possibly a course we could roll the new theme with for students?

**Comment by kat-wehr** [comment]
Probably - no studio, just text, video and images.

**Comment by btopro** [comment]
fixed something similar
