### ISSUE TITLE
[site-menu] unpublished status shows for logged out users

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#368]
Regression from https://github.com/elmsln/lrnwebcomponents/pull/442
Steps to reproduce
- Load a theme with site-menu and an unpublished page, hidden icon visible (as it should be)
- Go to the site in an incognito tab, hidden icon still visible

![image](https://user-images.githubusercontent.com/329735/90440203-d28dfb00-e0a4-11ea-805d-1e08bb5ff607.png)

**Comment by heyMP** [comment]
This is the case only when the site is in `"publishedPageOn": false` That would need to be set to `"publishedPageOn": true`.  We could say "If `publishedPageOn` is set to `false` then we should not display the visibility icons to  logged out users.
