### ISSUE TITLE
Embedding twitter conversations

### ISSUE THREAD

**Issue by tomsshow** [elmsln/issues#370]
So when I try to paste the embed code I get from twitter, haxcms sanitize the code and it is not stylized as a twitter embed, it reverts to basic blockquote styling.

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/91230829-3a25f500-e6fa-11ea-9b43-9ea82572c69e.png)
progress

**Comment by btopro** [comment]
https://github.com/elmsln/lrnwebcomponents/tree/master/elements/twitter-embed

**Comment by btopro** [comment]
working https://dev.to/btopro/twitter-embed-in-litelement-and-vanillajs-olm . Doing a build to test in hax directly but appears to be working outside of an issue w/ twitter itself.
