### ISSUE TITLE
[github-preview] make a github preview element

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#388]
Simple; queries the github open API like https://api.github.com/repos/elmsln/haxcms

presents this information in a card / clickable format such as:
![github details](https://user-images.githubusercontent.com/329735/93517524-9515cb00-f8f9-11ea-867d-347b07c3a666.png)

This would obviously be designed better than this but using the API we could make a nice lightdom driven element that ajax loads the data on the front end (they have the right cors settings it appears) so that we give people a richer experience w/ a github repo. HAX integration would be PERFECT for the paste on an empty line and then insert the github preview tag or whatever name we come up with. Might be odd to have a dedicated github tag vs some tag that can help the presentation of previews of websites more wholistically, w/ github detection in it (or a code-repo-preview, something so that semantically we aren't wed to github even tho all of us are ;) ).

It should also interface with gitlab, bitbucket or at least have some flexibility in order to make that possible.

**Comment by btopro** [comment]
https://dev.to/btopro/will-critique-for-code-50m

**Comment by MichaelCurrin** [comment]
It seems like a ton of possible ideas and directions in here. Can I suggest narrow the scope to make it easier to decide and get out the initial version?

Like leave gitlab and bitbucket out - I don't know if they have APIs but perhaps the API call can change and the widget appearance stays the same.

And focus on a simple Github card. I have made them before. See preview. 

https://github.com/MichaelCurrin/my-github-projects/blob/master/README.md#my-github-projects

Display the repo author and name, the description paragraph and maybe star or for count or last updated.
The description field is also bite sized and widely used and so ideal for a preview.
If you start to preview the README for example that will take up more space and be more effort and maybe can some later. It would take a second API call to get the contents of that file.

**Comment by MichaelCurrin** [comment]
Regarding previewing any given website - that could be done using iframe maybe? But you might have Cors issues and browser compatibility issues etc. This can take research.
And you have to make sure the external website fits in the widget nicely. That could be hard to define and then apply esp if the target site is not responsive.

I think a widget that is focused on doing a github preview well (using the API) is going to be more useful than a generic widget that can also do github. Maybe you can have a suggestion though that if a github URL is detected in the web preview widget then you say why not use the github preview widget?

**Comment by MichaelCurrin** [comment]
I can here from dev.to BTW and wanted to give some ideas.

Also the GH REST API needs no auth token so you can easily request that data. But you will eventually hit rate limits if you reload the page enough times in a short time.

**Comment by btopro** [comment]
Great kick start thank you. I don't disagree with anything said here. Goal would be initially to just make a github card (name pending). The abstractions were more "oh we could make x which is a less specific form of y" sorta thing. Hopefully someone takes us up on working on this and then this adds more flavor to the requirements and food for thought :)

**Comment by MichaelCurrin** [comment]
After this discussion, I've seen something like the initial image with the text from the README and fading out. I don't remember where.

Anyway I wanted to share that there is an easy way to make a more minimal card that can be dropped into markdown or HTML anywhere.

```html
<a href="https://github.com/MartinHeinz/python-project-blueprint">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=MartinHeinz&repo=python-project-blueprint&title_color=ffffff&text_color=c9cacc&icon_color=2bbc8a&bg_color=1d1f21" />
</a>
```

<a href="https://github.com/MartinHeinz/python-project-blueprint">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=MartinHeinz&repo=python-project-blueprint&title_color=ffffff&text_color=c9cacc&icon_color=2bbc8a&bg_color=1d1f21" />
</a>

I that found on a profile README - https://github.com/MartinHeinz

**Comment by btopro** [comment]
exists, published, getting another PR soon to enhance it more but this is a thing as far as I'm concerned. Great work @collinkleest
