### ISSUE TITLE
Rich-text-editor cross-browser issues

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#39]
- Keyboard shortcuts (except for link) don't work in Edge
- In Firefox and Safari, they fire but continue to bubble.
- In Firefox, selection is cut when any toolbar button is used.
- In Edge, Firefox, and Safari, pasting is doubled.
- In Edge, Firefox, and Safari, cut does not save to the clipboard.

**Comment by btopro** [comment]
closing out. we fixed a lot of these and codebase is completely different / evergreens are WAY ahead of 2019 when this was opened
