### ISSUE TITLE
[HAX]  HAX printing colors property to the element

### ISSUE THREAD

**Issue by heyMP** [elmsln/issues#394]
In the HAX editor, when saving an element that extends simple colors, all of the color options are printed to the DOM on the "colors" attribute of the web component.

![Screen Shot 2020-09-23 at 1 28 42 PM](https://user-images.githubusercontent.com/3428964/94058657-51b2d500-fdaf-11ea-99af-9820598b6cb9.png)

**Comment by btopro** [comment]
Yeah this is an annoying aspect of inheriting things currently (and maybe an area for API enhancement in HAX for sure). Here's how we solve it in other elements
https://github.com/elmsln/lrnwebcomponents/blob/master/elements/video-player/video-player.js#L376-L378

```json
      saveOptions: {
        unsetAttributes: ["__utils", "__stand-alone", "colors"],
      },
```

This can be used to remove attributes / properties that may have come across. ANYTHING using SimpleColors as a base class / or wrapped in should remove stuff like this. Dono if maybe there's a decorator we can add to the element's properties definition or something to optimize how we handle these. Right now we do unset colors everywhere. Maybe the SimpleColors base class could implement one of the hooks in HAX to clean up the element prior to passing along (though could impact other things already using it).

here's the hooks:
```
 * Specialized functions
 * `preProcessHaxNodeToContent`
 *  - If you define this function on your element
 * then it will run BEFORE the conversion to text. This can be used to do
 * specialized processing that may not be standard prior to conversion to content.
 *
 * `postProcesshaxNodeToContent`
 *  - If you define this function on your element
 * then it will run AFTER the node has been converted to Content and allows you
 * to act upon the content even further. This could be to clean up / regex against
 * the text certain patterns or to look for certain elements at the end of
 * the conversion routine.
 *
 * `preProcessHaxInsertContent`
 *  - If an element needs to ensure it cleans up data
 * during the conversion from preview to being inserted. This function passes in
 * the details object for creating an element from HAX schema. Examples could be
 * objects that contain focus which may cause issues when doing a pure clone as the
 * reference is being garbage collected on save (see grid-plate).
```

**Comment by btopro** [comment]
went through and added
```js
saveOptions: {
        unsetAttributes: ["colors"],
      },
```
to all our elements that currently use `SimpleColors` but didn't already have this in place
