### ISSUE TITLE
[WCFactory] Gulp file errors on new elements

### ISSUE THREAD

**Issue by heyMP** [elmsln/issues#395]
@wcfactory/cli/0.8.7 darwin-x64 node-v12.18.3

After creating a new element with `wcf element`.  I cd into the newly created element and run `yarn start` I get a gulp error saying that it cannot find the `dev` task.

![Screen Shot 2020-09-30 at 11 20 16 AM](https://user-images.githubusercontent.com/3428964/94710934-6fcf8680-0315-11eb-8c49-d3d77a8afdc9.png)

![Screen Shot 2020-09-30 at 12 06 44 PM](https://user-images.githubusercontent.com/3428964/94710950-73fba400-0315-11eb-9776-42b688d3d534.png)

**Comment by btopro** [comment]
https://github.com/elmsln/lrnwebcomponents/blob/master/elements/air-horn/package.json#L30-L38

**Comment by btopro** [comment]
looks like you need updated templates locally. It's not references the .cjs in new things but this example you provided is not

**Comment by heyMP** [comment]
Is there a way to update the templates from the wcf command?  If not we can probably add that as a command.

**Comment by btopro** [comment]
#18 :) nope, known issue / thing we've had a need for. Just doesn't bite us too often
