### ISSUE TITLE
[lrnwebcomponents] linter wraps dynamic imports breaking @web/dev-server

### ISSUE THREAD

**Issue by heyMP** [elmsln/issues#420]
I just ran into an issue with dynamic imports and @web/dev-server .  Our js linter breaks long import statements into multiple lines:

```
    import(
      "@lrnwebcomponents/code-editor/lib/monaco-element/monaco-element.js"
    );
```
dev-server doesn’t recognize it as a dynamic import.

converting to this fixes the issue.
```
    import("@lrnwebcomponents/code-editor/lib/monaco-element/monaco-element.js");
```

**Comment by btopro** [comment]
Shakes fist in the air at @ChristianMurphy and his well intentioned linting routines!

Makes sense, was wondering what was making them break up on the line like that.

**Comment by ChristianMurphy** [comment]
```js
// prettier-ignore
import("@lrnwebcomponents/code-editor/lib/monaco-element/monaco-element.js");
```
is a quick work around.

This sounds like an upstream bug though.
new line or not, the import works the same in reality.

**Comment by btopro** [comment]
It does but our rewrite engine for local development in open-wc won't recognize it bc of the new line since I guess it's preg match isn't correct (upstream like you mention)

**Comment by ChristianMurphy** [comment]
I think the issue may be coming from https://github.com/modernweb-dev/web/blob/27e7ca62a6d3b59e91e9e1869e940b34089ce346/packages/dev-server-core/src/plugins/transformModuleImportsPlugin.ts#L146-L174
This is why people should leverage an [Abstract Syntax Tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree) instead of writing a custom parser :sweat_smile:

**Comment by ChristianMurphy** [comment]
Opened modernweb-dev/web#759 upstream with an example of the issue

**Comment by ChristianMurphy** [comment]
A full fix is incoming at https://github.com/modernweb-dev/web/pull/951

**Comment by ChristianMurphy** [comment]
Fix has been released https://github.com/modernweb-dev/web/releases/tag/%40web%2Fdev-server%400.0.23

**Comment by btopro** [comment]
is there a dependency we can fix to pick this up or is it downstream elsewhere?

**Comment by ChristianMurphy** [comment]
That is a great question, searching https://github.com/elmsln/lrnwebcomponents's `yarn.lock` file locally, I don't see `@web/dev-server` being used anywhere.
@heyMP how are/were you using `@web/dev-server`?

**Comment by heyMP** [comment]
`@web/dev-server` is the successor to `es-dev-server`.  I think we can upgrade to `@web/dev-server` with no issues.
