### ISSUE TITLE
Adding new custom content tag

### ISSUE THREAD

**Issue by 99bits** [elmsln/issues#422]
How to add new custom tags to the Haxcms content.  For example, adding a unity3d game as a custom component tag so that users can add the game to the page.

**Comment by btopro** [comment]
`_config/config.json` has a JSON blob in it called `appStore` The name of the HAX spec for communicating it's requirements is called appstore. In there there's a property called "autoloader" (Screenshot below). This provides a list of the of `"tag-name": "location/of/the/file/js"`. If you create your own web component you can supply your own location of the file. @heyMP might have experience making custom components for a specific site but not positive.

![JSON blob for HAXcms config.json](https://user-images.githubusercontent.com/329735/97480525-ec13b480-1929-11eb-990e-782df8b272a8.png)

My recommendation to you would be to customize this list to your needs (removing what you dont want that we default to), make a new tag, learn the haxProperties schema (https://haxtheweb.org/documentation-1/hax-development/hax-schema) or just look at other elements we've made for what their schema definition is, and then import said tag. The autoloader list is things that are automatically loaded sot hat they can be added via the HAX Add menu. You can also add web components manually if needed but via HAX is the prefered method.

**Comment by btopro** [comment]
closing as answered; please open other issues if you have additional questions
