### ISSUE TITLE
[grid-plate] Replace responsive-utility / responsive-behaviors with pure CSS solution

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#429]
See [The Raven Technique: One Step Closer to Container Queries | CSS-Tricks](https://css-tricks.com/the-raven-technique-one-step-closer-to-container-queries/) and [CSS Holy Albatross](https://heydonworks.com/article/the-flexbox-holy-albatross/).

In order to do this, I will need to:
- determine if this technique should be a standalone behaviors superclass
- compare the api of responsive-behaviors
- review/migrate the components currently using responsive-behaviors

**Comment by btopro** [comment]
closing #424 as you'll review this at some point and redo how it's implemented. I think we can have reasonable progressive enhancement from vanillaJS + light dom just hitting selectors like `grid-plate *[slot="col-1"]` type of global css. This could help w/ TTFP / flicker of unstyles content problems

**Comment by btopro** [comment]
now part of https://github.com/elmsln/issues/issues/763
