### ISSUE TITLE
[haxcms] Optional started pages.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#431]
A good way to onboard folks that are new to HAX CMS would be to have boilerplate pages. If they pick a course theme, you can choose to create it with sample lesson, learning objectives, lesson, and summary pages. If it's a portfolio theme, it might have certain portfolio pages. This would let them get used to editing pages before they have to learn to create pages.

**Comment by btopro** [comment]
completely agree; I believe this has been discussed previously in boilerplate threads. We currently just duplicate a boilerplate directory so at minimum we can make the starting point be like 3 pages of what's possible w/ well presented content. make a boilerplate on hax.psu or send me HTML and I can set it up.

We currently don't have support for the boilerplate per theme sorta concept though it's a great idea; just requires more planning / API work.

**Comment by btopro** [comment]
https://github.com/elmsln/HAXcms/issues/436
https://github.com/elmsln/HAXcms/issues/507
