### ISSUE TITLE
[meta] Formalize working group on the direction of ELMS:LN projects

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#440]
Suggested during conversations with @rickhumphries, a founding adopter of the elmsln NGDLE approach, we should have a formalized working group that meets monthly (or at whatever interval) in order to set direction, vision and needs for the projects under the ELMS:LN umbrella.

As HAX / web components are a core piece of elmsln and have been the moonshot to ultimately pull its UX forward, as we approach feature standardization within HAX and our portfolio of web components, we should be more strategic and open in the direction that this pushes forward.

Additional things to consider as we form this group:
- We are building tools that ultimately will build an LMS. This methodology needs better communicated as to how things all inter-relate, maybe we need to focus on visualizations and examples as this comes together. For example: @nikkimk makes a table that can be edited. This slots into HAX to make tables more accessible but is a natural gradebook editing interface. This then slots into the studio. The studio has discussion forums. The forums can be pealed off without studio and used stand alone, the gradebook pealed off and as a traditional LMS gradebook, the studio can be embedded in HAXcms, HAXcms can leverage elmsln as a headless backend. This sort of cascading, interrelated relationship of all things is complicated to grasp and we may need a priority list that is made of lots of microtasks that are tagged as to what they influence as opposed to a linear list.
- Is this group only code contributing / founding members of the project?
- Do we have a process for knowing when things that would grow the community should modify priority? For example, detouring into Moodle development to help on-board the team currently working to bring HAX into Moodle. How do we quantify this and correctly community that Moodle development directly benefits the platform goals / community?
- Is there a level of community contribution required in order to influence this roadmap more directly? Is that a %, or hourly thing, or do we have a mindset of "if that's your scratch and you itch it enough, and we agree its good enough, it becomes the priority to integrate it" (ala Drupal pre 2015).

**Comment by rickhumphries** [comment]
Thanks for kicking this off @btopro. I'm happy to set something up in the new year for those who are interested in being a part of the group. I think the group initially should draw from current developers, tutors, instructors of ELMS:LN who are actively using it to deliver courses to learners. I think that will serve us better initially as we look to agree to a meeting format / agenda and can have frank discussions on the pros/cons of using ELMS:LN currently which I think will only strengthen us as we go forward. These are some of my thoughts currently on some topics we can discuss:

- Understanding of the new direction ELMS:LN is taking with the focus on HAX development and the move to de-couple from Drupal. What challenges does this pose and how can we ensure a smooth transition.
- NGDLE - microservices and 'containers-as-a-service' are two ideas being discussed as ways of keeping the NGDLE approach without Drupal. How might this work in practice? Would this include integration with external tools too? Are there any industry standards we should be adopting across these tools? How do we keep learners roles / relationships /groups seamless across the different services? 
- The Scope of ELMS:LN - what outcomes should we focus on that we believe will really drive ELMS:LN and adoption in general forward? Should the focus just be on the course delivery and integrations / APIs and ELMS:LN is essentially acting as a plugin for other LMSs? Or is ELMS:LN the 'front door' as it were that is in control of the 'learning pathway' (grading / achievements / unit sign offs etc.)
- Feature development. We can show and tell any interesting concepts being worked on within our groups and discuss integration into core

Any more thoughts welcome :)

**Comment by btopro** [comment]
Wed: 9am - 10am EST; going to start out weekly with 2 representatives from Penn State and 2 from Buttercups. Will change and expand from here as time goes. First objective is to hash out painpoints and get all groups onto the same version of elmsln

**Comment by rickhumphries** [comment]
@btopro I thought it might be a good idea to create a space where we can add informal meeting minutes just so we have a record of the sorts of things we want to discuss. Can also be used to throw out ideas ahead of the meeting for a rough agenda? Was thinking either a new channel in Slack or trying out Github forums?

**Comment by btopro** [comment]
That's a good idea @rickhumphries . Maybe if

**Comment by btopro** [comment]
That's a good idea @rickhumphries ; I didn't realize there was a forums thing in github so I just enabled it: https://github.com/elmsln/issues/discussions

Would you like to run point on keeping the agenda / getting this kicked off so we're on task? I could see a Forum post about what the proposed topic of discussion is + something about joining the slack channel for details on getting into the meeting. The first several lets try to keep the scope tied directly to this whole "getting on the same page" swing we're in to keep momentum going.
