### ISSUE TITLE
[hax] button for rich-text-editor

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#446]
this would just wrap the thing being editing. Can be added to the "text" based context menu and this is a great reason to still have that separate.

**Comment by btopro** [comment]
@nikkimk Code is in place for this to work. It would add a new button to the hax text context menu which would allow for injecting a "full" text editor; aka rich-text-editor. I have also primed rich-text-editor for HAX so it knows how to respond but the following problem seems to be internal to rich-text-editor:
- I make a tag in hax
- I click to inject the rich-text-editor in HAX which calls a "wrap" function, effectively taking the active paragraph and wrapping it in a rich-text-editor.
- when `<rich-text-editor><p>the active contnet</p></rich-text-editor>` is placed in hax, it immediately gobbles itself and injects the rich-text-editor toolbar.

Possible solution:
- have rich-text-editor use rich-text-editor-toolbar's internal to its shadowRoot (which is how HAX manages its UI elements) while maintaining the original content editable item in light dom.
- this way its positioned accurately but also doesn't cause issues w/ elements that injects additional wrapper elements into hax (an anti-pattern for sure).

Hopefully this isn't too difficult; I'd prototype it but I know you've been working on stuff w/ rich-text recently so I don't want to touch it.

**Comment by nikkimk** [comment]
hax-text-editor-toolbar now inherits rich-text-editor behaviors but without a <rich-text-editor> wrapper.
