### ISSUE TITLE
[drupal] Support / account for Bootstrap theme in HAX

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#449]
This will take some A/B testing and exploration to figure out what needs worked on as described in the issue here on d.o. -- https://www.drupal.org/project/hax/issues/3191444

Looks like from the reported screen shots that there's some CSS we need to inject into the editing view to ensure it looks like it does on the "view" / normal page load. That or accounting for bootstrap in the displayed page via some kind of hax to bootstrap normalization shim css (or js but hopefully not).

**Comment by btopro** [comment]
Drupal issues seems minor now w/ the lastest update to HAX / the portfolio but leaving this open as we'll have someone working on related bootstrap issues

**Comment by WardinT** [comment]
Copied from my issue on drupal.org (https://www.drupal.org/project/hax/issues/3191444#comment-13959108):

In my ideal world, the overall configurability would consist of

Header and Footer Region content
Color Schema
Modifiers like rounded corners, shadows
defined in the theme settings and the standard components applied to the content region accordingly.

The idea is "borrowed" from Uikit theme and DXPR theme and builder (fka Glazed theme and builder)

**Comment by btopro** [comment]
#212 #620
