### ISSUE TITLE
[haxcms] course elements and theme inspiration

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#450]
https://www.e-education.psu.edu/geog438w/node/371 - look through design and in-page assets and create web components to draw inspiration from the functionality.

**Comment by btopro** [comment]
#449 #212 definitely related as this is a bootstrap theme in the 2nd example

**Comment by NovasKnowledge** [comment]
working on it

**Comment by btopro** [comment]
Sounds good. Give it a shot in open-wc.org tooling after identifying able name of an element and properties to give it

**Comment by NovasKnowledge** [comment]
So I decided to take a look at the interactive image on the site (Syllabus, Assignments and grading chart). When inspecting it, it looks like it is made using different classes and not a custom web component.  Now on hax, the closest thing to a interactive image is the styled image, which uses 2 custom web components (I think).  Should I try and create a third web component using the different classes from the site and combine it with the hax components?  Or is there an easier way to do this?

**Comment by btopro** [comment]
Good questions. So the classes are specific to their implementation. We want to make something exactly like it, but encapsulated as a webcomponent. That means something like basic-image or some such name for our element. Think about th properties that new element would have like source ,title ,caption, etc. Then make a new component and leverage their css and html structure for the starting point. Think about how simplified the class names can become if locally scoped (meaning writing in a |static get styles` method and not requiring or being able to communicate with global scoped css).

Use theirs as a starting point and then say how could our component eliminate the need for all their custom html and css (currently written by hand or copy paste). From there be thinking of what a hax editing experience would feel like for this element

**Comment by NovasKnowledge** [comment]
https://github.com/NovasKnowledge/test-450

**Comment by NovasKnowledge** [comment]
For those working on this issue next, here is my repo where I have been working on the issue.

https://github.com/NovasKnowledge/image
