### ISSUE TITLE
[video-player] Interactive transcript issue after going full screen

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#488]
I noticed on our ELMS:LN instance that we've currently upgraded for testing that going full screen and then back again makes the interactive transcript disappear and then the settings get messed up a bit:

![image](https://user-images.githubusercontent.com/4973810/105198668-ce737700-5b35-11eb-9147-468c3a9e6143.png)

Have you come across this before?

**Comment by btopro** [comment]
@nikkimk I am able to replicate weird behavior in this area; guessing a state management thing in a property for what the current mode is - https://courses.aanda.psu.edu/music109/node/1303 as an example on our end.

**Comment by btopro** [comment]
fixed in latest
