### ISSUE TITLE
[a11y-collapse] @media query for print so it expands to show all contents

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#510]
@nikkimk do we have a media query for print mode of an a11y collapse to ensure that we can view the content in the printed output

**Comment by btopro** [comment]
@collinkleest here's a good one to learn a CSS concept. We have a tag called `a11y-collapse` that has a title and the content in it. When the user hits print, a specific `@media print` can be leveraged (https://joshuawinn.com/css-print-media-query/)

Apply it to this element so that if someone prints the page that all collapse elements display their content. A quick google suggests that if we need to do a forced state change (it'll render the JS before printing) that `window.matchMedia("print")` could be used to KNOW what the current state is. I have never tried this but see if you can make the element FORCE the state to open if we are in a matchMedia of print

**Comment by btopro** [comment]
https://github.com/elmsln/lrnwebcomponents/blob/master/elements/a11y-gif-player/src/a11y-gif-player.js#L272-L294 -- example I just added to a11y-gif-player to see if this is possible (and it is!)

**Comment by collinkleest** [comment]
@btopro 
[Demo demo_index.html.pdf](https://github.com/elmsln/issues/files/5985662/Demo.demo_index.html.pdf)
is this the desired behavior? looks like the collapsable elements are already opening when print is toggled
we can go over this tomorrow

**Comment by btopro** [comment]
@rickhumphries can you reproduce the issue in question? I believe you reported that these don't print open in a certain context. Maybe she fixed this to make me look cray

**Comment by rickhumphries** [comment]
@btopro I think it just came up while we were talking about retaining styling for print and you went to demo this and it didn't work. Not 100% sure but weren't we in the storybook library (https://webcomponents.psu.edu/styleguide/?path=/story/navigation-collapse--a-11-y-collapse-group-story) and trying to print from there. I've just had a go at printing the page whilst some of the accordions were closed and it didn't open them in the print version for me. Example attached

[Navigation _ Collapse - A 11 Y Collapse Group Story ⋅ Storybook.pdf](https://github.com/elmsln/issues/files/5992202/Navigation._.Collapse.-.A.11.Y.Collapse.Group.Story.Storybook.pdf)

**Comment by btopro** [comment]
oh ok, if it's just on storybook I'm going to close it out. It is working in prod / test settings other then storybook so shouldn't be a big deal. Also possible that storybook is just out of date bc it is built independently of the CDN stuff
