### ISSUE TITLE
Renaming a page in site outline breaks navigation.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#517]
In this Lesson, https://iam.hax.psu.edu/lnm105/sites/acctg211/01_lesson, when pages 2 (Business Stakeholders) and 5 (Four Types of Business Organizations) were renamed, their paths change to https://iam.hax.psu.edu/lnm105/sites/acctg211/blank. Now Both 2 and 5 go to the same page in navigation.

**Comment by btopro** [comment]
This is due to an initial issue on the import. I've fixed the importer for future builds but this one I am fixing manually as we speak.
