### ISSUE TITLE
[meta] Considerations on theming

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#529]
We've been having discussions in the ELMS:LN working group around theming and how you might have one component that can alter it's design based on the 'theme' being applied to it.

I came across the shoelace web component library which has a similar concept and so I wanted to raise it here as a reference point to review the conventions they use as it could be useful. 

@nikkimk I've been told you may be interested in this

**References**
https://shoelace.style/getting-started/themes
https://shoelace.style/components/theme

**Comment by btopro** [comment]
#504 I believe last working group we discussed the notion of revisiting this down the road after getting onto the latest version of ELMS:LN / cutting a new release when BC adopts in production. This will create a foundation by which we can then start having discussions like this to say "ok, now that we have buttons, and they are intentionally designed... should we not adopt the ____ button".

**Comment by btopro** [comment]
@cmd30 has been working on a style guide bit by bit, reverse engineering some elements we have across Eberly and A&A but also envisioning how we *should* be designing things for consistency across the portfolio. Going to close this out for now but opening another issue now
