### ISSUE TITLE
Tab order

### ISSUE THREAD

**Issue by JAlbert2** [elmsln/issues#537]
Probably not the most important issue, more of a design choice. Tabbing through a page tabs through all the submenu items in the sidebar before moving between menus, even when the drop down is not active. Having the sub-menus render when the main is not active becomes an issue for readers as every menu then seems like a main menu. It also takes longer to tab through a menu tree if a person has to search through all of the menus. I think it would be beneficial to not render, or at least exclude the unopened menu tags from the tab order, for a11y concerns.

**Comment by btopro** [comment]
@JAlbert2 I'm not entirely following. Are you saying that it's possible to tab into sub-menus without that sub-menu being visually expanded? If so that is less a big deal for non-sighted users but is a big issue for sighted users (a rare issue there)

**Comment by JAlbert2** [comment]
You are correct

**Comment by btopro** [comment]
PR fixed this :)
