### ISSUE TITLE
[color-picker] rename this

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#540]
this should be more like `hex-picker` and `hex-code`. hex-code is the square, hex-picker or `hex-input` is the thing showing the change to the color in real time.

Bulk rename from color-picker to this. we have a simple-colorpicker element that's for picking in a specific set of colors; what you are making is more of a color swatch visualizer w/ some additional selection components.

**Comment by collinkleest** [comment]
Got it, I will change it
