### ISSUE TITLE
[hax] Server timing out after working on certain webcomponents

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#545]
We're seeing an issue which is timing out the server when working with certain webcomponents in HAX editor on ELMSLN.

We're seeing it on elements where the `icon` is a textfield, when typing in an icon like "view-day" for example, when it comes to save the browser either egg times out for a few minutes and eventually saves or just times out for a good ten mins or so without saving.

I'm not sure what the issue is but I tested just pasting in an icon's name (instead of typing it out) and it saves fine. I wasn't sure if HAX/ELMSLN was stalling during searching for SVGs which don't exist as you're typing? So, it's looking for `v.svg`, `vi.svg`, `vie.svg`, `view.svg`, `view-s.svg` as you're typing and that might be causing an issue? Not certain though.

I know you mentioned you've allowed icon inputs as a textfield in some components, have you come across this before?

**Comment by btopro** [comment]
I have not however it will continue to rewrite the path in real time to an SVG path as you type. The issue I am assuming is that because there's no debounce, it's every character, which then writes into an img tag and that then hits a file path which when failing, Drupal kicks in and tries to serve a 404. This would cause.... havoc potentially if these paths were able to activate in that way. Can you inspect the XHR traffic to see if the response for these misses on icon svgs is tripping drupal to return a 404?

**Comment by JackWillDavis** [comment]
Yeah looks like it is:

![image](https://user-images.githubusercontent.com/2301874/108491769-3edbf800-729c-11eb-9bbd-547dfa5fe66e.png)

I think we can get around it in the short-term by using a hidden property in the component and rate limiting changes to it maybe? Not sure on best approach to this as you obviously want HAX to update on every character when typing in a normal textfield (like a heading) but just causes simple-icon to overwhelm drupal when it's an icon.

**Comment by btopro** [comment]
I know Nikki has been recently looking at how to make the icon picker we have work without polymer at it's core (the real reason we stopped using it bc it was incredibly laggy). Could also debounce it a bit potentially or maybe require the library: part before attempting to evaluate at all. Also might be a good case for haxhooks where it could only debounce if in an editable state sorta thing

**Comment by btopro** [comment]
Commit adds in a very small debounce (100ms) before setting the value. This is low enough that people will feel it's an instant update but if you type quickly it'll delay it enough that you won't spam input values. This isn't specific to the icon timeout but could help reduce it slightly. The #552 and just not having a typed input for icon names (maybe use a select) would eliminate this.
