### ISSUE TITLE
[wcf] Name contains illegal characters

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#553]
Just adding this one quickly while I remember it.

When generating new components (using `wcf element`) in WCFactory, the package.json has an illegal character which always has to be amended manually to allow yarn to start up the demo.

It seems to be the `/` character in the Name field which causes a problem for me. So, in package.json it'll name it to [factoryname]/[elementname] and I can't build or demo the component until I change it to just [elementname].

Error I get in command line:
```
yarn run v1.22.5
error package.json: Name contains illegal characters
```

Example package.json:

![image](https://user-images.githubusercontent.com/2301874/109023833-0893e380-76b5-11eb-9602-0379ce815704.png)

**Comment by btopro** [comment]
weird... do you have the latest version of wcf?

**Comment by JackWillDavis** [comment]
Yea, I think so:

`@wcfactory/cli/0.11.0 win32-x64 node-v15.9.0`

**Comment by btopro** [comment]
can you paste a full file that's been built into jsonlint and see if it fails there / also post it here in full? Wondering if it's a linter thing cause we're not doing anything special in that regard

**Comment by JackWillDavis** [comment]
Hmm it's showing as valid json. I thought I'd seen other packages with a naming convention like that. 

Think it's something to do with my local setup then? Just realised in on the Current (not LTS release) of node so might be something to do with that maybe.

**Comment by btopro** [comment]
yeah I'm thinking it might be that if linter shows valid. I don't get those errors in mine but this sounds familiar from awhile back so thining node version maybe

**Comment by btopro** [comment]
closing; reopen if it wont validate but I believe this is platform specific
