### ISSUE TITLE
[barcode] Explore making a barcode input for HAX

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#555]
make...
- [x] barcode-scanner-input tag in the monorepo
- [x] leverage https://github.com/justinribeiro/barcode-reader if it makes sense if not make a new one
- [x] Add an input field so that we can take their event and turn it into a number
- [x] Bubble events off of it so we could monitor this as a form of input for HAX (but let's just care about input for now)
- [x] pipe into a QR tag
- [ ] Look into open APIs for searching based on barcode to get product inventory match or something
- [ ] wire up to HAXSchema as a valid input type
- [ ] Wire up to HAX so that users could just scan a barcode and go to the link in the page as that'd be a useful little app for demonstration purposes as minimum.

**Comment by JAlbert2** [comment]
Programming steps
-[] Hardware access
-[] Reader/how scanners work
-[] Return result to input field

**Comment by btopro** [comment]
exists. experiment successful
