### ISSUE TITLE
In-page side nav go-go-gadget auto-expandy menu

### ISSUE THREAD

**Issue by michael-collins** [elmsln/issues#556]
Pretty neat! https://doks.themejack.com/blue/manage-content/#homepage

<img width="1541" alt="Screen Shot 2021-02-27 at 3 04 51 PM" src="https://user-images.githubusercontent.com/1085304/109398824-2b203980-790d-11eb-95b3-3d8958bedbc3.png">

**Comment by btopro** [comment]
@collinkleest this would be a good one to pick some skills up in the haxcms theme layer and some low level is stuff. As you scroll down the menu opens / indicates what's active. We have a little menu brick for themes to do in headings in order and indent I believe but would be nice to do this detection as well. Probably applying an intersection observer on load and disconnect it when content changes

**Comment by btopro** [comment]
https://twitter.com/btopro/status/1372207208239337474
