### ISSUE TITLE
[hax] never ending story 3: The one where Nikki fixes more tedious hax things

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#558]
- [x] undo, redo, source, settings DO NOT have tool tip text, while Edit, Blocks, Media, Structure and Help all do.
- [x] Move / Collapse being grey on blue is odd looking. Maybe increase contrast?
- [x] Tool tip for Media / Blocks / Structure is identical hover to the actual text; not sure it's necessary at that point
- [x] Expand/Collapse shifts the row based on positioning / size of the text. lock size of the button width to ensure same between text diff
- [x] description area of upload source widget says undefined to start
- [x] change to dark mode transitions really slowly for text color, doesn't always have text color white on black in different drop down menus
- [ ] grid-plate tag doesn't always show up / have drop areas / outline to imply it's there. Make new content, make a grid.
- [x] Upload Source as a field set and name is a bit odd / redundant w/ being in the Media area. Maybe Add Media should be the section label, then NO "upload source" text
- [x] Media Search and Media above it implying Add, are not consistent. Either drop "Media Search" for Search or apply consistency in previous statement
- [x] When editing an active block, the Layout tab has a left-right scroll bar
- [ ] Clicking the Move button to drag it around, activates the in content drag event so it visualizes where you're going to drop the menu in effect which is confusing behavior
- [ ] drag and drop of the menu needs to ensure it is still entirely in the viewport as I was able to drop it beyond the screen so it becomes unselectable
- [x] bulleted list / numbered list item (li) being active loses the icon / broken SVG is seen as active
- [ ] add content hover might be better served only activating in grid plates or something. It overlaps w/ content / the menu regularly and now that the menu has a nice + always present to add above or below it might no longer be nessecary
- [ ] structure tab only updates when opened / set active. Should update whenever an item is inserted or type changed in some way. This way you could watch the structure build by keeping structure tab active and then adding content / changing heading hierarchies
- [ ] open the view source dialog, close it, open it again and it's blank
- [x] console message in console
![image](https://user-images.githubusercontent.com/329735/109437502-11f1b880-79f3-11eb-86b6-df19c84adfe1.png)

**Comment by nikkimk** [comment]
The last one and 9 of the first 10 are in Nikki branch

**Comment by nikkimk** [comment]
Resolved when https://github.com/elmsln/lrnwebcomponents/pull/496 is merged. You're welcome.

**Comment by btopro** [comment]
putting on my nits in order to pick at your code for errors.
