### ISSUE TITLE
[meta] What docs things needed changed in order to get tooling working?

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#563]
@JAlbert2 please review and report back what things went wrong when getting stuff setup so that we can fix docs to be more hands free / auto installing everything needed. We also need to know what misconceptions we can clear up preventing the on-boarding of new people historically.

**Comment by JAlbert2** [comment]
I'm working with OS X terminal, Big Sur 11.2.2. 
yarn concurrently and html-server were needed, missing from docs.
It wouldn't hurt to add the two yarn packages that are in the wcf repo (http-server and symlink-dir), or at least linking the repo if people are developing with wcf. 
I ran into issues running `wcf star`t and `wcf element`. I did not know I was supposed to clone the Monorepo inside of the wcf factory directory. I would clone my fork of the lrnwebcomponents repo and then try to build a factory within it.
I think most of the issues with wcf came down to I didn't know a repo existed for wcf with instructions. Having just `wcf element` as the only script in the lrnwebcomponents repo to create a new web component is a bit misleading. 
`wcf ui` is also really useful, but I can only find a mention of it in the last commit for the wcfactory readme.md file.
