### ISSUE TITLE
[hax] Editing buttons need to account for full width elements

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#566]
These editing buttons that show in context are positioned in the corners of the element, so when you have a full width element like this they won't position correctly:

![image](https://user-images.githubusercontent.com/4973810/109836454-1230c480-7c3c-11eb-99e7-df19027da8cd.png)

**Comment by btopro** [comment]
I think if we said that the buttons align w/ the element but not beyond the threashold of the `hax-body` tag itself that this would satisfy the positioning needs

**Comment by btopro** [comment]
latest UI is all left justified and all in one place
