### ISSUE TITLE
[hax] Clicking advanced settings hides entire HAX pane

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#567]
This might already be addressed in the HAX UI update but thought I would add it here anyway just in case.

Clicking on the advanced settings cog in HAX editor closes the window (and the advanced settings popup window) and hides them from view. Clicking on "Edit" in the top left shows both windows again.

Steps to reproduce:
* Edit a page in HAX (I was using within ELMSLN)
* Click on the advanced settings cog
* The HAX editor pane will close
* Clicking on Edit again will open both windows

![image](https://user-images.githubusercontent.com/2301874/109837755-68523780-7c3d-11eb-918c-1cc99f66d0ce.png)

**Comment by btopro** [comment]
yea the new UI update resolves this but thank you for reporting :)

**Comment by btopro** [comment]
These assets are in master if you want to fire up the demo for hax-body to check them out. Still has some work in progress things that are busted as I showed earlier today on call but it's very far along in the refresh. #558 details a list of things known w/ where it is currently if looking for documented issues in this iteration
