### ISSUE TITLE
[meta] roster assignments grades csv association  

### ISSUE THREAD

**Issue by michael-collins** [elmsln/issues#575]
Let us associate assignment grades with students via a csv file. No reason to lock up all that useful data in mean Drupals' database.

**Comment by michael-collins** [comment]
<img width="1662" alt="Screen Shot 2021-03-09 at 6 30 12 PM" src="https://user-images.githubusercontent.com/1085304/110553134-88369f00-8106-11eb-880f-36a1107c23e8.png">

<img width="1666" alt="Screen Shot 2021-03-09 at 6 37 26 PM" src="https://user-images.githubusercontent.com/1085304/110553156-91c00700-8106-11eb-9e56-335af711c621.png">

**Comment by btopro** [comment]
#585 accounted for a lot of this already. Will need to revisit after faculty start playing with it end to end to know what additional data slices would be helpful
