### ISSUE TITLE
HAX - text showing up twice in the editor

### ISSUE THREAD

**Issue by Deb-G** [elmsln/issues#577]
When copy and pasting from a word document to the Hax editor without clearing the formatting, the text shows up in smaller text below.  

![Screen Shot 2021-03-10 at 1 27 17 PM](https://user-images.githubusercontent.com/12716869/110837041-c77fff80-826e-11eb-80c8-d4da1dc2a8e0.png)

This happened while working on: https://courses.aanda.psu.edu/arth280/

**Comment by btopro** [comment]
@Deb-G when you get a chance can you email me the word document you used that generated this issue? I did some more testing of the paste clean up that hopefully handles this but it's HIGHLY use-case specific (like I just test a ton of different documents to see if I can clean them up) given the complexity of cleaning word garbage :). Closing for now, thanks for the report and I look forward to the email so I can do some more testing.
