### ISSUE TITLE
[elmsln] [lrnwebcomponents] ResponsiveUtility - issue with breakpoints in ELMSLN

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#581]
Having a small issue with the ResponsiveUtility in a webcomponent. I've initialised it as:

```
window.dispatchEvent(
  new CustomEvent("responsive-element", {
    detail: {
      element: this,
      attribute: "size",
      relativeToParent: false,
      sm: 576,
      md: 768,
      lg: 992,
      xl: 1200,
    },
  })
);
window.ResponsiveUtility.requestAvailability();
```

The size parameter seems to jump upwards at a certain point. When resizing the screen manually, it goes down in this order:

* xl
* lg
* md 
* sm
* md
* sm
* xs

I think it's because the `responsive-width` attribute is taken from the parent element instead of the screen itself maybe? It looks like `sm` switches to `md` at about `916px` screen size. This is where the menu bar disappears from the left-hand side on a course site which extends the width of the content area.

Is it possible to have the responsive utility to use the total Screen size instead of the parent element?

**Comment by btopro** [comment]
`relativeToParent: false,`

**Comment by JackWillDavis** [comment]
Got it, working fine now thanks.
