### ISSUE TITLE
[hax/ux] Task A: grid of images

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#592]
Create a page of content that has 4 images side by side in a grid

Document the steps involved / any areas that the user has confusing / expresses confusion in doing the task.

**Comment by francescaansell** [comment]
parter: Neil Porterfield 

Starting process… 
Was able to choose a name and change the theme
Started by looking on the side bar for options
Choose edit page content
Choose Add media Realized was wrong 
Choose blocks… choose grid layout had a hard time getting the grid layout on the page
After adding the grid went to add building blocks
Went to add content
Went to Add blocks 
Add an image by URL from internet search 

Made the realization of repetition 

Was able to finish the task

**Comment by Griffin-Sullivan** [comment]
Grid of 4 images
Tried to use a table block to make a grid,
Couldn’t delete the table
Tried to use image gallery
Couldn’t delete the gallery
Found grid block
Accidentally added paragraphs to grids
Found add column button for each row
Dragged images into empty parts of grids
Couldn’t delete paragraphs
Added the images under paragraphs
Struggled to find where to put blocks throughout whole process, because the blue highlight indicator wasn’t popping up
Discovered wherever you drag it will work
Figured out delete requires a hover, before clicking a drop down option to confirm delete

**Comment by TechWithJoe** [comment]
Partner: Anthony 

1. click edit button
2. wrote description
3. clicked media button
4. googled dog picture
5. Saved images
6. Dragged them from saved photos and they uploaded
7. Adjusted width with the info on the left hand side tray
8. did 5-7 multiple times

Issues: The photos would not stack in a 2x2 grid, they will be on a line.

**Comment by TechWithJoe** [comment]
Update: HAXcms would literally not let us upload a photo. "error, photo is not supported"

**Comment by TechWithJoe** [comment]
Update: I had to use my computer, Anthonys computer would not allow image uploads for strange reason.

**Comment by btopro** [comment]
@TechWithJoe if you or he can recall; what was the NAME of the file or format involved? This could be a simple fix on our end but another example of unintended consequences of sanitizing file names :)

**Comment by UIXKinguin** [comment]
Grid of images - Jonas Jason

logged in using credentials

new site created

title set as Image Grid

Opened the edit page content

Deleted presets

Go to blocks

Went to grid layout and was able to just drag in the grid layout

Created a 2x2 grid and dragged and dropped the image blocks in to the grid and uploaded the images once the blocks were set.

Attempted adding a column, result was not what he expected

Confused on how to format the grid properly

Image will not slot to the side but only slots into the bottom.

Adding and deleting columns does not create the space required

Deleting all images and setting the gridlayout beforehand allowed him to put the images in cleanly.

**Comment by btopro** [comment]
shes pressing new site
she pressed already creted grid image test
edit page content
she checked blocks
she sees image gallery or image
shes trying image
she had to fully open page to edit it
going back to blocks>image
she realizes she needs to add media first
shes going to media
shes browsing her computer library to choose images
she has a picture of greece and is checking the layout section
shes adding a column
media again, and browsing again to add another picture
shes making the picture smaller
going to settings
edit selected image
then we figured out that we had to use grid layout in blocks
then she clicked in each block and added media
that made he final result look correct
