### ISSUE TITLE
[hax/ux] Task C: Create a multiple choice quiz

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#594]
Create a multiple choice question on the page after a paragraph of text setting up what the question will be about.
- add the question with a title
- Add 3-4 possible answers
- Set the correct answer and save the page.
- Take the "quiz" to verify it works

**Comment by JAlbert2** [comment]
Logged in
Create a new site under a name
Course theme since it doesn't matter too much
Launch page
Read the intro documentation
Edit page content
Searched for question within block tab
No blocks found with question, found under multiple choice
First, make the title of the question
Then, create the questions
Select randomize answers
Some time to find where to edit answers, but easily found
Changed placeholders
Automatically saved?
Not saved
When does it save?
How do we save?
Recreate question as it did not save when the page was reloaded
Testing functionality, making sure the element works
We're both oblivious, save page button on left side
Celebration at save
Done?

**Comment by colemantech2-0** [comment]
-clicked on "load multiple choice quiz" page that was already created
-pressed edit on the side of the page
-selected content on page & then deleted it
-pressed blocks & then pressed multiple choice
-typing random questions for people to answer
-"how do I edit the question I already created?" was a question asked aloud
-"aha" --> took 30 seconds
-now that figured out how to edit, went to options, then clicked on toggle expand
-then added another block from toolbar and typed a new question out
-then hit enter and created a couple of choices for the question
-now is adding a title by looking in the blocks section of the toolbar
-clicked on "heading 2" & then typed in title
-tried to change font but didn't know how to so made it bold
-added horizontal line for asthetic purposes using tool under blocks 
-checked to make sure quiz works & it does

**Comment by nzp126** [comment]
Create a new site button
Named it
Loaded it
Went to the edit pen
Went to Add Content
Added a paragraph
Wrote a quiz title.
Back to Add Content 
Selected multiple choice
Dragged it into the paragraph
Clicking a little circle + that added a paragraph
Clicked check answer when there was no answer and I was rewarded with confetti
Wrote a NEW title for the Quiz
Used the sidebar to write the first question
Added an answer by clicking on the answer set. 
Clicked add item to add a new answer
Now wrote the question 
Wrote the answers to the questions
Clicked the "correct" box to specify which answer

**Comment by Griffin-Sullivan** [comment]
Create multiple choice quiz
Had to find edit button
Had to go to blocks to find quiz
Tried to directly click on the answer option to edit
Found answer editing under ellipses button
Used add item button to add another item
Changed all of the values to different answers
Set the correct answer with the checkbox
Tested block by checking right answer and wrong answer

**Comment by JonasJason** [comment]
Partner: Jeffrey Oh

Task: Create Quiz

Confused about whether or not to add block to frame or layout

Click add block > multiple choice

Edit:

Change Title
Edit question of multiple choice
Add options

Trying to figure out how to mark an answer as “correct”
Selected “correct” option successfully

Trouble reordering answers
Trouble editing the text of each answer

Change the way the search box looks when searching blocks

Not sure if auto-save or manual save
Found manual save button

**Comment by CleverInsect** [comment]
Multiple Choice Quiz: Caitlin Norse
•	Clicked the new site button
•	Named the new site "Multiple Choice Fun"
•	Changed "course theme 3" to "course theme"
•	Clicked on newly created website
•	Clicked edit page content 
•	Clicked blocks 
•	Scrolled down to multiple choice
•	Went back to blocks 
•	Clicked header
•	Dragged the header up above the multiple choice
•	Wrote “what is my favorite flavor of Ice Cream” in the header
•	Deleted header
•	Multiple choice already comes with a title 
•	Copied title put it as question 
•	Renamed title as Ice Cream Quiz
•	Scrolled down to answer set in the side panel
•	Added item clicked on the three dots and wrote vanilla 
•	Went to the next one and wrote mint chocolate chip
•	Added another item, clicked the three dots added chocolate
•	Repeated process, but wrote strawberry
•	Clicked correct checkbox on mint chocolate chip
•	Kept feedback
•	Saved the page content
•	Clicked on vanilla to check answer 
•	Response as wrong which is correct for the quiz
•	Clicked the reset button
•	Clicked on mint chocolate chip
•	Clicked check answer
•	Got "Great Job!"

**Comment by mcao** [comment]
Multiple Choice Quiz: Michael Cao
- Clicked into the sample site and created a new page and named it, got sent to editor
- Had to find the button to add blocks, and then find the multiple choice one
- Clicked on that one and then had to screw around to figure out how to give the page a title
- The title on the page vs what the tab displays as the title vs the title in the text are all different
- Figured out the difference between the three eventually. 
- Gave the multiple choice quiz a title, but apparently the title and question are different
- Gave the multiple choice question a couple of choices - struggled to find out how to do so
- Created "what is the best cms" question, created options, and selected two answers as the correct ones
- Kept feedback as is with default options. The choices in the question kept shifting around.
- Saved page and went through the quiz, selecting the two correct answers. Got the question right.
- However, there's nothing to indicate that you need two choices, and any combination of choices besides the exact two correct choices returns incorrect. It doesn't even tell you if you select ONE of the correct answers but not both, or select both of the correct answers but then select a third option.
- Figured it all out eventually but there's a couple barriers to usability still remaining.
