### ISSUE TITLE
As a user I want to be able to easily see where I can drag content.

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#60]
Proposed Solution:
When content is in the drag mode, instead of the grey use a more prominent color or technique to give attention to the possibilities.

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/73882403-fb991d80-482f-11ea-9a9c-acedb8733689.png)

Added green drop zone and made drop areas slightly larger (36px instead of 20px) to make it more obvious

**Comment by junkant** [comment]
Yes, that will work for sure!

**Comment by btopro** [comment]
Closing then as this is now the way it works in master :)
