### ISSUE TITLE
As a user I want the up/down and drag buttons to be more standard and prominent.

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#61]
Proposed Solution:
Take a look at GrapesJS and how they incorporate icons for dragging.

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/73988079-a16f8980-490f-11ea-80ab-135402389b21.png)

for reference. I do enjoy the idea of having it be a mini bar off to the top right which also has an offset color for what is currently highlighted / selected. I agree the bar is too squished in 1 area and it distracts from writing when drag and move is not a common operations that you'll do every paragraph / item.

Also this is a convention we could add visually into the `grid-plate` tag. @michael-collins thoughts on a design for a small floating container like this which could be for movement / replication / delete / grid types of operations?

I like in grapes how it has the text ops to the left (if double click) but the "grid" options off to the right. If we had a small visual area like this I think it could help w/ all moving and plate modification options on the right and all contextual to the item itself over to the left (@nikkimk is our chunking expert for mental models so pinging her too)

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/74065054-02579a00-49c2-11ea-83d7-025af757f62e.png)

work in progress concept. All "grid" style buttons are moved over to the right (which there are a lot so... would need to think what these are and how they are ordered more carefully). All contextual to what you are working with are on the left.

For example, positioning and scaling are right now over top of the UI which is inconsistent. Once we get #10 #8 w/ a panel that has everything you can modify on it, that would be able to take the place of scale, positioning, change type, possibly even the grid / column replacement aspect.
![image](https://user-images.githubusercontent.com/329735/74065156-3af77380-49c2-11ea-88f8-a2592d5b579f.png)

**Comment by onelittlebecca** [comment]
I think we can provide some effective ways to lay these two different button sets out, while improving the UX and still conveying that these things control different things. Let me think on this.

**Comment by junkant** [comment]
I agree there are too many buttons.

What is the functionality of the + and - ?

Maybe remove the add element at the end? This would not be a likely place for someone to look for adding elements. Especially if this is the one place for drag and drop and layout altering. Maybe have it appear at bottom or top of content block.

<img width="85" alt="add element bottom" src="https://user-images.githubusercontent.com/20044546/74534142-19861280-4f01-11ea-8ae3-eae21d8052a9.png">

**Comment by btopro** [comment]
I agree. Here's the latest state of it so we're on the same page. +/- add and remove columns. While needing clarity this is incredibly fast / easy to use in the current pattern.

## bar outlining an element
![image](https://user-images.githubusercontent.com/329735/74538938-2e67a380-4f0b-11ea-8bae-3107d69477f4.png)


## hover state for drag handle
![image](https://user-images.githubusercontent.com/329735/74538913-227be180-4f0b-11ea-86f9-bad7fae2bf4a.png)

## click state for drag handle
![image](https://user-images.githubusercontent.com/329735/74538876-14c65c00-4f0b-11ea-9f9c-ca5e7ddc3efb.png)

I'm going to do some additional work today before recording a video but this is honestly way more functional than before.

**Comment by btopro** [comment]
Standard location for these. Let's consider this taken care of (grids now use the same drag and drop as the normal one) and then we can do an additional review in another round #10 has screen shots showing how this is handled https://github.com/elmsln/issues/issues/10#issuecomment-591680120
