### ISSUE TITLE
[ux project] voice based interface

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#611]
We have web components that can leverage voice APIs in the browser. Think Xbox kinect type of interface or Siri, but in web components. Using this, we've wired the baseline for this into HAX. The state of which can be reviewed here - https://www.youtube.com/watch?v=kzu0kfErHMA

We need this to be intentionally planned and implemented for a quality voice based navigational experience. This is both a tech demo but also practical dictation example and generic, reusable web component. Some considerations
- What makes a good voice UI (research)
- Any research / writing about how Siri / Alexa / Cortana work from a user input and response perspective
- How we can easily implement this in any system, using HAX as a vehicle
- We already have wiring in HAX that needs reviewed, documented, blogged about, etc.
- We need a recommended way for new voice commands to be added to HAX and other developers to contribute voice based processing UI tech
- The conversational piece needs worked out. You ask for an operation, it's committed, but then what additional options pop up and how do you handle those. This is not currently explored.

To successfully complete this issue there will need to be documentation as well as functional commits to implement the voice UI changes internal to HAX. A stand alone demonstration of the technology that effectively teaches people how to implement it outside of HAX would also need to be produced.

**Comment by francescaansell** [comment]
I think this is a good option for me. This summer at my internship I have a similar assignment. My career goals are somewhere between UX designer and IT Project Management.

A few points to clarify... this issue will need lots of documentation/research along with learning how to implement this technology I research? 

@btopro

**Comment by Griffin-Sullivan** [comment]
Me

**Comment by btopro** [comment]
its a fun prototype; some day it would be a full research project but its good for now :)
