### ISSUE TITLE
[hax] Grid defaults to using a paragraph

### ISSUE THREAD

**Issue by Griffin-Sullivan** [elmsln/issues#614]
When you create a new grid, it automatically inserts a paragraph into it so that it's not empty. This makes it impossible to delete the paragraph as long as the grid is empty. Instead use the "add block" or element button in each grid space so the user can decide what they want in their grid.

**Comment by btopro** [comment]
fixed; now empty state and hover correctly allows inserting into any open columns (or above/below the tag entirely)
