### ISSUE TITLE
Typo on add page

### ISSUE THREAD

**Issue by donoberry** [elmsln/issues#616]
I was creating a page on the blog theme. When you click the add button on the side tab, there are two fields, title and location, underneath the location text box, the text reads "What is displayed in the **bnowser** after your site name / URL" If bnowser was the intended word, disregard.

**Comment by btopro** [comment]
Good find. The small details turn ppl off when overlooked and I'm a terrible speller. This is under the elements/haxcms-elements/lib part of our monorepo. Search for that misspelling and your sure to have an easy commit fix 🤓

**Comment by btopro** [comment]
PR resolved this
