### ISSUE TITLE
DRUPAL: Media Module integration

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#62]
As a user, I would like to have the ability to upload my media assets into the Drupal media library.
Proposed Solution:
Upload into the media library and at the time of upload choose the media type.
 ______________
As a user, I would like to be able to insert media assets from the Media library.
Proposed Solution:
Reuse media library assets.

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/81746260-279ded80-9474-11ea-82c0-903c9c0e466e.png)

Dev code for D8 pushed up and supports searching these. We need to make the upload side save as a media entity instead of the file entity (like it is currently)

**Comment by onelittlebecca** [comment]
damn! you've been busy Bry!

**Comment by btopro** [comment]
https://www.drupal.org/project/hax 3.10 now has Media Module integration for searching as well as now uploading.
![image](https://user-images.githubusercontent.com/329735/81859641-87a79900-9533-11ea-8e0d-3409cb64be76.png)

![image](https://user-images.githubusercontent.com/329735/81859613-7eb6c780-9533-11ea-9978-f18b03599326.png)
