### ISSUE TITLE
[HAXcms] Theme used on haxtheweb.org isn't responsive on mobile

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#621]
There are elements which extend the width of the viewport and so require scrolling horizontally.

![image](https://user-images.githubusercontent.com/4973810/113873276-92eb5f00-97ac-11eb-8a9e-77d845738f0a.png)

**Comment by btopro** [comment]
@collinkleest can you detour from bootstrap theme and fix this. It's in which ever "clean" theme that haxtheweb.org is using. Should be pretty easy given what you've been working on recently :)
