### ISSUE TITLE
[haxcms] initial login camera enhancements

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#638]
- needs to align the photo it takes correctly
- needs to only turn on web cam when asked to do so
- needs to turn off web cam after it's been initialized

**Comment by JAlbert2** [comment]
Might be able to take my solution from barcode-reader to fix this.

**Comment by btopro** [comment]
@JAlbert2 are you claiming this one? I agree it might be similar or at least not a huge issue. The way of getting this code to spin up to even attempt
- get HAXcms downloaded
- make a symlink from `lrnwebcomponents/node_modules` pointed to `haxcms/node_modules`
- this allows you to do development in the monorepo yet have it affect the cms / see it working in action

run `yarn start` in the `haxcms` repo root. This will fire up a local demo of the login sequence with fake data in order to simulate logging in (admin/admin or any random input I think works on this screen). Should see the login camera and it being sized incorrectly

**Comment by JAlbert2** [comment]
Yeah I'll claim this one

**Comment by btopro** [comment]
@JAlbert2 wok on this one next

**Comment by JAlbert2** [comment]
Got the tooling installed last night, but having trouble pinpointing the specific elements related to the issue

**Comment by btopro** [comment]
`simple-login` is the project and base element doing all the work. simple-login-avatar is rendering the image
![image](https://user-images.githubusercontent.com/329735/115457571-b96cb980-a1f2-11eb-8669-4ce8429dbc91.png)
screenshot to help diagnose / laugh.

**Comment by JAlbert2** [comment]
Currently have simple-login-camera wired up to turn on the video with an event. I'd like the simple-icon-button to trigger it, but I can't find how clicking the camera in HAXCMS snaps a photo. Should I not be in the simple-icon-button.js file?

**Comment by btopro** [comment]
code I can pick through? simple-icon-button will emit an event. It's probably more a matter of listening for the event. example from HAXcms site editor UI:
```
<simple-icon-button
        hidden
        dark
        id="editbutton"
        icon="${this.__editIcon}"
        @click="${this._editButtonTap}"
        title="${this.__editText}"
        voice-command="edit (this) page"
      ></simple-icon-button>
```

In this the `@click` event callback is capturing that this was clicked on and then allowing you to do whatever in response to it.

**Comment by JAlbert2** [comment]
https://github.com/elmsln/lrnwebcomponents/pull/526

**Comment by btopro** [comment]
code review opened for this

**Comment by JAlbert2** [comment]
I can find the simple-icon-button in the console, but I can't find the index file within the HAXCMS repo.

**Comment by JAlbert2** [comment]
Do you know why the video stream only renders when you leave the webpage then return to it for simple-login-camera?

**Comment by btopro** [comment]
no, might be a local development thing?

**Comment by btopro** [comment]
does it happen when running `ddev start` for local spinning up of haxcms?

**Comment by JAlbert2** [comment]
I'll take your word for it that it works. `ddev start` is not a valid command for me, probably just missing a command in my terminal.

**Comment by btopro** [comment]
like `ddev` itself :) https://www.ddev.com/
