### ISSUE TITLE
[spacing tag] A tag to show conditional rendering usage

### ISSUE THREAD

**Issue by JAlbert2** [elmsln/issues#641]
A tag to dynamically space elements in the demo to show rendering or functions that only load when the tag is visible. Instead of repeatedly adding br tags, have a tag do the work.

**Comment by btopro** [comment]
so like "make me 20 spaces" as `<demo-space count="20">` sorta thing? Would be a good demonstration element / something to talk through if you'd like to work on this idea.

**Comment by JAlbert2** [comment]
Not sure how to reference pr's or commits from another repo.
