### ISSUE TITLE
[elmsln] [hax] HAX Editor should be in edit mode by default when clicking on HAX Editor

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#645]
In ELMS:LN, after clicking on 'HAX Editor' the course author is taken to the HAX authoring page but HAX Editor itself is not in editing mode. From a UX perspective it feels as though it should be in edit mode by default at this point

**Comment by btopro** [comment]
doing a build now to test again but I believe this will now work. editor loads, waits 2s and then sets editMode. There were some initial timing issues internal to how h-a-x sets up the page / loads info in that caused it to open rapidly and then close as the state management kicked in. Will close when this is fixed.
