### ISSUE TITLE
[product-glance] make a web component out of a thing

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#648]
https://www.coursera.org/specializations/python on the right hand side has a cool little series of things like this:
![image](https://user-images.githubusercontent.com/329735/114806848-68cd0a80-9d73-11eb-89b9-6c6eecf600aa.png)

This is effectively a web component that...
- leverages simple-icon for the icon presentation
- has properties of icon, title
- has a slot that is rendered as the lighter grey text

This could be a design element purely (product-info), then loaded into a list (product-glance).

CSS variables could default to simple-colors variables but default to match the mock up.

**Comment by whatsacomputertho** [comment]
If no one else is doing this I'd gladly work on this

**Comment by btopro** [comment]
Sounds good to me. Much more straight forward to create a new thing :)

**Comment by btopro** [comment]
https://www.npmjs.com/package/@lrnwebcomponents/product-glance

https://twitter.com/btopro/status/1390328789083766787 -- thread about this workflow and what came about as this is now haxified

![image](https://user-images.githubusercontent.com/329735/117328970-296d7780-ae62-11eb-8dfe-8b19f8ece884.png)
