### ISSUE TITLE
[star-rating] make a star rating element

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#649]
![image](https://user-images.githubusercontent.com/329735/114807168-f90b4f80-9d73-11eb-9947-44e4117165e3.png)
as an example. A star rating element...
- could leverage the star icons from simple-icons
- have color options as simple-icons can be leveraged to use SimpleColors easily
- properties of stars (Number) and showNumber (Boolean) in order to provide variation
- the text after this in the mock up would be part of the demo in order to demonstrate that this is an `display: inline-fex;` defaulting element and needs to correctly adhere to the font sizing and line spacing of it's peers

**Comment by hvk5388** [comment]
working on it

**Comment by btopro** [comment]
@hvk5388 excellent. Let me know if you need any scenario advisement or questions.

**Comment by btopro** [comment]
interactive and non-interactive modes present. Also now colorizable
