### ISSUE TITLE
[hax] Support custom field based items in CMS integrations

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#65]
For drupal integration, it would be useful to be able to custom field types to the page that have already been created and are integrated with the content type being edited -- is that possible?

**Comment by btopro** [comment]
I'd have to see a mock up of how you'd expect this to function.

**Comment by junkant** [comment]
Something like this.
If we categorize our options.
We should have a section called "Drupal. Fields" or something similar.
<img width="207" alt="drupal-fields-idea" src="https://user-images.githubusercontent.com/20044546/74385867-9068c180-4dc2-11ea-98b3-fcaa74a29d41.png">

**Comment by btopro** [comment]
ahhh ok, that's what I thought you were implying :). That'd be cool for sure. I think we could add some form of support for this by allowing custom definitions of trays w/ the tray UI thing I'm playing with currently. Then we'd need some special drupal / token stuff to make that work. Would you mind mocking up what you'd expect to find under that drawer and what that might look like?

**Comment by junkant** [comment]
Super quick and grey!
Each field is on its own line with the type of field it is on the right.
![quick-custom-field-idea](https://user-images.githubusercontent.com/20044546/74440471-137a2e00-4e3c-11ea-8632-3954536c3a3a.jpg)
