### ISSUE TITLE
[product-offering] make this a web component

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#650]
![image](https://user-images.githubusercontent.com/329735/114807586-ac744400-9d74-11eb-8752-e8d6a35c24ce.png)
Using this for inspiration (https://www.udacity.com/course/data-scientist-nanodegree--nd025) try and make 1 of these as a product-offering type of card

- properties include image, icon, accent-color (provided by SimpleColors), title (that auto underlines 1st word of text)
- slot for additional writing
- This could be presented inside of a grid-plate tag (in the demo that is) in order to achieve the listing effect OR could be done as a map running through an array of data
- Make sure to support lazyloading on the image and also have a fallback / placeholder if none is set

**Comment by francescaansell** [comment]
Claiming this one

**Comment by btopro** [comment]
Sounds good. Work on this in a fork of our monorepo please which means installing the wcfactory.js.org tooling

**Comment by btopro** [comment]
@JAlbert2 installed and knows what this means so he can help you get this setup in class if you run into issues. If you do, then to start use open-wc.org to start your element as it's very straight forward

**Comment by francescaansell** [comment]
Yeah I think I am going to need advice, Seemed easy enough in the documentation but my computer keeps saying wcf is not recongized.

**Comment by btopro** [comment]
Np. Common issues in setup. What OS you got? @JAlbert2 if you recall getting this chime in

**Comment by francescaansell** [comment]
Windows... I see an info message saying the platform 'win32' is incompatible with this module

**Comment by btopro** [comment]
Win32? Might need some more device details. Did you follow the additional steps about windows?

**Comment by btopro** [comment]
Try using cygwin and see if that helps

**Comment by btopro** [comment]
Then if that doesnt work, use open-wc.org tooling and file an issue about this incompatibility so we can put people on it this summer

**Comment by francescaansell** [comment]
Will do, trying to install and use cygwin now

**Comment by btopro** [comment]
this was previously accepted, just forgot to update
