### ISSUE TITLE
[barcode-reader] Fix overlay not resizing

### ISSUE THREAD

**Issue by JAlbert2** [elmsln/issues#651]
Within the current build of the barcode reader, the gray box overlay will resize the height, but the width is locked at 100%. Should dynamically resize with video size. Scale attribute exists to resize video

**Comment by btopro** [comment]
look up "css intrinsic video ratio"

**Comment by JAlbert2** [comment]
It isn't taking hold with it. I think something within the border CSS that is preventing it from readjusting. May just ahve to rebuild the overlay.

**Comment by JAlbert2** [comment]
Right: 0px is forcing it right. Would like to inject the scale attribute into the css, but
`Error: Value passed to 'css' function must be a 'css' function result: undefined. Use 'unsafeCSS' to pass non-literal values, but take care to ensure page security.`
Tried `<div id="overlay" right="${this.scale}%"></div>` but `Attribute right is not allowed here`

**Comment by btopro** [comment]
`.style="right:${this.scale};"`

**Comment by btopro** [comment]
LitElement will bomb out when you do bindings like your example which are not valid fyi

**Comment by JAlbert2** [comment]
`.style="right:${this.scale};"` is also not allowed within the div tag.

**Comment by btopro** [comment]
Try without the . I've done this else where. Also you could target the div via shadow root query selector and then apply th styles manually via via styles attribute. See how this happens in hax-body with .right positioning cause we data bind to a style in this similar manner for float: right

**Comment by JAlbert2** [comment]
I found a workaround with just applying it to the video tag directly. Tried using the shadowRoot in _firstUpdated() and constructor, but no luck.
