### ISSUE TITLE
[hax] drop down options for common style settings

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#654]
The Advanced tab currently has the option to add additional CSS styles. The UX would be better if some of the more common CSS styles could be tweaked via pre-select options. 

Initially this should only focus on component positioning since the styling of content within the component itself (typography etc.) should be managed with additional in-context component editors (or declared separately as editing options by the component author).

Initial options:

- Display
- Position
- Top
- Right
- Left
- Bottom
- Margin (all directions)
- Padding (all directions)

![image](https://user-images.githubusercontent.com/4973810/115238721-e9925a80-a115-11eb-84ec-9f06dd78a05a.png)
![image](https://user-images.githubusercontent.com/4973810/115238786-fdd65780-a115-11eb-8d1b-34c28f58420e.png)

**Comment by btopro** [comment]
This should go under developer tab. Not sold necessarily on top,left, etc positioning but #887 could be under here potentially as well. Want to empower css knowledgeable users but not overwhelm core audience that lacks html knowledge
