### ISSUE TITLE
[dx] come up with a consistent "this is how to do it in windows" doc set for lrnwebcomponents

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#657]
We have things that mostly work for windows but we need more detailed instructions so we can scale up and support more developers more rapidly this fall. It "largely works" but there are all kind of odd edge cases people run into all the time here.

This could be a good summer project for a student to improve the DX at this level.

**Comment by JonasJason** [comment]
This is definitely up my alley and honestly useful for me to have as a quickstart guide to contributing. I can start looking at this

**Comment by btopro** [comment]
ENHANCEMENTS (at least to work on windows in cygwin)

yarn global add concurrently
yarn global add gulp
yarn global add es-dev-server


https://github.com/coreybutler/nvm-windows/releases - install NVM
install cygwin
open cygwin
run the following in cygwin:
```
nvm install 14.16.1
nvm use 14.16.1
node -v
npm install -g yarn
curl -fsSL https://raw.githubusercontent.com/elmsln/WCFactory/master/wcfactoryme.sh -o wcfactoryme.sh && sh wcfactoryme.sh
mkdir -p ~/{homedirectory}/Documents/company
cd ~/{homedirectory}/Documents/company
wcf start

```
Open a web browser and fork https://github.com/elmsln/lrnwebcomponents to your own user

run the following in cygwin:
```
mkdir -p ~/{homedirectory}/Documents/git/github/{username}/
cd ~/{homedirectory}/Documents/git/github/{username}/
git clone git@github.com:{username}/lrnwebcomponents
ln -s ~/{homedirectory}/Documents/company/factories/lrnwebcomponents ~/{homedirectory}/Documents/git/github/{username}/lrnwebcomponents
cd lrnwebcomponents
yarn install

**Comment by btopro** [comment]
Need to fire up a windows machine to attempt more.

**Comment by btopro** [comment]
faster install overall should have resolved many windows issues right there
