### ISSUE TITLE
[documentation] See what redme details we are missing from readme.so

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#663]
Cool lil web app here that could help us find things ppl might be expecting and add to our readmes https://readme.so/editor

**Comment by hvk5388** [comment]
Our read me includes a lot of tech help, but not a lot of personal touches. Some of the things on the list that I thought might be helpful:

- Acknowledgement/Authors
- Color References (not sure if we have any)
- Logo (just to spice it up)
- Contributing Instructions
- FAQs (if you have any you like to answer right away)
- Feedback/Support (unsure if its a great idea to give out contact, but you could just say to message on github)
- Tech Stack (just to give more info on what it is)

**Comment by btopro** [comment]
Great ideas and thank you for reviewing those missing details. Please start working up a PR to the README for `lrnwebcomponents` that at least establishes these sections. Not sure what color references means either unless you mean how we use colors in which case -- https://webcomponents.psu.edu/styleguide/?path=/story/colors-simple-colors--all-the-simple-colors

**Comment by btopro** [comment]
You are the bomb dot com
