### ISSUE TITLE
[marketing] OERSchema needs a new website

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#669]
http://oerschema.org/
Update to use hax11ty (uses jeckyll currently) but needs to allow for it's current way it generates the RDF schema. Best bet is to iframe that part and make a wrapper site that's hax11ty so we can sustain and enhance it as we grow.

needs:
- https://github.com/open-curriculum/oerschema-logo
- https://github.com/open-curriculum/grav-plugin-oerschema - and other plugins that it integrates with other platforms

**Comment by michael-collins** [comment]
Point of fact, it's not a Jekyll site. Boyce built it using Gulp and Twig. If you want to add to it, just do some pull requests against the https://github.com/open-curriculum/oerschema/blob/master/src/config/schema.yml file, and it will autogenerate new schema. It has example code block features. A better use of time would be to add to the schema definitions and provide code examples.

**Comment by michael-collins** [comment]
Also, all changes get discussed beforehand with the project group, so make sure to bring up change proposals in the issue queue ahead of making pull requests.

**Comment by btopro** [comment]
yeah I dono how to update that then. I'm not sure why a marketing site merged w/ an ontology but then again I've done things like that before so no stones thrown :p. Still, from a pure marketing perspective It needs a different theme some how.

**Comment by michael-collins** [comment]
I think it was for efficiency. It’s somewhat trivial to change the aspects
if the theme, so just let me know what you think should be changed and we
can try to move it forward.

**Comment by btopro** [comment]
the homepage has a video (by me) showing something that doesn't even work any more to my knowledge.

**Comment by michael-collins** [comment]
Okay, I'll remove it. Anything else?

**Comment by btopro** [comment]
Anything to suggest it's part of larger efforts. I think it's a larger redesign of properties and how they are all connected / integrated. Wasn't a specific "this needs a new website" in a vaccume. More, how do we better communicate what ELMS is, HAX, HAXcms, OERSchema, LRNWebcomponents, WCFactory, HAX11ty, etc. Using HAX11ty for all sites is one start in this direction. Having common navigational structures / 90s web-ring style linkage or logo / link farm associations, are more in general what I had in mind as opposed to specific "just change the site to look like X" :)

**Comment by btopro** [comment]
It's hooked into everythign else now but for ontology reasons needs its own thing too. https://oer.hax.psu.edu/bto108/sites/haxcellence/documentation/oer-schema
