### ISSUE TITLE
[video-player] bugs

### ISSUE THREAD

**Issue by cgldevel** [elmsln/issues#681]
I've attached a screen recording to demo:
1) After pause, the video-player automatically resumes play from the beginning, instead of maintaining its position on pause.  
2) After returning from full screen, the video-player stretches from it's original size. 

I was able to duplicate bugs across multiple courses and a fresh hax.psu site.  Reported by student to faculty

https://user-images.githubusercontent.com/11019355/117845373-7a101680-b24e-11eb-9111-e75bfc94493b.mov

**Comment by nikkimk** [comment]
The second issue is resolved in my latest PR
