### ISSUE TITLE
[simple-fields-array] adding item when form injected dynamically is undefined

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#683]
HAXcms has a simple array tag that it loads and then the user can hit "add item". This is generating an error in that it says `undefined` in the id that it generates for the array of items. Then when you go to reorder (or would query the id directly to get a the data) you'll get undefined / not-found as there is no numerical entry to parse. This is an issue w/ the simple

This happens in the HAXcms site settings panel that opens though it probably isn't specific to HAXcms as it's just adding the form to the page.

![image](https://user-images.githubusercontent.com/329735/117887928-6e891380-b27f-11eb-9467-229f506b18df.png)

**Comment by nikkimk** [comment]
This commit to master should resolve the issue: https://github.com/elmsln/lrnwebcomponents/commit/6bc6bf65146f026d169976b0bf4a9b3f3076f31b
