### ISSUE TITLE
[HAXdesktop] menu should not be closed when in production environment

### ISSUE THREAD

**Issue by whatsacomputertho** [elmsln/issues#688]
This might involve...
- Opening main.js within the HAXdesktop repo
- Updating the createWindow() function body such that it does not remove the entire menu if in production environment
- Instead, it should just remove the devtools menu item (I think, at least)
- Also update the comments I left after completed

**Comment by whatsacomputertho** [comment]
Also maybe we should create a .env file as well

**Comment by btopro** [comment]
Not sure what "in a production environment" means. This is running locally on their desktop so that's basically "prod". An ENV file which can then be used to trigger the debug / admin tools for local development on the app itself would be good though.
