### ISSUE TITLE
[HAXdesktop] should load a welcome screen on execution

### ISSUE THREAD

**Issue by whatsacomputertho** [elmsln/issues#689]
This would involve...
- Updating the mainWindow.html file which is loaded on execution
- Possibly include UI element which toggles the "Open" system dialog on click
- Not sure what else the welcome screen would include, maybe just branding from there and other stuff idk

**Comment by btopro** [comment]
This should be what's seen on the demo / log in for https://github.com/elmsln/haxcms on the haxcms-site-listing UI. This UI needs replaced with something more simplistic and using the desktop app as a vehicle for this would be ideal.
