### ISSUE TITLE
[hax] edit source button then scrolling can lose the hax context item menu

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#690]
Just like it says.
- make something long source wise
- scroll down while editing source
- the context menu for working on the item can hide
- then you can't set your HTML source you've been modifying

Possibly we need a stationary button for changing back to the other mode or not allow that item to leave that state until changed back over. I like the current behavior of click away and it goes back to normal but I'm not sure if this is user expectation or not.

**Comment by btopro** [comment]
#677 related and might be resolved by enhancements there

**Comment by nikkimk** [comment]
The latest PR resolves this.
