### ISSUE TITLE
[haxSchema] expand API to support slots like we do properties in configure

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#694]
Great idea @nikkimk had while working on #677 is to have haxProperties which map `slots: []` in the way that we map things to the `configure` and `advanced` tabs in the UI. By doing this and slots having their own API we could better inform HAX of where slotted material should go and what can be slotted (for example a11y-tabs can only accept a11y-tab, while another element might only allow paragraphs / bulleted lists).

This will require an expansion of the existing API and existing usage of `slot` under configure/advanced will be left in-tact (though it's only used rarely at the moment).

**Comment by nikkimk** [comment]
My latest HAX iteration does this.
