### ISSUE TITLE
[elmsln] [hax] UX improvements authoring CMS Token static content in HAX

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#708]
We use static content in the Media site heavily for being able to reuse pages of content across multiple sites.

In the course sites, we would then simply use something like the following `<cms-token token="ciscode|rev=1|tool=elmsmedia|item=7518|entity_type=node|render=value|field=body|delta=0"></cms-token`

When using the HAX Editor I'm able to edit content but it doesn't save back to Media. It's also not able to pick out the individual components of the content as well, but that would make sense as it's being treated as one 'block'.

I'd like to discuss ways that this can be improved for the course author. Initially I think it would be good to display some sort of indication that this is a cms-token to admin and present options for authoring in the media site. This used to be via a 'cog' menu in previous versions of ELMS, so it would be a replacement for this. Perhaps a little more obvious though as the cog menu relied on a mouseover. 
This would then need to be accompanied by HAX Editor being switched on for static content in the Media site.

Longer term, it would be nice for the static content to be editable from within the course site, and then a call made to Media to update afterwards. However, I know that `<cms-token>` is legacy so not sure if this would be considered.

**Comment by btopro** [comment]
Definitely worth discussing how to ease this. I think we'll have to wait for the new UI w/ improved in-block editing support to drop. I believe at one time we were looking at doing `haxProperties` for cms-token's that generated a link in the side panel that said "click to edit complex media" which would open a pop up to the edit form of the node. Then after hitting save, it would close the window and notify the content area that it should refresh the token and display the updated media from the media system.

I believe we had this type of workflow at one point for some types but I'm not seeing it currently in looking for it
