### ISSUE TITLE
[idea] Spelling word library / web components

### ISSUE THREAD

**Issue by AndrewGearhart** [elmsln/issues#725]
A highly useful element (that I've had on a back burner for quite some time ... and would be happy to help implement and might be useful for K-12) would be audio recordings for the purposes of spelling practice. 

Initially:
A word is entered with an audio recording and the user has the opportunity to try spelling it from the pronunciation/audio-recording (then the system compares the actual spelling with the user's spelling). (This could piggy back on the audio recording being discussed in elmsln/elmsln#620 )

Next step:
A record is kept of right/wrong answers and wrong answers are surfaced more frequently than those that the user has gotten right.

**Comment by btopro** [comment]
This would involve
- A singleton that is aware of the flash cards on the page
- HAX wiring for an individual flash card
- a flash card web component that has support for an audio clip of speaking the word
- integration w/ the audio input that can rip directly to mp3

**Comment by btopro** [comment]
#881 group that did this project had support for speaking the answer so that you can then actually type and try to answer by spelling
