### ISSUE TITLE
[video-player] loading too rapidly can cause issues with youtube

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#728]
odd issue we've tracked down where youtube ID doesn't get associated correctly and so if you go to load the media, it's there, but clicking to start it missed the reference and so doesnt know how to interface with the YT API. Either there's an issue w/ the load timing of their API on sites w/ other assets or the video player itself needs to ensure that if it loads in this way / defered / after the page has loaded via visibility / etc, that it still understands how to render and reflect the appropriate YT id throughout. This breaks loading as well as pausing if you are able (at random) to get it to load.

**Comment by btopro** [comment]
There's a hack in place currently so our prod systems are ok but this needs resolved to remove the shim.

**Comment by nikkimk** [comment]
see https://github.com/elmsln/lrnwebcomponents/pull/539
