### ISSUE TITLE
[glossary] Support Glossary of terms type, style, etc

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#731]
Just to kick off ideas on how a course glossary might work. I saw the way that Wikipedia links to other articles in its mobile app and thought it worked really well:

![image](https://cloud.githubusercontent.com/assets/4973810/16987404/ffd70686-4e83-11e6-92f5-7442a68cacc5.png)

Also potentially links with elmsln/elmsln#620

**Comment by btopro** [comment]
#965 would bring a good UX pattern int and HAX has changed hte game on entry from... checks notes.... 2016 when this was opened :)
