### ISSUE TITLE
[a11y] Expansion of Accessible Fallback feature - Mobile Fallback, Print Fallback...

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#734]
Feature request:
The accessible fallback feature is really great. I think this could work really well as a way of loading different media content automatically depending on the context it's being delivered too.

It would work slightly differently in that the media choice would be automatic instead of user-driven.

Mobile fallback and/or tablet fallback could automatically load a different media type based on whether the screen size is small or medium. A use case for this is if something like a H5P presentation is being used and the functionality is compromised when it is scaled down on mobile phones. Maybe you want to load an image instead.

Print fallback would automatically load a different media type if you were printing the course page, or using the Print PDF feature. Zurb has some print visibility classes that I used to use for this purpose (http://foundation.zurb.com/sites/docs/v/5.5.3/components/visibility.html) but it's difficult to maintain and manage via the wysiwyg source code. Use case for this is if you have any type of interactive content (let's say a multiple choice quiz), but you just want some static content loaded instead which loads just the quiz questions. Or you have an embedded video but it makes more sense to display a link to that video instead when printing.

**Comment by btopro** [comment]
#710 starts down this path by at least allowing for printing a single page for the time being and supplying the start of a solution to toggle theme based on the opening of an address with a `?format=print-page` parameter being set
