### ISSUE TITLE
New buttons for the hax-text-editor-toolbar

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#762]
- iconpicker
- inline-image button (for images that are icon sized

**Comment by btopro** [comment]
"that are icon sized" would this also accomodate people wanting to have a 200x300 size image float right within a `p` of text?

**Comment by nikkimk** [comment]
The float right would be better to do a special grid layout. Every time I let people float their own images, then they wonder why the float looks bad if the text doesn't wrap nicely. (I just recently gave someone a float on another project that once they saw how it looked in practice had me undo it.
