### ISSUE TITLE
page navigation not refreshing the page content

### ISSUE THREAD

**Issue by michael-collins** [elmsln/issues#769]
When navigating in elms, the url changes, but the page does not change to match. A page reload fixes it.

In the example image, the page should show the content corresponding to the url, but instead has the previous page.

<img width="1259" alt="Screen Shot 2021-08-10 at 7 39 43 PM" src="https://user-images.githubusercontent.com/1085304/128948675-5c4715ac-7b05-44a7-a787-2f5db41addee.png">

**Comment by btopro** [comment]
while I haven't verified (bc it's hard to replicate this). I believe it's now fixed (and in production). It was discovered that we did the following logic:
- make sure you are logged in
- make sure you are logged in, and are you

With Cosign / webaccess this was fine. Azure fails the 2nd test after about 10-20 minutes as the application is responsible for validation after the initial success. We've changed how we handle this and so it should work now. If this happens again though let me know as it's been very difficult to track down.
