### ISSUE TITLE
[hax] Support for special edit modes.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#773]
In order to do contextual edits in a carousel/galley or a `self-check` we need to either have a special edit mode or a way to display and edit slotted content that is currently offscreen.

**Comment by btopro** [comment]
would this be applied to an individual block? so that we'd have `edit-mode-block-level` and then the active item uses the haxHooks for supplying it's own authoring experience and we drop into this new "mode"? Or would this be like a `self-check-edit-mode` and `gallery-edit-mode`

**Comment by btopro** [comment]
I've seen things that suggest you fixed this :)
