### ISSUE TITLE
installation Haxcms ubuntu 20.04

### ISSUE THREAD

**Issue by yangjun1222** [elmsln/issues#774]
Hi, I want to install Haxcms on ubuntu 20.04, with Docker and ddev, the procedure on (https://haxtheweb.org/documentation-1/haxcms/installation ) is a little different from 
(https://github.com/elmsln/HAXcms), which says  node is needed.(cd system/backend/nodejs
yarn run dev). and in (https://github.com/elmsln/HAXcms/blob/master/scripts/haxcmsme.sh)
, I found that node, yarn, npm, docker, ddev must be installed too.
After I install all these software, I got this:

`yangjun@yangjun-WSPC:~$ cd haxcms
yangjun@yangjun-WSPC:~/haxcms$ ddev start
Starting haxcms... 
An old nginx-site.conf exists at /home/yangjun/haxcms/.ddev/nginx-site.conf. Please move it to ~/.ddev/nginx_full 
Building ddev-ssh-agent 
Recreating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Running   Command=ip address show dev docker0
Building db 
Building web 
Creating ddev-haxcms-db ... done
Creating ddev-haxcms-web ... done
Creating ddev-haxcms-dba ... done
 
Creating ddev-router ... done
 
Project type has no settings paths configured, so not creating settings file. 
Project type has no settings paths configured, so not creating settings file. 
Executing post-start hook... 
=== Running task: Exec command 'sudo a2enmod http2' in container/service 'web', output below 
Enabling module http2.
To activate the new configuration, you need to run:
  service apache2 restart
=== Running task: Exec command 'echo "Protocols h2 http/1.1" > /etc/apache2/conf-available/http2.conf' in container/service 'web', output below 
=== Running task: Exec command 'sudo a2enconf http2' in container/service 'web', output below 
Enabling conf http2.
To activate the new configuration, you need to run:
  service apache2 reload
=== Running task: Exec command 'bash scripts/haxtheweb.sh 'admin' 'admin'' in container/service 'web', output below 
Reinitialized existing Git repository in /var/www/html/_sites/.git/
Reinitialized existing Git repository in /var/www/html/_config/.git/
did nothing, make sure your web server user can write to _sites, _published, _archived

╔✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻╗
║                Welcome to the decentralization.               ║
║                                                               ║
║     H  H      AAA     X   X     CCC      M   M     SSSS       ║
║     H  H     A   A     X X     C   C    M M M M   S           ║
║     HHHH     AAAAA      X      C        M  M  M    SSSS       ║
║     H  H     A   A     X X     C   C    M     M        S      ║
║     H  H     A   A    X   X     CCC     M     M    SSSS       ║
║                                                               ║
╟───────────────────────────────────────────────────────────────╢
║ If you have issues, submit them to                            ║
║   http://github.com/elmsln/haxcms/issues                      ║
╟───────────────────────────────────────────────────────────────╢
║ ✻NOTES✻                                                       ║
║ All changes should be made in the _config/config.php file     ║
║ which has been setup during this install routine              ║
║                                                               ║
╠───────────────────────────────────────────────────────────────╣
║ Use  the following to get started:                            ║
║                                                               ║
║    user name:    admin
║    password:     admin
║                                                               ║
║                        ✻ Ex  Uno Plures ✻                     ║
║                        ✻ From one, Many ✻                     ║
╚✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻✻╝
=== Running task: Exec command 'bash scripts/github-publishing-ssh.sh' in container/service 'web', output below 
=== Running task: Exec command 'echo 'go to http://haxcms.ddev.local - click the top right power button and enter admin / admin to get started!'' in container/service 'web', output below 
go to http://haxcms.ddev.local - click the top right power button and enter admin / admin to get started!
Successfully started haxcms 
Project can be reached at https://haxcms.ddev.site https://127.0.0.1:49154 
yangjun@yangjun-WSPC:~/haxcms$ 

`

I can make a new website using haxcms , I can add new page to it, but some icon won't work.

I just know some PHP, know some concept about docker, so how to set up a haxcms that can work?

**Comment by btopro** [comment]
Hello. We definitely need to clean up the docs and rename some stuff 🤓. Haxcms can run with PHP or NodeJS (beta) backend. So don't need both and PHP is more robust version.

Do you mind sending a screenshot or posting the network errors about missing icons? Sometimes when we do builds of assets we forget to include resources that exist locally. I just fired haxcms up in ddev this morning. The docker configuration should work but I could use more eyes on it for sure.

Thanks for checking us out, I'll take a look at this tomorrow hopefully

**Comment by btopro** [comment]
Sounds like you were able to make a site so that's good.
Ways for us to help debug this:
- We need to split docs out into 2 or 3 sections there it seems. NPM/Node is primarily for developing and testing the assets locally (like builing HAXcms itself). ddev / docker is for local, php based deployment of HAXcms so that you can build websites with it. Was this your understanding or what did you think you had to do?
- Screen shot of the missing icons
- browser / general setup your using

**Comment by yangjun1222** [comment]
Thank you very much. I can make a site, but I can not "edit details",
after I click the icon on the left,(edit details), I got the following :

![Screenshot from 2021-08-13 14-22-51](https://user-images.githubusercontent.com/1796909/129314393-b5fe5135-2aad-4897-addc-6d01399c6ea3.png)
and I notice that "back to the site list" icon is a black hole, and  I can not navigate different web page,
(I can add some new web pages), and I can not edit them.

**Comment by btopro** [comment]
Are you using code from a point release of HAXcms or `master`? I fixed a FF related issue yesterday (and I run Ubuntu 20 as well). We're doing a lot of active development / clean up for a new version actively and hope to have a point release marked early next week, but pull the latest copy of master and you might need to do a super refresh in browser to reflect the new assets.

**Comment by yangjun1222** [comment]
(https://haxtheweb.org/documentation-1/haxcms/installation)
I just clone this repo: git clone https://github.com/elmsln/haxcms.git,
then install docker and ddev, and "open a terminal window, go to the directory and type ddev start"
I do not know what version I am using.  I just learned docker and ddev, 
![image](https://user-images.githubusercontent.com/1796909/129664778-29845744-d174-40d2-8567-bc2aa0376f8d.png)
After ddev start, it displays "Starting haxcms... 
**An old nginx-site.conf exists at /home/yangjun/haxcms/.ddev/nginx-site.conf. Please move it to ~/.ddev/nginx_full** 
Building ddev-ssh-agent ............"
So the version (a point release of HAXcms or master) is determined  by this conf file?

**Comment by btopro** [comment]
When you first go to haxcms.ddev.local and load the wrapper site listing / management panel in the top right corner it says a number in white.

Make sure to pull master if it doesn't say 3.0.0 as I just did a build and release yesterday to fix some UI and other reported issues
