### ISSUE TITLE
[haxcms] site title (browser tab) not refreshing with page

### ISSUE THREAD

**Issue by michael-collins** [elmsln/issues#779]
Maybe related to page refresh issue, I noticed the page title in the browser tab is not refreshing in elms content pages.

**Comment by btopro** [comment]
to clarify you mean the label / title on the tab in the browser bar yes?

**Comment by michael-collins** [comment]
Yes, exactly.

**Comment by btopro** [comment]
@hvk5388 work on this one next now that we have the tooling stuff figured out

**Comment by btopro** [comment]
fixed for next release
