### ISSUE TITLE
[elmsln/hax] HAX editor edit menu should remember which side I previously moved it to

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#791]
Edit menu defaults to the right every time I open HAX editor to edit a page, even if previously moved to the left, which means I have to move it again each time.

**Comment by btopro** [comment]
@hvk5388 this can be after the remembering menu state / current PR your working on. This would involve localStorage and recalling that the user moved the menu to the left (or right) side of the page and then we can apply this setting on spin up of the page.

**Comment by btopro** [comment]
@hvk5388 last PR resolved this so now it'll be correct initially (instances it wasnt) as well as recall where you last placed it
