### ISSUE TITLE
[hax editor] Terminology box pops up if clicked wherever there's a <span>

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#792]
Most of our components wrap the content in a `<span>` tag. We don't have these wired up for in context authoring yet, but when it's clicked on a 'term' box pops up and then this can cause weirdness like content being duplicated

![image](https://user-images.githubusercontent.com/4973810/129974874-4d724d31-8a52-4fca-b34c-99f102b2a0ee.png)

**Comment by btopro** [comment]
Pull master again. We noticed this too earlier this week but I didn't push up Nikkis fix until yesterday afternoon

**Comment by rickhumphries** [comment]
Yep that fixed it
