### ISSUE TITLE
[hax] Can't easily author a table, need editable-table integration

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#793]
Editing a table in HAX editor has issues. Can't seem to write in the cells or create new rows/columns etc. Is `<editable-table>` still a thing?

**Comment by btopro** [comment]
Yeah. It got cut temporarily so we could ship a working build prior to our semester starting but its going to be worked back in shortly

**Comment by btopro** [comment]
Will need to dig in and pick this up. It was in HAX at one point but removed for unknown reasons.

**Comment by btopro** [comment]
added back in in its current state. It has bugs and needs more testing outside of a local test environment but is at least enough to get a conversation started around how to correct the issues it has in changing states. We can take a `table` into `editable-table` mode, need a way of unwrapping the editor successfully when losing focus. This logic is probably in HAX activeEditingElement changing / "core" being set as opposed to another value. At that point we need to
- [ ] see table isn't active / a new element is
- [ ] run some kind of "give me the info as the table requested" function and spit that into the `editable-table` tag's place
- [ ] replace the previous active element (table) with the real thing
- [ ] perform this same thing when requesting HTML (haxHooks need run to clean up editingElements)
- [ ] perform this same thing when hitting save and still active (though solution to above should account for this)
- [ ] include whatever CSS is required to global / base styles to ensure table looks correct in and out of HAX edit state

**Comment by btopro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Table editor in HAX](https://trello.com/c/uu7SRkX8/21-implement-table-editor-in-hax)

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/202024886-50575d6e-6a40-45ef-81f0-7779132b20ea.png)

**Comment by btopro** [comment]
woot!
