### ISSUE TITLE
[hax] Delete buttons have a dropdown on hover to 'confirm' which doesn't feel intuitive

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#795]
The way a confirmation appears when hovering over the delete button doesn't feel like good UX to me. 
![image](https://user-images.githubusercontent.com/4973810/130102026-7a7800e8-f6cd-46bc-bf61-90a76d29298c.png)

It also obscures other buttons so I often click to delete by accident when targeting something else. I'd prefer to just click the icon without the dropdown and then have a small dialog to confirm.

Edit: alternatively, maybe the dropdown should only show on click rather than on hover

**Comment by btopro** [comment]
cough @nikkimk ;)

**Comment by nikkimk** [comment]
Resolved in PR https://github.com/elmsln/lrnwebcomponents/pull/550
