### ISSUE TITLE
[hax] 'Experimental' flag for HAX Blocks (components)

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#796]
There are quite a lot of blocks/components available by default and some work a lot better than others. I know the display of these is determined by what's in a registry so can be removed if needed, but thought the idea of an 'experimental' flag would be good to show the end user that they probably shouldn't use it right now. This also allows the status of the block to be updated later so the end user now knows it's good to go. 

Experimental blocks could be colour coded and only included in the list if a checkbox is ticked or something

**Comment by btopro** [comment]
This is also the default list shipping in elms - https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/settings/shared_settings.php#L12-L59

and in haxcms: https://github.com/elmsln/HAXcms/blob/master/system/boilerplate/systemsetup/config.json#L575-L618

I'm more then ok with this being 2 issues.
1. is to actually do the experimental flag
2. is to have you issue a PR for what you find to be rock solid / worth including by default
3. A list of what needs work

The list of what needs work can then help inform the edtechjoker tag in the queue and provide possible mini-projects for my student teams either to fix the HAX wiring OR to improve the element itself.

**Comment by btopro** [comment]
#993

**Comment by btopro** [comment]
fire branch now has collapses and tagging is exposed. PMP is currently doing an audit on these tags and grouping things. A lot of clean up in what is experimental has happened as a result of this as well
