### ISSUE TITLE
[hax] Issues authoring with <grid-plate>

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#797]
You're probably well aware of this so feel free to close the issue and point to other related issues, but I'm finding it quite difficult working with the grid in the latest hax version. 

I find it difficult to see where the grid boundaries are, which column is 'active', and most of the time I'm not able to drag any blocks/components into the grid columns I need (it only allows me to place them above or below the actual grid).

**Comment by btopro** [comment]
To be on the same page @nikkimk This is after your PR to fix styles.

**Comment by nikkimk** [comment]
Resolved in PR https://github.com/elmsln/lrnwebcomponents/pull/552
