### ISSUE TITLE
[hax] Outline button stalls server

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#801]
Clicking on the "Outline" button in the HAX editor causes the page to become unresponsive. If it's left for too long, it causes the entire server to lock up.

I don't have much info to provide I'm afraid as there aren't any console or PHP/Apache error logs associated. There are just two simple webcomponents on the page (although it's not happening on every page), I can provide the files over Slack if needed but have you seen this sort of issue on your end when using the Outline button?

Is the Outline button just scanning for elements on the page and pulling out the element title or is it doing more than that?

**Comment by btopro** [comment]
clicking the outline button in haxcms you mean it never loads that page? it's just a link over to the outline designer page so I'm not sure what would cause that other than missing icons or something that causes lots of slow loading 404s.

**Comment by JackWillDavis** [comment]
Ah sorry, yeah so it's when you're in the HAX editor on a course page and you click this button:

![image](https://user-images.githubusercontent.com/2301874/130218605-034f710e-992b-4b17-8410-c84d095930fd.png)

The page becomes unresponsive and if it's left it'll freeze up the server.

It does look similar to the previous issue we had when Drupal was freezing up with 404s on icons, and we are using custom icons in those components on page, but they're select boxes and are all accounted for. If you've not seen it on your end then it might be something in our components causing it.

**Comment by btopro** [comment]
Hmm. Server freezes or just the page/browser tab? That's supposed to produce a click through hierarchy of the page you are currently on. Browser your using and does it happen on a simple page?

**Comment by btopro** [comment]
Works on hax.psu.edu when I tried. I'll have to try in elms as well tho it's an identical setup for this button since hax is managing it. Also was this on a haxcms delivered design or a node/123/hax type page?

**Comment by JackWillDavis** [comment]
It's just the page which freezes but if you don't close the tab at the first warning, it'll then stall the entire server. Same as the 404 issue we were having before but it only happens when clicking that Outline button which I assume isn't trying to load any of the custom icons anyway (which are a selectbox dropdown now instead of an autocomplete anyway).

I'm using Chrome (92.0.4515.159) on Win10.

I've just checked and it doesn't happen on a simple page (where there is just a CMS token component with simple text and an image) and it's a `node/123/hax` type page.

**Comment by btopro** [comment]
Hmm ok sounds like the other issue (bizarre). What is getting 404/403s in the network tab if you watch it before and after hitting that button on a big page? Also I think there is a preserve log button in inspector so you don't lose that data when you have to stop the page running

**Comment by btopro** [comment]
can't replicate in current build; let me know when you get your box up to the latest if this is still happening

**Comment by JackWillDavis** [comment]
This isn't happening anymore on the current build so I'm assuming this is sorted now! If it happens again, then I'll have a look again into whether its one of our own webcomponents causing it or, if not, I'll reopen.
