### ISSUE TITLE
[hax] outline panel needs to allow scroll on long pages

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#802]
Might be that I tried on mobile but it won't allow scroll if it overflows the device screen. The search tab works but the blocks tab also has this issue

**Comment by nikkimk** [comment]
Pic or it didn't happen. Can I have some screenshots pls?

**Comment by btopro** [comment]
Phone

**Comment by nikkimk** [comment]
Phones do screenshots.

**Comment by nikkimk** [comment]
Resolved in https://github.com/elmsln/lrnwebcomponents/pull/553
