### ISSUE TITLE
[hax/elmsln] Extending autoloaded webcomponents

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#803]
Hi, happy to make PRs for this one but thought I would check to see whether there is anything in place at the moment before I try anything out. I think there was a conversation about it briefly a while back but not sure if anything has been added in the meantime.

At the moment, on git pull I need to go in and manually add our own webcomponents back into the two `wc-registry.json` files and when pulling a copy of ELMSLN onto a fresh installation, I also need to update the core shared_settings file. It would be great if we could hold these extra components within our own repo (in `config`) so they automatically get added to the autoloader without any manual input.

Is there anything in ELMSLN at the moment that would load an extra `wc-registry.json` file from config?

And, can the `hax_autoload_element_list` [here](https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/settings/shared_settings.php#L12-L59) be extended via our own shared_settings file in config?

**Comment by btopro** [comment]
I'd be all for elms supplying another registry vs direct JS injection. The doc / demo for wc registry I believe does have an example of multiple registries in the lrnwebcomponents repo. Def a good PR there

Redoing that variable could happen in your local shared_settings copy to overwrite what core ships as default for the autoloader variable. That's what we do internal. The initial list is just for there to be SOMETHING 🥳

**Comment by JackWillDavis** [comment]
Ah so for the shared settings, I could just declare the same variable with the same defaults but add our own to the list in the config shared_settings file? Like:

```
$conf['hax_autoload_element_list'] = '{
  "a11y-collapse": "@lrnwebcomponents/a11y-collapse/a11y-collapse.js",
  "a11y-figure": "@lrnwebcomponents/a11y-figure/a11y-figure.js",
  "accent-card": "@lrnwebcomponents/accent-card/accent-card.js",
   ...,
  "custom-element-1": "@example/custom-element-1",
  "custom-element-2": "@example/custom-element-2",
}';
```

That sounds good our end if that would work.

I'll have another look at the wc-registry docs and see if I can sort something out today and test it out.

**Comment by btopro** [comment]
Basically there is support for multiple registries so you should be able to use drupal add js call to add some script that adds yours
