### ISSUE TITLE
[hax] additional scrubbing / state cleaning to do of the body area

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#804]
![Screenshot from 2021-08-20 09-02-00](https://user-images.githubusercontent.com/329735/130237262-58a56b63-6075-44da-979c-9fbeb8e0f7d6.png)

Shown are 2 things of note that should be scrubbed out but were not:
- a rich-text-editor tag. Previously there were regexes that forcibly remove core hax editing tags / anything that declares itself to be part of the authoring experience. This should probably be applied some how to rich text now that it's so much of core usage. `this.haxUIElement` is used elsewhere to help with this though the deep dive of text editing may require specific support for removing these elements now based on your refactor
- css vars / `style="` sorta leave behinds. At some level we need to allow these I know but there are ones like the one pictured that we knowingly can target and remove. If something references a css variable that has --hax or --haxcms in it then it can be safely removed without consequence

The above took place on hax.psu when I edited a bulleted list of items and added a link to the list item via paste. (Chrome obviously)

**Comment by nikkimk** [comment]
resolved in https://github.com/elmsln/lrnwebcomponents/pull/553
