### ISSUE TITLE
[elmsln/hax] <cms-token> stays in edit-mode even after saving

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#806]
I've added a `<cms-token>` (which is a video from our Media site). After saving you can't click to play the video or interact with the transcript because it seems like the `hax-edit-mode` attribute is still there:
![image](https://user-images.githubusercontent.com/4973810/130525994-ee0a5a63-0543-4a8c-beaa-33a0f6f5c15f.png)

Edit: same thing happens when I display a H5P through this method too

On a side note - it's also quite hard to select it when authoring because the 'edit area' is off down the bottom left and doesn't surround the whole frame:

![image](https://user-images.githubusercontent.com/4973810/130526097-5cd3b93f-1624-49c6-b43a-912fef63d7ee.png)

**Comment by btopro** [comment]
`hax-edit-mode` now gets forcibly unset in haxSchema for these so it wont bleed through
