### ISSUE TITLE
[video-player] disappearing fullscreen button

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#810]
In DMD201 you'll see this. `/dmd201/node/247` in our courses.
- Go to the page, should see video and full screen no issue
- click to another page
- come back to this page
- The full screen is gone

I don't know what test your doing for how / if that shows but there's something in the timing of the paint that appears to be influencing the appearance of this button.

**Comment by nikkimk** [comment]
Try https://github.com/elmsln/lrnwebcomponents/pull/558

**Comment by btopro** [comment]
works, thank you
