### ISSUE TITLE
[video-player] Video player seems to be clipping with the editor

### ISSUE THREAD

**Issue by Griffin-Sullivan** [elmsln/issues#814]
I was testing the video-player by turning learning-mode on and off, and when you turn learning-mode on it expands the video since the transcript is turned off. Although part of the video is now visually behind the editor on the right, when you click in the editor it actually clicks the video. So, the video is visually behind the editor, but logically the video is on top somehow. 

I also noticed some tool-tip text when hovering over icons on the right bar were being clipped by the page. The page was on top of the text coming from the right, so we either need to make this text appear on top or have the words align under each other inside the right bar.

**Comment by nikkimk** [comment]
Can you please provide me with some screenshots of this happening? Thanks!

**Comment by Griffin-Sullivan** [comment]
![Screen Shot 2021-08-30 at 2 34 41 PM](https://user-images.githubusercontent.com/48397354/131387935-8041982e-6ae3-4a98-aba3-3bb1b407ce38.png)

**Comment by nikkimk** [comment]
Thanks. The PR in https://github.com/elmsln/lrnwebcomponents/pull/558 should resolve this.

**Comment by btopro** [comment]
confirmed this is resolved via that PR; ty Nikki
