### ISSUE TITLE
the navigation arror on content page do not work 

### ISSUE THREAD

**Issue by yangjun1222** [elmsln/issues#815]
I added several pages, when edited, the content on the right page won't change with the menu (after clicking the navigation menu bar, the title in the browser address changes, but the content page always shows the first page. the navigation arrows (in the left and right side of content page   <  and >, left is grey and right is black )won't work,  so I can ONLY edit the first web page.

**Comment by btopro** [comment]
which theme?
what version of haxcms?
What browser?
have you gone back to haxcms.ddev.local and logged out and back in / verify that you are logged in?

**Comment by yangjun1222** [comment]
I chose the Course theme, which might be the problem. I  built another test website with a different theme, it works fine.

**Comment by btopro** [comment]
Shouldn't be as we run that in production. Make sure you have the latest version of haxcms code base and then open network panel in inspector and check disable cache. Then refresh site with th course theme and see if it works
