### ISSUE TITLE
how to use hp5 component?

### ISSUE THREAD

**Issue by yangjun1222** [elmsln/issues#816]
In add blocks, there is a H5P blocks, or H5P element. Is it possible to use other H5P elements?
I am very interested in this example [fill-in-the-blanks](https://h5p.org/fill-in-the-blanks).
Thanks!

**Comment by btopro** [comment]
Your able to use the h5p element with an environment that already could produce h5p like drupal or WordPress. We unfortunately don't have direct editing support of h5p files since it requires a full PHP cms integration to work. @cgldevel might know their workflow for using that tag or if they do.
