### ISSUE TITLE
[term-glossary] Vocab presentation based on user adding to a page

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#849]
> for btopro only; Nikki brought up the idea of a fly out that identifies words in the page but instead of constantly applying the
> vocab-term in context, it instead shows them in a flyout of words that appear in this page with a count #
> This is also in keeping with performance as this way it can late load since it's not critical

Because we have #848 that means we have some options for how best to present a vocabulary term in context of material. What we need now is a microservice that can draw from a data store of words, have words added to it, return ALL the words (as 1 big list if asked) and also identify words in text so that it could automatically apply the vocab term tag to it.

## Requirements for back end
- Build a microservice that stores and processes vocabulary terms
- POST / READ This service can be passed a text / HTML string of text, identify words that match the glossary
- POST / CREATE needs to be able to take word, textual definition, and any links desired
- GET / READ needs to accept a parameter for returning 1 term / definition or ALL
- Pervasive data store in a jsonbin.io or actual data store of your choice

## Requirements for front end
- Create a demo page / space that has the ability to add new words to the glossary via a small form `POST`
- The ability to hit a button and present all words in the glossary with their definitions via a `dl` tag (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)
- The ability to take a block of HTML on the page and send off to the microservice for processing.
- The front end needs to then get the words that match, find them in the text of the HTML, and then automatically apply a `vocab-term` tag (https://www.npmjs.com/package/@lrnwebcomponents/vocab-term) which when clicking the word, would show the definition positioned near it.
- Demo should include an area where the user can type text and hit "process" and it augments the typed text, presenting matches for the vocab word in context

example implementation in the vocab-term tag for visualizing the definition and putting it in a modal
```html
<vocab-term>
  <details>
    <summary>Coffee</summary>
    <p slot="information">Bean juice made into warm beverage.</p>
    <ul class="links">
      <li><a href="https://www.starbucks.com/">Link to starbucks information</a></li>
    </ul>
  </details>
</vocab-term>
```
This example will show the word coffee and when clicked, it'll show it in a modal

**Comment by RyanArmani** [comment]
Group B Selected this object

**Comment by btopro** [comment]
https://github.com/briangan123/term-glossary

**Comment by btopro** [comment]
fixed w/ microservices!
