### ISSUE TITLE
Mammoth .DOCX converter // HTML Page Display as Web Component

### ISSUE THREAD

**Issue by beb5040** [elmsln/issues#856]
It would be nice to have a windowed display for uploaded word docs that could concisely keep open source or CC licensed documents or manuals available in context on page. If they could be rendered as accessible within relevant page content instead including it as paged content or exclusively as a download that would be ideal both for student course navigation, but also as note taking and publishing tool. 

The best case scenario for this would be either a link that could be expanded into the window or have the window turned on directly. 

Conceivable uses for this would also include : linking relevant research considerations or papers, included course reserves or readings without having to deviate from course pages significantly. Would remove a lot of the bad photocopied scans that perpetuate a lot of readings and would find use as an external tool beyond just in HAX directly.

**Comment by btopro** [comment]
I think we're on the same page about recalling data and what not. If you want something to be kept as a file though it's an upload. I don't think we're in the business of forcibly fixing files for presentation purposes. If you want to import the contents of a file into the page this is now going to be in the next release. If you want to export a page to Docx this is also possible and we'll be adding prominence in the UI at a later date.

**Comment by btopro** [comment]
fixed w/ microservices!
