### ISSUE TITLE
Full page source editor

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#867]
I think it's a recent change that clicking the full page source now opens in a smaller side window rather than being full page. I have to admit I really liked that it was full page as it was so much easier to read and manage. 
Thought a good idea would be to have  a little 'full screen' toggle button that could make this take up the full page again:

![image](https://user-images.githubusercontent.com/4973810/137457333-e456b409-95cd-4100-9cfa-26c658ae9061.png)

**Comment by btopro** [comment]
This is a regression @nikkimk and I noticed recently

**Comment by btopro** [comment]
fixed in latest
