### ISSUE TITLE
[elmsln] Move change section function in ELMS:LN header closer to the section title.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#87]
The change section function is currently grouped with the avatar. It should be grouped with the section.
[studio-notes.pdf](https://github.com/elmsln/issues/files/4256321/studio-notes.pdf)

**Comment by btopro** [comment]
aren't you just burning the studio down and changing it?

**Comment by nikkimk** [comment]
These are changes from Ben's email and mockups. I'm breaking them down into individual issues.

**Comment by btopro** [comment]
new UI option makes this all in one place
