### ISSUE TITLE
[sorting-question] A question that requires the user sort the possible options

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#872]
https://h5p.org/content-types/sort-the-paragraphs is the comp to go off of.

Requirements:
- Web component must allow for sorting a list
- statements are singular lines in an `Array` which uses `map` in order to write into the page
- haxProperties for the array of items can be added so users can add new items (see `@lrnwebcomponents/multiple-choice` for examples)
- must be drag and drop as well as up / down arrow capable
- CSS for showcasing right and wrong answers
- Should support progressive enhancement / reading options in from slotted material (this way it can have a demo as well)
- Need to be able to check answer
- Need a way of showing the "correct" order either via right/wrong css (like they do) or placing a number next to each one that demonstrates the right order, only visible when checking the answer
- Need to disable the "click to test words" when HAX is activated (+1 bonus, this is not easy and requires haxHooks which is an advanced part of the spec. Do this last)

**Comment by NGyaBoi** [comment]
Viable Slime: Neel, Michael, Sean, and Nick H

**Comment by ejm5763** [comment]
Group F: Liz, Liam, Julian preference 2

**Comment by nro337** [comment]
Table in the Corner: This is our preference 1

**Comment by ksanroman** [comment]
Group 1: Mike, Karina, Frank and Hailey

**Comment by btopro** [comment]
#1477
