### ISSUE TITLE
[elmsln/haxcms] Page with multiple cms shortcode tokens doesn't render them all

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#878]
If a course page has many tokens on it linking to media content then not all of them will display. 

> It's possible the client-side handshakes are getting screwed up because there's too many being initiated
(Ollendyke, 2021)

We tried to replace the `_mooc_content_render_content` function in `mooc-content.php` to this which attempts to replicate the way haxcms does rendering now server-side (think I've translated that convo correctly!):
```
/**
 * Render content; stinking weird but basically the entire page.tpl.php
 */
function _mooc_content_render_content() {
  $node = _mooc_content_get_active();
  $content = '';
  // support for banner block
  if (isset($node->body) && !empty($node->body['und'][0]['value'])) {
    if (module_exists('mooc_content_theming')) {
      $content .= _mooc_content_theming_banner_block($node);
    }
    drupal_alter("haxcms_node_content_response", $node->body);
    $content_ary = node_view($node);
    // ax contextual links as we don't use this paradigm :)
    unset($content_ary['#contextual_links']);
    $content .= drupal_render($content_ary);
  }
  else {
    // try to skip to the next item if they don't have edit rights
    $next = book_next($node->book);
    // ensure we have a next item and it's in this one
    if ($next && $node->book['mlid'] == $next['plid']) {
      if (entity_access('update', 'node', $node)) {
        $node->body = array(
          'und' => array(
            0 => array(
              'value' => '<div class="black-text"><em>' . t('This page is empty, so students will automatically be taken to the next page. You have not been redirected so you can edit this content if desired.') . '</em></div>',
              'format' => 'textbook_editor',
            ),
          ),
        );
        $content .= drupal_render(node_view($node));
      }
      else {
      // if the user is a standard user then take them to the next book page
        $content = array(
          'redirect' => base_path() . $next['link_path'],
        );
      }
    }
    else {
      if (module_exists('mooc_content_theming')) {
        $content .= _mooc_content_theming_banner_block($node);
      }
      drupal_alter("haxcms_node_content_response", $node->body);
      $content .= drupal_render(node_view($node));
    }
  }
  return $content;
}
```
However, this didn't have any impact unfortunately.
What does help though is creating a single piece of static content in Media that includes all the html/shortcodes etc. and using that single shortcode on the course page. Must be something about the Media site being able to render everything ahead of time that helps w/ it.

**Comment by rickhumphries** [comment]
Update - the server-side rendering mentioned above does in fact work and we've managed to deploy this successfully. There **is ** still a limit to the nuber of cms-tokens you can include on a page however but we've managed to work around this by breaking certain pages up etc. so it's no longer an issue necessarily
@JackWillDavis - is there anything you wanted to submit a PR for on this or has this already been done?

**Comment by btopro** [comment]
What's the limit for reference?

**Comment by rickhumphries** [comment]
Seemed to be around 15

**Comment by JackWillDavis** [comment]
Nothing for us to PR for this one I think unless you wanted me to put one in to update the code block above @btopro?

**Comment by btopro** [comment]
if the above helped you then yes please do. We officially do not use `mooc-content` for delivering any course content as of like 2 weeks ago so I don't want to have you guys diverging on patches and things to ensure that it's a working part of our platform.
