### ISSUE TITLE
[post-card] Make a remixable post card for hax

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#879]
https://remixer.visualthinkery.com/a/OEG-postcard using this as a comp, create a fully functional, HAX capable version of this asset. HAX has the ability to edit values in place much like our storybook knobs. This project involves:
- Creating 1 fully documented variation per team member (3 teammates == 3 post cards implemented in the demo)
- haxProperties wiring with working boilerplate demo
- variables for images and any textual aspects which are variable
- SVG based assets can be taken from the project itself or generated by the team via CSS / images / other methods
- internationalization integration via i18n mixin
- scaled down proportionally for mobile (their version appears to just scale as you drag in, possibly using css scale or SVG capabilites)
- Should support slots to improve progressive enhancement

The general requirements for all project 3 submissions also must be met and requirements are to be gathered by asking questions and in class activities to tease out full requirements.

This work is based on https://creativecommons.org/licenses/by-sa/4.0/?ref=fahim.pages.dev so a reference in the comments as to where this came from is best practice.

**Comment by francescaansell** [comment]
3b4b doing this

**Comment by JT-aa** [comment]
jingtao and yue 2nd choice

**Comment by btopro** [comment]
This will be published to npm on tuesday as part of (a new class) showing how to get and reuse assets from other places. This was 1 of 3 elements that will be making its way into our production product in the coming weeks and only 3/11 will be making it in. https://github.com/elmsln/lrnwebcomponents/blob/master/elements/post-card/src/post-card.js#L7-L11 comment left for prosperity. Good work you all this took me all of 10 minutes to get into a state that it's worth other people seeing / possibly using.

**Comment by btopro** [comment]
last commit added this w/ better defaults and some a11y clean up. it'll be in the next release. Congrats gang, you are the 1st edtechjoker graduates to get published. Hopefully we'll use this in some history classes, I still gotta pitch it to people as being available and maybe clean up some more from there.
