### ISSUE TITLE
Header menu in ELMS:LN should be text instead of icons

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#88]
[studio-notes.pdf](https://github.com/elmsln/issues/files/4256314/studio-notes.pdf)
> How about a big button that
says “STUDIO” and another
one that says “CANVAS?”
I bet most students don’t
rely on these specific links
for finding stuff on Canvas,
and I think minimizing UI
elements will help make
everything easier to use.

**Comment by btopro** [comment]
That reads more like "remove these links they are unused". It also screams performing a real UX audit w/ students. Maybe these are things we could run through in EdTechJoker when you (I'm hoping here) come in to speak to my class again :)

**Comment by btopro** [comment]
these are getting absorbed into our haxcms theme layer so cutting this as it's legacy anyway
