### ISSUE TITLE
[trading-card] Trading cards are awesome, let's make some

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#880]
https://remixer.visualthinkery.com/a/toptrump - using this as a comp, create a fully functional, HAX capable version of this asset. HAX has the ability to edit values in place much like our storybook knobs. This project involves:

- Creating 1 fully documented variation per team member (3 teammates == 3 trading cards implemented in the demo)
- haxProperties wiring with working boilerplate demo
- variables for images and any textual aspects which are variable
- color input for border / primary color needed
- this design can be made inaccessible; so simple-colors is needed in order to ensure that color contrast ratios can be maintained between text color and the background color that renders the spaces
- Each line should also optionally support an icon from the simple-icons library
- slots should be available for custom implementation
- Demo must include an implementation of rendering cards by running through a `map` function in order to stamp data from an array into the cards.
- scaled down proportionally for mobile (their version appears to just scale as you drag in, possibly using css scale or SVG capabilities)
- Bonus: Add support for flipping the card over / having a "back" to the card +2 (this would have support for an icon / text / image that is the "back" of the card and then a state change for which side the card is to display)

This work is based on https://creativecommons.org/licenses/by-sa/4.0/?ref=fahim.pages.dev so a reference in the comments as to where this came from is best practice.

**Comment by JT-aa** [comment]
jingtao and yue

**Comment by haileyhahnnnn** [comment]
IST204group1: Hailey, frank, mike, Karina

**Comment by kxm5816** [comment]
PaddysHub: Khory, Andrew, Perry, Ethan
