### ISSUE TITLE
[flash-card] create a flash card for practicing comprehension in material

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#881]
https://h5p.org/flashcards#example=733 - This issue is to produce 1 card. Not the sliding interaction. This card should have a correct answer and input for the user to guess what the answer is. On checking their answer it should tell them if they got it right or wrong. It should not be case sensitive.
Detailed requirements
- Support for an image / slotted area of flexible content, question being asked, right answer, ability to change color
- i18n support so that labels in element are translatable
- Demo must have multiple flash cards listed on it and load data in from a JSON blob using `.map` function to print out multiples
- Should work with or without an image; this could also be slotted material so that it can be anything
- visually should look very similar to this interaction
- Must visualize state for correct and incorrect
- This comp does not have a button for "try again" but needs one for accessibility
- **Bonus: Create the sliding interaction / a wrapper element called `flash-card-list` which the `flash-card`'s talk to in order to know which card you are currently engaging with (like 2 of 10). Then as you check for an answer it'll flip over, show you right or wrong, but then progress to the next card just like the comp. +2 bonus**

**Comment by hvk5388** [comment]
Koding Krab is doing this one: Hannah, Taylor, Evan, Colton

**Comment by JAlbert2** [comment]
PennStat is the second group. Jonah, Griffin, Elizabeth, Pooja

**Comment by spb5732** [comment]
Viable Slime: if these two groups are not picked for this^

**Comment by ejm5763** [comment]
Group F: Liz, Liam, Julian 1st preference

**Comment by haileyhahnnnn** [comment]
IST Group 1: Mike, Hailey, Katrina, Frank

**Comment by btopro** [comment]
integrated
