### ISSUE TITLE
[mark-the-words] Marking defined words in a text area

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#882]
https://h5p.org/mark-the-words - This provides an activity for identifying parts of a sentence as relevant / important to the topic at hand. In the example it asks to mark what words are types of berries. This element has only a little styling but is one of the more complex data driven options.

- Must be able to write content / be slotted in as far as what is selectable
- Click handler that detects the text node / word clicked and then wraps it in a tag
- Checking answers then queries for this tag to see if it matches a predefined list of answers
- variables for question to ask, number correct / incorrect, and the answer (a String that is `,` comma delimited)
- Showing solutions are important states
- Need to visualize correct / incorrect in context based on if the word selected matches or not
- need to be able to "reset" to try it again
- Need class applied to slotted content (or an element that acts like a span) for correct and incorrect
- Need an element for the button and state change so that we can check the answer
- Need to disable the "click to test words" when HAX is activated (+1 bonus, this is not easy and requires `haxHooks` which is an advanced part of the spec. Do this last)

**Comment by jmgiannetti** [comment]
Group F Liam, Julian, and Liz

**Comment by andrewtheiller37** [comment]
Paddys Hub - Andrew, Perry, Ethan, Khory

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/232910596-441f6863-d8fd-49ad-a41f-c0d9e1c5253a.png)
