### ISSUE TITLE
long message when moving stuff around in and out of stop note 

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#884]
I also tried to make a H2 tag go from body into the stop-note which generated a bunch of this. Also I hit save. I think simple-fields-combo has some default window stuff firing even if it's not in focus. which triggered that but I could be wrong.

Rebase to master bc I've merged BOTH our work into it :) and then you'll have to yarn install bc it's got a lot of tooling enhancements (hax loads a lot faster locally and fixed other random things)

![image](https://user-images.githubusercontent.com/329735/141203950-bb93a782-1358-4f12-8c22-c8a7ddf3f367.png)

**Comment by nikkimk** [comment]
Unable to replicate in latest updates to master
