### ISSUE TITLE
[haxcms-blank-theme] Create true blank theme

### ISSUE THREAD

**Issue by cgldevel** [elmsln/issues#888]
hascms-blank-theme is not truly blank - it includes a 'print' button and the 'creative commons' footer at the bottom.   Maybe we should consider creating an haxcms-ultra-blank-theme that contains no other elements (just an open slot) - or maybe, we add some CSS variables to haxcms-blank-theme so those items can be hidden.

**Comment by btopro** [comment]
should be good in master
