### ISSUE TITLE
[elmsln] Warning messages with outline designer in Drupal

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#893]
![image](https://user-images.githubusercontent.com/4973810/143250165-0ecb3358-d276-4e76-8bc2-d3bee9d7fbb6.png)

**Comment by rickhumphries** [comment]
Also get this error when adding pages. It still adds the page in though:

![image](https://user-images.githubusercontent.com/4973810/148082744-854659ae-6bd5-41da-9a30-dc55774909ce.png)

**Comment by btopro** [comment]
check logs; no issues here as to adding pages though we may be squashing notices or something from output which would malform the JSON response.

**Comment by btopro** [comment]
searched and... my issue queue comes up... 

https://www.drupal.org/project/outline_designer/issues/2930286

we had the fix just not applied apparently :)
