### ISSUE TITLE
CMS Token Cache Issue?

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#912]
We're getting a lot of calls through to our service desk reporting pages or resources that don't load and just displays a loading spinner:
![image](https://user-images.githubusercontent.com/4973810/145198501-70ff62e1-c980-41d7-8d72-c3d1d3258573.png)

On looking at the console there are errors retrieving the resource:

![image](https://user-images.githubusercontent.com/4973810/145198587-85a7a05f-5a30-4af2-b747-2884ba34f5ac.png)
or
![image](https://user-images.githubusercontent.com/4973810/145198633-92a98134-2583-49d2-a519-afed5c478188.png)

The resource it's looking for will be a link like this:
`https://courses.mydomain.co.uk/pttp/webcomponents/cms-token/FQva7n_v8zPvg3WKnVkKtsbYoXqTj5Q4K5J4HTdzzSo/?token=%5Bciscode%7Crev%3D1%7Ctool%3Delmsmedia%7Citem%3D9139%7Centity_type%3Dnode%7Crender%3Ddisplay_mode%7Cdisplay_mode%3Dh5p%5D&cachedResponse=false`

This has happened to me too sporadically and the issue can be fixed by clearing the browser cache each time, but we're also getting some reports that this isn't working for some learners (although they may just not be clearing their cache properly when they say they have). 

I seem to be able to replicate it in two ways:
1. Accessing a course site as one user, logging out and logging into the same course as a different user
2. Accessing course content, then accessing pages that open in a new tab (these pages are part of the course site but not associated with the book outline). Then trying to navigate around the course outline in the newly opened tab (navigating around in the original tab is fine though!)

**Comment by btopro** [comment]
if you seed the caches on the site via drush w/ a `drush @courses.pttp cc all && drush @courses.pttp ecl` is there any change? I'm not sure why there would be requess to `webcomponents/cms-token` bc it's not a valid path and would expect to 404 in my mind. The path would look more like `pttp/cms-token/BIGLONGTHING/?WHATITSTRYINGTOGET`

Might need more detail as to where the `webcomponents/` is coming into play here or if maybe you have other rewrites that are influencing it. We've switched off the lazy load assets to remote / back end rendering to avoid some issues of things like this not loading but they weren't 404'ing (bad path) they were 500'ing at the time (failed request)

**Comment by btopro** [comment]
ignore my message about `webcomponents/` I was apparently not awake yet. the edited comment is accurate

**Comment by rickhumphries** [comment]
duplicate of #918
