### ISSUE TITLE
Replacing CKEditor on Legacy Edit Page

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#915]
The only reason we would use the legacy edit page is because we have additional options in there that we need to configure like instructional significance, visibility, or our own custom 'module dependency' field which is linked to our module unlocking feature.

However, even if we don't touch CKEditor at all, if we need to change any of those settings and then save the page, CKEditor will seriously mess up the content by throwing `<span>`s and `<p>`s everywhere and even throwing content out of components too.

I think it's agreed that no one actually uses CKEditor anymore and the 'source mode' in HAX is so much better anyway. Does the Textbook text format rely on CKEditor at all, or can another editor just be switched in? Thinking that might be easier than trying to configure CKEditor to not mess with things.

**Comment by btopro** [comment]
textbook I BELIEVE is tied to CKEditor tho it can be disabled / changed via features

**Comment by rickhumphries** [comment]
Yes we do have one custom field which is the module dependency to unlock pages based on learner progress: 
![image](https://user-images.githubusercontent.com/4973810/146099909-b0fc5db0-1edd-4157-87af-60c32b263ae8.png)

That's the only one though, so we can look to move this over to haxcms in the future. 

Since textbook is tied to CKEditor it's potentially a bit too tricky to unpick it. The main reformatting issue we think is CKEditor's dislike of wrapping inline elements around block level elements (which is an issue because components needs a `<span>` tag to wrap content) so @JackWillDavis got around this by adding an exception for span tags wrapping all block elements. He'll add a PR for it soon

**Comment by btopro** [comment]
PR accepted
