### ISSUE TITLE
Creating a link with inline editor isn't working

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#924]
https://recordit.co/mbuLlWpq5t

**Comment by btopro** [comment]
"something that could have been brought to my attention... YESTERDAY"

Funny, we just got this report internally. We are running master and will keep updating as we bug squash things like this.

**Comment by nikkimk** [comment]
Should be resolved now in this request: https://github.com/elmsln/lrnwebcomponents/pull/593

**Comment by btopro** [comment]
doing a build now; it'll be pushed up soon. thank you @nikkimk
