### ISSUE TITLE
[ELMS/Media] Reinstate a way of providing shortcode option to 'just the image'

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#934]
Previously there was a way to retrieve the 'token' for this which was an iframe of the rendered image field along the lines of:
`ciscode|render=link|display_mode=iframe|item_type=image|entity_type=node|rev=1|tool=elmsmedia|item=#|field=field_image|delta=0`
This just allows the displaying of an image 'as is' without the dotted lines beneath. Other option is to just provide a display mode that just gives the image.

Wondered if this might just be a HAX configurable thing in the future, so the component is just pointing to the resource and then you choose how you want to display it in the authoring pane.

**Comment by btopro** [comment]
an iframe of an image as opposed to just rendering the image stand alone you mean?

**Comment by rickhumphries** [comment]
Well, rendering the image standalone probably makes more sense. I'm just including the token above as this is what was generated for us to use before in the past (I think there was some sort of 'share' button on the media site)

**Comment by btopro** [comment]
See if you got edit if the share button shows up. We still have share so I think you Are saying they are not visible as opposed to not working yes?
