### ISSUE TITLE
[HAX] Performance degradation when authoring large pages of content

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#935]
Not sure if this points to a memory leak of some kind but we've found that if we're authoring a page with a lot of content on it, if the author has been working on it for a while then everything slows down completely and becomes very laggy in it's responsiveness.

**Comment by btopro** [comment]
this is still while at a `node/123/hax` path yes? This isn't surprising given the sheer weight of ELMS:LN / Drupal's jQuery nest of vipers. HAX isn't a small baby either but consider that HAX running in HAXcms is going to be significantly lighterweight then system + full additional system sorta weight.

I'm not entirely sure what's "do-able" about this however we've had success w/ putting content editing into an admin theme bc the foundation access theme has so much JS / CSS that it doesn't help. HAX will continue to get lighter over time through low level performance optimization but if you have a specific leak you can trace as far as what specific action is leaky we'd look into it. Mutation Observers drive a lot of what's going on w/ HAX and they can add up on very large pages for sure.

**Comment by btopro** [comment]
several landmine memory leaks were fixed in the new release.
