### ISSUE TITLE
[cloogs] envision what data needs to be available in the store and constraints

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#949]
@liljimmyk99 your in charge of the store and working on some initial routing things for if the user would reload the page / change steps / etc
- [ ] what properties we need in the store
- [ ] Do we have an element that's like `hax-app-step` which then has a title, slot for material on the step, etc?
- [ ] How do we define constrains as far as when to change step / what can activate a step change
- [ ] How do we disable scrolling yet leverage the scrolling container in the current example to ensure a smooth, snapping transition
- [ ] How do we establish initial state so that "nothing" is effectively step-1

**Comment by liljimmyk99** [comment]
### How do we establish initial state?

In the constructor of the HAXCMSApp, we would check local storage for information about the current step and information about it.  If there is none or there is an issue with the data, we would default to step 1.

**Comment by liljimmyk99** [comment]
### How do we disable scrolling yet leverage the scrolling container in the current example to ensure a smooth, snapping transition

Removed the following css variables from `scrollable-component` properties
**-           --content-padding: 0 0 25px 0;
-           --content-row-height: 100%;
-           --viewport-scroll-snap-type: x mandatory;**

**Comment by liljimmyk99** [comment]
### what properties we need in the store

https://github.com/elmsln/haxcms-user-flow/issues/11
