### ISSUE TITLE
[haxcamp] CLI

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#953]
Make a simple CLI that you can get info from a web service (json based backend or something in the gitrepo). Why? cause it's cool, different, fun.
- [ ] need an ascii art for it
- [ ] need a name
- [ ] use JSON sitting in site git repo as the "backend" so it's a good example of headless architecture (can then present at the event too)
- [ ] Need to know what data to share via the CLI, options for when camp is, where it is, things like that
- [ ] 1 line install / to call it up much like 1-line installers

**Comment by mayormaier** [comment]
I plan to work on this tomorrow.

What do we think about `campfire` as a potential application name?

**Comment by btopro** [comment]
Fire would work. Elmsln CLI is leafy, HAXcms CLI is haxy. Something short

**Comment by lizblake** [comment]
so should the art be a fire or like a hax camp logo

**Comment by mayormaier** [comment]
> so should the art be a fire or like a hax camp logo

I was thinking like a fire with the characters around it

**Comment by btopro** [comment]
ASCII of HAX w. A fire below it maybe. Something readable but not overly complex

**Comment by btopro** [comment]
Here's a very simple example from haxcms installer https://github.com/elmsln/HAXcms/blob/master/scripts/haxtheweb.sh#L143

**Comment by btopro** [comment]
https://patorjk.com/software/taag/#p=display&f=Isometric1&t=HAX%20the%20web there's also cool services like this to get an idea

**Comment by mayormaier** [comment]
Sweet- I've been using figlet so far in my prototypes. The CLI is a work in progress now, hopefully I will have code to push Tuesday/Wednesday. 

Can we make a elmsln/campfire repo for this and get some CI into an npm package? My idea is to make a node executible for people to run with npx

**Comment by btopro** [comment]
Sounds good. Admin on it https://github.com/elmsln/campfire

**Comment by btopro** [comment]
This can be a gateway to our events and installing our other projects easily too

**Comment by lizblake** [comment]
I just learned you can do colors in ascii art....
working on a bash script
