### ISSUE TITLE
[elmsln] Hardcoded timeouts causing content to go missing

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#956]
In ELMSLN v1.2.1, there are some hardcoded timeouts written into cis_filter which is causing issues with content loading on some of our course sites. Currently the timeout is set to 250ms which isn't enough time for some of our content to return and results in a blank response from Media.

Would it be possible to remove this timeout from cis_filter or to allow it to be set as a installation-specific value in shared_settings so that we can easily control the limit?

Here are the timeouts:

[cis_filter timeout 1](https://github.com/elmsln/elmsln/blob/1.2.1/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/cis_filter.module#L258)
[cis_filter timeout 2](https://github.com/elmsln/elmsln/blob/1.2.1/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/cis_filter.module#L291)
[cis_filter timeout 3](https://github.com/elmsln/elmsln/blob/1.2.1/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/cis_filter.module#L723)

**Comment by btopro** [comment]
hmm... yeah these definitely should be higher as they are delivering content. Bc of how our system delivery has changed, this can absolutely be higher. It should still be within reason though. When rear-delivered / pre-rendered, this was going to hold up the entire site being delivered. Now that it's ajax driven, something more like 5s is probably more appropriate. It would cause an individual page to chug for sure, but it would allow enough time for items to all come through and render.

I'd make a shared_settings setting of like 5000 and then if you needed to override it then you could in your local shared_settings file.  Sound reasonable for a PR?

**Comment by JackWillDavis** [comment]
Yeah 5000 should be plenty, we've got ours set to 2500 currently and it's sorted the issue we were having. I'll put a PR through for it.

**Comment by btopro** [comment]
merged
