### ISSUE TITLE
[haxcms] Cycling Messages for Returning Users

### ISSUE THREAD

**Issue by elizabeth-delor** [elmsln/issues#957]
The best way I can describe this is the Minecraft opening page where every time a returning user opens it, there is a new welcome message each time a user joins. 
Ex:
![image](https://user-images.githubusercontent.com/74112413/155394763-6b5b46a5-1ee3-4d78-9477-404bd89addb7.png)
![image](https://user-images.githubusercontent.com/74112413/155394786-19d96028-eb9f-4853-89d7-3cff7a52dbe2.png)

Examples of what it will say on the HAXCMS site would be:
- You're Back!!
- The Journey Continues
- Oh You're Here...
- Uh ohhh back again

etc etc. Have fun with it and add more if you think of any funny openings.

**Comment by btopro** [comment]
@liljimmyk99 @dronk6 don't care which of you pick this up but idea is a simple element / snippet of JS that automatically picks a statement at random from an array of possible values
