### ISSUE TITLE
[threaded-discussion] Smart block to embed discussions into anything

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#960]
Discussion board, hax-discussion smart block could be only thing on a page (so a discussion board). Also would need another aggregate / list view for all discussions. Discussions added in context, this page generated automatically

## Goals
- Create a completely headless discussion widget that is able to save and recall the conversation
- Ability for user to embed in a page and it automatically generate a UUID if one is not supplied
- Use `@lrnwebcomponents/threaded-discussion` and it's data model requirement (or making a new one for each)
- Going for a "Disqus" / drop in and use anywhere style commenting engine. Your demo can have multiples on the same page / app in order to illustrate this capability (if it works with multiple UUIDs in the same page that would indicate that it's flexible to handle multiple conversations on different end points)

## Requirements for back end
- POST / CREATE Ask for a UUID to be created which creates a data storage area for this
- POST / CREATE Add a new comment to a thread
- POST / UPDATE edit a comment's content
- DELETE / DELETE delete a comment
- Ability to store multiple threads; one per UUID
- Pervasive data store in a jsonbin.io or actual data store of your choice
- Validation of the domain -> UUID -> route as a way of verifying this discussion can be embedded / loaded here

## Requirements for front end
- If no UUID on front end, needs to ask backend for one
- A simple "whats your name" `input` so that they can set their user name in localStorage on the front end
  - obviously in a production environment we'd be doing this via a larger system concept / JWT / something to validate. We're not handling that outright as this is a demo
- wiring up to the threaded-discussion tag and handling it's events to add new comments
- wiring up to a highly simplified / reddit style list view which then has reply, edit, and delete operations off to the side for easy testing and verification of it all working (again, obviously in a prod environment it wouldn't have this but demonstrates the flexibility of how to render and the headless nature of the calls to the backend working agnostic of UI)

![image](https://user-images.githubusercontent.com/329735/158408678-b075cf93-8c8d-4e14-8e8f-8aa934814712.png)

**Comment by mayormaier** [comment]
da-penguins @liljimmyk99 @elizabeth-delor @Taylor-Bracone @dronk6 @hvk5388 is working on this

**Comment by btopro** [comment]
https://da-penguins.stoplight.io/docs/threaded-discussion/b3A6NTAwNDMzNzA-get-comment
https://da-penguins.github.io/threaded-discussion-docs/posts/notes/
https://threaded-discussion.vercel.app/
https://github.com/liljimmyk99/threaded-discussion
