### ISSUE TITLE
[elmsln] Issue preventing course creation in ELMSLN

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#966]
As discussed with @btopro on Friday 18th March over Slack.

There is an issue which prevents the creation of course sites via command line or via the CIS Quick Setup process on ELMSLN v1.2.1. The barebones Drupal site is installed with a `placeholder-for-uid-1` account but the mooc profile isn't installed at all.

![image](https://user-images.githubusercontent.com/2301874/159252025-cb9d0175-3d86-40cd-95c4-d5fb766b42e6.png)

The elmslndbo config details seem to be properly sourced. If I'm logged in as the `ulmusdrush` I can log into mysql on the command line for the elmslndbo superuser but I can't for the course `bhive101` mysql user account.

@btopro suggested that the issue could be a PHP 7x compatibility issue which would explain why the site partially completes but only the base and nothing else. I've included a few of the log/job files from the course creation to record here. Let me know if you need any more info for this or want me to test anything.

Example Job file:

![image](https://user-images.githubusercontent.com/2301874/159253124-1c9ba425-f1ce-4609-aa8f-037ee32cbed2.png)

Example Log file:

![image](https://user-images.githubusercontent.com/2301874/159253299-2e372716-5cfd-438e-83e7-40844125444e.png)

**Comment by btopro** [comment]
actually that fixed it and I was just able to make a course. I love it when its simple stuff.

**Comment by btopro** [comment]
@JackWillDavis obviously do your own testing of this prior to rolling / hot fixing but it's 1 line in 2 files. 1 to drop it as required by elmsln_core and another to drop it from shared_settings. In testing on our prod I was able to comment both lines out without issues in existing sites (the shared_settings call for `path_inc` was my only concern but on stage it didnt brick and then did it on prod without issue).

**Comment by JackWillDavis** [comment]
Ahh nice one, let me give it a go on our development server now.

**Comment by JackWillDavis** [comment]
Yeah that's worked on our development server 👍 thanks a lot! I do have a question on initial course setup on the new version but I'll send that over Slack quickly.

Thanks again!
