### ISSUE TITLE
[elmsln] elmsln_bakery_authority override is being ignored on course creation

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#969]
Previously, we've been able to override the default bakery authority value using a conf setting in shared_settings.php like this:

`$conf['elmsln_bakery_authority'] = 'cis';`

When creating a course service in ELMSLN v1.2.1, it doesn't seem to take into account this setting and defaults bakery to looking to `people` as the master site. Would it be possible to reinstate this or is it just that the conf value has changed to something else in newer versions of ELMS?

**Comment by btopro** [comment]
`elmsln_bakery_authority` is used in `elmsln_bakery_install`. If this module runs its install prior to the global conf file being there for shared settings its possible to miss. Otherwise the setting is never referenced. This means it could be modified in the CIS's build step as far as when it prints the file. Here's the variables that that one is controlling:

```php
$bakery_authority = variable_get('elmsln_bakery_authority', 'cpr');
  // set the domain which things can respond to
  variable_set('bakery_domain', '.' . $cfg['address']);
  // need to look at current site for it being the 'people' domain
  if (elmsln_core_get_profile_key() == $bakery_authority) {
    $children = array();
    // build out the children that this can respond to
    foreach ($settings as $key => $system) {
      // ensure custom usage of the registry doesn't bleed over into this
      // as well as this not being the people distro which is the authority
      if (!isset($system['custom']) && $key != $bakery_authority) {
        $children[] = _cis_connector_format_address($system, '/', 'front');
      }
    }
    variable_set('bakery_slaves', $children);
    variable_set('bakery_is_master', 1);
  }
  else {
    variable_set('bakery_is_master', 0);
  }
  // people distro is the master for this
  $bakery_master = _cis_connector_format_address($settings[$bakery_authority], '/', 'front');
  variable_set('bakery_master', $bakery_master);
```
