### ISSUE TITLE
[hax] Cannot paste content into website

### ISSUE THREAD

**Issue by JAlbert2** [elmsln/issues#983]
I have a normal paragraph tag in hax.psu.edu. When I hit paste, this happens.
<img width="1440" alt="Screen Shot 2022-05-09 at 10 38 54 AM" src="https://user-images.githubusercontent.com/34032765/167434575-96360e36-bfe8-4c63-ae86-c20f9db32752.png">

I have to reload the page to fix the bug, but the content isn't pasted over.
:)

**Comment by JAlbert2** [comment]
Safari bug

**Comment by btopro** [comment]
were you able to paste in safari or was this a mis-report?

**Comment by JAlbert2** [comment]
It's a safari specific bug, chrome works ok
