### ISSUE TITLE
[hax] Share

### ISSUE THREAD

**Issue by JAlbert2** [elmsln/issues#984]
Share with other people

**Comment by btopro** [comment]
need a button for "share" in the top bar and it to present the multiple options for sharing the URL w/ others and their access levels as a result of that.
- Course (anyone with a PSU account)
- OER (anyone anywhere, no login)
- Sites (anyone with a PSU account)
- Editor rights in the current site (check if same site exists in THEIR profile)

**Comment by btopro** [comment]
this would be a good place to put #609 options. We could have a "share" button in the dropdown user menu and then if we pop a modal that has some different menu options for checking and selecting the features to disable, theme to present in, etc.

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/186974118-9b024ac7-279a-4cfe-9804-d3d67662776b.png)
