### ISSUE TITLE
[elmsln] Running drush command with quotes fails in new course hook

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#989]
This is more of a question as it's probably me implementing this incorrectly!

I'm using the `hook_cis_service_instance_TOOL_options_alter` hook to run a drush command when creating a new course site in ELMSLN. The drush command is using the `role-add-perm` to assign a permission automatically on course creation.

I'm implementing it like this:

```
/**
 * Implements hook_cis_service_instance_TOOL_options_alter().
 */
function my_module_cis_service_instance_courses_options_alter(&$options, $course, $service) {

  $options['role-add-perm'][] = "'authenticated user' 'access mooc-content app'";

}
```

Whenever this is included (and I've tried loads of combinations of quotes) it causes the course install to fail, although there are no errors.

The drush command itself works fine when I run it on the command line like this: `drush @courses.name role-add-perm 'authenticated user' 'access mooc-content app'` but fails when part of the hook.

Could anyone provide a pointer to how best to implement this in ELMS?

**Comment by JackWillDavis** [comment]
Sorry, I fake news'd this issue earlier. There are error messages: `bad characters in the course file`.

**Comment by btopro** [comment]
good to close?
