### ISSUE TITLE
Theme CSS tweaks

### ISSUE THREAD

**Issue by michael-collins** [elmsln/issues#991]
When looking at the course content in a certain breakpoint, the top bar floats down over the text (iPad, so probably a Safari issue). Also, I put some recommendations to add some white space on either side of the text to make content more readable. See image:

![image](https://user-images.githubusercontent.com/1085304/170682201-8f5bb0db-8c67-4adb-9cfb-28c7ab6a1272.jpeg)

**Comment by btopro** [comment]
Was mostly cleaned up in the next version to go up (shooting for this fall, have to clean stuff up still) added commit that resolves both suggestions here
