### ISSUE TITLE
Print themes for HAX

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#992]
Functions to print page, lesson, and course as HTML with consistent print CSS or PDF so that users can print or that authors can iframe content into canvas without navigation and header.

**Comment by btopro** [comment]
#984 should handle about 1/2 of this. #755 another 1/2. Just need to
- [ ] execute print window / pop up w/ the print button visible in print mode of the response content
- [ ] label the print button (not doing popover atm)
- [ ] PDF print #1023
