### ISSUE TITLE
[hax] H5P resizing via h5p-element

### ISSUE THREAD

**Issue by cgldevel** [elmsln/issues#997]
I recently ran into a bug where h5p elements weren't resizing correctly on oer.hax.psu.edu/course.  However, I noticed when in 'edit' mode at (iam.hax.psu.edu), all elements resized correctly.

The reason is that when in edit mode, h5p-element is loaded into the DOM so that you can place tag onto page thereby creating a new h5p-element. However, in 'view' mode, h5p-element is never referenced, so it fails to correct sizing.

Possible Fix: Add `<h5p-element></h5p-element>` to index.php output so it DOES get referenced in 'view' mode / public urls.

This seemed to do the trick, although probably not best long-term solution.

**Comment by btopro** [comment]
hmm...
- hack it into place
- support custom JS / CSS injection per site (ala drupal module w/ that name)
- add it to the custom directory to run something like...
```
setTimeout(function() {
  document.body.appendChild(document.createElement('h5p-element'));
},1000);
```

I like the last option bc we already have stuff built in to call `custom/build/custom.es6.js` and adding this line above (untested but I believe that'll do it) will inject the tag which will get hydrated by the existing scripts :)
